/**
*Moteurastronomique:tempssidéral,conversionsdecoordonnées,
*positionsduSoleil,delaLuneetdesplanètes(élémentsorbitaux
*keplériens,méthodedePaulSchlyter),phaseslunaires,levers/couchers.
*Précisiontypique:quelquesminutesd'arc—largementsuffisantpour
*pointeruninstrumentamateur.
*/

exportconstDEG=Math.PI/180;
exportconstRAD=180/Math.PI;

exportinterfaceGeoPosition{
latitude:number;
longitude:number;
}

exportinterfaceEquatorial{
ra:number;//degrés
dec:number;//degrés
}

exportinterfaceHorizontal{
alt:number;//degrésau-dessusdel'horizon
az:number;//degrésdepuislenord,senshoraire
}

constrev=(x:number)=>((x%360)+360)%360;
constsind=(x:number)=>Math.sin(x*DEG);
constcosd=(x:number)=>Math.cos(x*DEG);
consttand=(x:number)=>Math.tan(x*DEG);
constasind=(x:number)=>Math.asin(Math.max(-1,Math.min(1,x)))*RAD;
constatan2d=(y:number,x:number)=>Math.atan2(y,x)*RAD;

/**Nombredejoursdepuisle0.0janvier2000(échelledeSchlyter).*/
exportfunctiondayNumber(date:Date):number{
consty=date.getUTCFullYear();
constm=date.getUTCMonth()+1;
constd=date.getUTCDate();
constut=
date.getUTCHours()+
date.getUTCMinutes()/60+
date.getUTCSeconds()/3600+
date.getUTCMilliseconds()/3600000;
constt=
367*y-
Math.floor((7*(y+Math.floor((m+9)/12)))/4)+
Math.floor((275*m)/9)+
d-
730530;
returnt+ut/24;
}

exportfunctionjulianDay(date:Date):number{
returndate.getTime()/86400000+2440587.5;
}

/**Obliquitédel'écliptiqueendegrés.*/
exportfunctionobliquity(d:number):number{
return23.4393-3.563e-7*d;
}

/**Tempssidérallocalendegrés.*/
exportfunctionlocalSiderealTime(date:Date,longitude:number):number{
constd=dayNumber(date);
constw=282.9404+4.70935e-5*d;
constM=356.047+0.9856002585*d;
constgmst0=rev(w+M+180);
constut=
date.getUTCHours()+
date.getUTCMinutes()/60+
date.getUTCSeconds()/3600;
returnrev(gmst0+ut*15.04107+longitude);
}

exportfunctionequatorialToHorizontal(
eq:Equatorial,
lst:number,
latitude:number,
):Horizontal{
constha=rev(lst-eq.ra);
constsinAlt=
sind(eq.dec)*sind(latitude)+cosd(eq.dec)*cosd(latitude)*cosd(ha);
constalt=asind(sinAlt);
constaz=rev(
atan2d(
-sind(ha)*cosd(eq.dec),
sind(eq.dec)*cosd(latitude)-cosd(eq.dec)*sind(latitude)*cosd(ha),
),
);
return{alt,az};
}

/**Réfractionatmosphériqueapprochée(degrés)pourunealtitudeapparente.*/
exportfunctionrefraction(altitude:number):number{
if(altitude<-1)return0;
return0.0167/tand(altitude+7.31/(altitude+4.4));
}

functioneclipticToEquatorial(
lon:number,
lat:number,
r:number,
ecl:number,
):Equatorial&{distance:number}{
constx=r*cosd(lon)*cosd(lat);
consty=r*sind(lon)*cosd(lat);
constz=r*sind(lat);
constxe=x;
constye=y*cosd(ecl)-z*sind(ecl);
constze=y*sind(ecl)+z*cosd(ecl);
return{
ra:rev(atan2d(ye,xe)),
dec:asind(ze/Math.sqrt(xe*xe+ye*ye+ze*ze)),
distance:r,
};
}

interfaceElements{
N:number;
i:number;
w:number;
a:number;
e:number;
M:number;
}

constPLANET_ELEMENTS:Record<string,(d:number)=>Elements>={
mercure:(d)=>({
N:48.3313+3.24587e-5*d,
i:7.0047+5.0e-8*d,
w:29.1241+1.01444e-5*d,
a:0.387098,
e:0.205635+5.59e-10*d,
M:168.6562+4.0923344368*d,
}),
venus:(d)=>({
N:76.6799+2.4659e-5*d,
i:3.3946+2.75e-8*d,
w:54.891+1.38374e-5*d,
a:0.72333,
e:0.006773-1.302e-9*d,
M:48.0052+1.6021302244*d,
}),
mars:(d)=>({
N:49.5574+2.11081e-5*d,
i:1.8497-1.78e-8*d,
w:286.5016+2.92961e-5*d,
a:1.523688,
e:0.093405+2.516e-9*d,
M:18.6021+0.5240207766*d,
}),
jupiter:(d)=>({
N:100.4542+2.76854e-5*d,
i:1.303-1.557e-7*d,
w:273.8777+1.64505e-5*d,
a:5.20256,
e:0.048498+4.469e-9*d,
M:19.895+0.0830853001*d,
}),
saturne:(d)=>({
N:113.6634+2.3898e-5*d,
i:2.4886-1.081e-7*d,
w:339.3939+2.97661e-5*d,
a:9.55475,
e:0.055546-9.499e-9*d,
M:316.967+0.0334442282*d,
}),
uranus:(d)=>({
N:74.0005+1.3978e-5*d,
i:0.7733+1.9e-8*d,
w:96.6612+3.0565e-5*d,
a:19.18171-1.55e-8*d,
e:0.047318+7.45e-9*d,
M:142.5905+0.011725806*d,
}),
neptune:(d)=>({
N:131.7806+3.0173e-5*d,
i:1.77-2.55e-7*d,
w:272.8461-6.027e-6*d,
a:30.05826+3.313e-8*d,
e:0.008606+2.15e-9*d,
M:260.2471+0.005995147*d,
}),
};

functioneccentricAnomaly(M:number,e:number):number{
letE=M+RAD*e*sind(M)*(1+e*cosd(M));
for(letk=0;k<12;k++){
constdE=(E-RAD*e*sind(E)-M)/(1-e*cosd(E));
E-=dE;
if(Math.abs(dE)<1e-8)break;
}
returnE;
}

functionheliocentric(el:Elements){
constE=eccentricAnomaly(rev(el.M),el.e);
constxv=el.a*(cosd(E)-el.e);
constyv=el.a*(Math.sqrt(1-el.e*el.e)*sind(E));
constv=atan2d(yv,xv);
constr=Math.sqrt(xv*xv+yv*yv);
constlon=v+el.w;
constx=
r*(cosd(el.N)*cosd(lon)-sind(el.N)*sind(lon)*cosd(el.i));
consty=
r*(sind(el.N)*cosd(lon)+cosd(el.N)*sind(lon)*cosd(el.i));
constz=r*sind(lon)*sind(el.i);
return{x,y,z,r};
}

exportfunctionsunPosition(date:Date):Equatorial&{
distance:number;
lon:number;
x:number;
y:number;
}{
constd=dayNumber(date);
constw=282.9404+4.70935e-5*d;
conste=0.016709-1.151e-9*d;
constM=rev(356.047+0.9856002585*d);
constE=M+RAD*e*sind(M)*(1+e*cosd(M));
constxv=cosd(E)-e;
constyv=Math.sqrt(1-e*e)*sind(E);
constv=atan2d(yv,xv);
constr=Math.sqrt(xv*xv+yv*yv);
constlon=rev(v+w);
constecl=obliquity(d);
consteq=eclipticToEquatorial(lon,0,r,ecl);
return{
...eq,
lon,
x:r*cosd(lon),
y:r*sind(lon),
};
}

exportfunctionmoonPosition(date:Date):Equatorial&{
distance:number;
phase:number;//0=nouvellelune,0.5=pleinelune
illumination:number;//0→1
}{
constd=dayNumber(date);
constN=rev(125.1228-0.0529538083*d);
consti=5.1454;
constw=rev(318.0634+0.1643573223*d);
consta=60.2666;
conste=0.0549;
constM=rev(115.3654+13.0649929509*d);
const{x,y,z}=heliocentric({N,i,w,a,e,M});
letlon=rev(atan2d(y,x));
letlat=asind(z/Math.sqrt(x*x+y*y+z*z));
letr=Math.sqrt(x*x+y*y+z*z);

//Perturbationsprincipales
constsun=sunPosition(date);
constMs=rev(356.047+0.9856002585*d);
constLs=rev(sun.lon);
constLm=rev(N+w+M);
constD=rev(Lm-Ls);
constF=rev(Lm-N);

lon+=
-1.274*sind(M-2*D)+
0.658*sind(2*D)-
0.186*sind(Ms)-
0.059*sind(2*M-2*D)-
0.057*sind(M-2*D+Ms)+
0.053*sind(M+2*D)+
0.046*sind(2*D-Ms)+
0.041*sind(M-Ms)-
0.035*sind(D)-
0.031*sind(M+Ms)-
0.015*sind(2*F-2*D)+
0.011*sind(M-4*D);
lat+=
-0.173*sind(F-2*D)-
0.055*sind(M-F-2*D)-
0.046*sind(M+F-2*D)+
0.033*sind(F+2*D)+
0.017*sind(2*M+F);
r+=-0.58*cosd(M-2*D)-0.46*cosd(2*D);

constecl=obliquity(d);
consteq=eclipticToEquatorial(rev(lon),lat,r,ecl);
constelong=rev(lon-Ls);
constphaseAngle=180-elong;
constillumination=(1+cosd(phaseAngle))/2;
return{
ra:eq.ra,
dec:eq.dec,
distance:r*6371,//kmapprox(rayonsterrestres→km)
phase:rev(elong)/360,
illumination,
};
}

exportfunctionplanetPosition(
name:keyoftypeofPLANET_ELEMENTS,
date:Date,
):Equatorial&{distance:number;magnitude:number}{
constd=dayNumber(date);
constel=PLANET_ELEMENTS[name]!(d);
constp=heliocentric({...el,M:rev(el.M)});
constsun=sunPosition(date);
constx=p.x+sun.x;
consty=p.y+sun.y;
constz=p.z;
constr=Math.sqrt(x*x+y*y+z*z);
constlon=rev(atan2d(y,x));
constlat=asind(z/r);
constecl=obliquity(d);
consteq=eclipticToEquatorial(lon,lat,r,ecl);
return{
ra:eq.ra,
dec:eq.dec,
distance:r,
magnitude:approxMagnitude(name,p.r,r,sun.distance),
};
}

functionapproxMagnitude(
name:string,
helioDist:number,
geoDist:number,
sunDist:number,
):number{
constbase:Record<string,number>={
mercure:-0.36,
venus:-4.34,
mars:-1.51,
jupiter:-9.25,
saturne:-9.0,
uranus:-7.15,
neptune:-6.9,
};
constcosPhase=
(helioDist*helioDist+geoDist*geoDist-sunDist*sunDist)/
(2*helioDist*geoDist);
constphaseAngle=Math.acos(Math.max(-1,Math.min(1,cosPhase)))*RAD;
return(
(base[name]??0)+
5*Math.log10(helioDist*geoDist)+
0.013*phaseAngle
);
}

exportconstPLANET_NAMES=[
"mercure",
"venus",
"mars",
"jupiter",
"saturne",
"uranus",
"neptune",
]asconst;

exporttypePlanetName=(typeofPLANET_NAMES)[number];

/**Altituded'unobjetfixeàuninstantdonné.*/
exportfunctionaltitudeAt(
eq:Equatorial,
date:Date,
pos:GeoPosition,
):number{
constlst=localSiderealTime(date,pos.longitude);
returnequatorialToHorizontal(eq,lst,pos.latitude).alt;
}

exportinterfaceRiseSet{
rise:Date|null;
set:Date|null;
transit:Date|null;
maxAltitude:number;
alwaysUp:boolean;
neverUp:boolean;
}

/**
*Lever/coucher/passageauméridienparéchantillonnagesur24h
*autourdeladatefournie.
*/
exportfunctionriseSetTimes(
eq:Equatorial|((d:Date)=>Equatorial),
date:Date,
pos:GeoPosition,
horizon=-0.583,
):RiseSet{
constat=(d:Date)=>(typeofeq==="function"?eq(d):eq);
conststart=newDate(date);
start.setHours(0,0,0,0);
conststepMin=5;
letprevAlt=altitudeAt(at(start),start,pos);
letrise:Date|null=null;
letset:Date|null=null;
lettransit:Date|null=null;
letmaxAltitude=prevAlt;
letminAltitude=prevAlt;

for(letm=stepMin;m<=24*60;m+=stepMin){
constt=newDate(start.getTime()+m*60000);
constalt=altitudeAt(at(t),t,pos);
if(alt>maxAltitude){
maxAltitude=alt;
transit=t;
}
if(alt<minAltitude)minAltitude=alt;
if(prevAlt<horizon&&alt>=horizon&&!rise){
rise=interpolate(start,m-stepMin,m,prevAlt,alt,horizon,at,pos);
}
if(prevAlt>=horizon&&alt<horizon&&!set){
set=interpolate(start,m-stepMin,m,prevAlt,alt,horizon,at,pos);
}
prevAlt=alt;
}

return{
rise,
set,
transit,
maxAltitude,
alwaysUp:minAltitude>horizon,
neverUp:maxAltitude<horizon,
};
}

functioninterpolate(
start:Date,
m0:number,
m1:number,
a0:number,
a1:number,
horizon:number,
at:(d:Date)=>Equatorial,
pos:GeoPosition,
):Date{
letlo=m0;
lethi=m1;
letloAlt=a0;
for(letk=0;k<12;k++){
constmid=(lo+hi)/2;
constt=newDate(start.getTime()+mid*60000);
constalt=altitudeAt(at(t),t,pos);
if((loAlt<horizon)===(alt<horizon)){
lo=mid;
loAlt=alt;
}else{
hi=mid;
}
}
returnnewDate(start.getTime()+((lo+hi)/2)*60000);
}

exportinterfaceTwilightInfo{
sunset:Date|null;
sunrise:Date|null;
nauticalDusk:Date|null;
astronomicalDusk:Date|null;
astronomicalDawn:Date|null;
}

exportfunctiontwilight(date:Date,pos:GeoPosition):TwilightInfo{
constsunEq=(d:Date)=>{
consts=sunPosition(d);
return{ra:s.ra,dec:s.dec};
};
constday=riseSetTimes(sunEq,date,pos,-0.833);
constnautical=riseSetTimes(sunEq,date,pos,-12);
constastro=riseSetTimes(sunEq,date,pos,-18);
return{
sunset:day.set,
sunrise:day.rise,
nauticalDusk:nautical.set,
astronomicalDusk:astro.set,
astronomicalDawn:astro.rise,
};
}

exportfunctionmoonPhaseName(phase:number):string{
constp=((phase%1)+1)%1;
if(p<0.03||p>0.97)return"Nouvellelune";
if(p<0.22)return"Premiercroissant";
if(p<0.28)return"Premierquartier";
if(p<0.47)return"Gibbeusecroissante";
if(p<0.53)return"Pleinelune";
if(p<0.72)return"Gibbeusedécroissante";
if(p<0.78)return"Dernierquartier";
return"Derniercroissant";
}

exportfunctionformatTime(d:Date|null):string{
if(!d)return"—";
returnd.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});
}

exportfunctionformatDegrees(v:number):string{
return`${v>=0?"":"−"}${Math.abs(v).toFixed(1)}°`;
}

exportfunctioncardinalName(az:number):string{
constnames=[
"N",
"NNE",
"NE",
"ENE",
"E",
"ESE",
"SE",
"SSE",
"S",
"SSO",
"SO",
"OSO",
"O",
"ONO",
"NO",
"NNO",
];
returnnames[Math.round(rev(az)/22.5)%16]!;
}
