import{generateText}from"ai";
import{createLovableAiGatewayProvider}from"@/lib/ai-gateway.server";

//——————————————————————————————————————————
//Types
//——————————————————————————————————————————

exportinterfaceFrameMetadata{
telescope?:string;
camera?:string;
focal_length_mm?:number;
aperture_mm?:number;
focal_ratio?:number;
pixel_size_um?:number;
sensor_width_px?:number;
sensor_height_px?:number;
exposure_s?:number;
gain?:number;
offset_int?:number;
temperature_c?:number;
filter_name?:string;
binning?:number;
latitude?:number;
longitude?:number;
captured_at?:string;
//FITSheaderraw(optionnel)
fits_headers?:Record<string,string|number>;
}

exportinterfaceQualityAnalysis{
quality_score:number;//0–1
fwhm?:number;//arcsec
eccentricity?:number;//0–1
snr?:number;
background_gradient?:number;//0–1(0=flat)
star_count?:number;
rejected:boolean;
rejection_reason?:string;
instrument_group:string;//hashdecompatibilité
notes:string[];
recommendations:string[];
ai_analysis:Record<string,unknown>;
}

exportinterfaceStackingCompatibility{
compatible:boolean;
reason?:string;
instrument_group:string;
normalization_params:{
scale_factor:number;
zero_point:number;
rotation_deg:number;
};
}

exportinterfacePipelineStep{
name:string;
status:"pending"|"running"|"done"|"skipped"|"failed";
result?:string;
duration_ms?:number;
}

//——————————————————————————————————————————
//Helpers
//——————————————————————————————————————————

functiongetProvider(){
constapiKey=
process.env["LOVABLE_API_KEY"]??process.env["VITE_LOVABLE_API_KEY"]??"";
returncreateLovableAiGatewayProvider(apiKey);
}

/**
*Génèreunidentifiantdegroupeinstrumentbasésurlesparamètresoptiques.
*Desframescompatiblesaurontlemêmegroup—utilepourlestackingcohérent.
*/
exportfunctioncomputeInstrumentGroup(meta:FrameMetadata):string{
constfl=meta.focal_length_mm?Math.round(meta.focal_length_mm/50)*50:0;
constpx=meta.pixel_size_um?Math.round(meta.pixel_size_um*10):0;
constbin=meta.binning??1;
constcam=(meta.camera??"unknown").toLowerCase().replace(/\s+/g,"_").slice(0,20);
return`fl${fl}_px${px}_bin${bin}_${cam}`;
}

/**
*Estimationdelaqualitébaséesurlesmétadonnées(sansvraieanalysed'image).
*UnvraipipelineutiliseraitFITS+traitementd'imageserveur.
*/
exportfunctionestimateQualityFromMeta(meta:FrameMetadata):Partial<QualityAnalysis>{
constnotes:string[]=[];
constrecommendations:string[]=[];
letscore=0.7;//scoredebase

//Exposurestrèscourtesoutrèslongues
if(meta.exposure_s!==undefined){
if(meta.exposure_s<10){score-=0.15;notes.push("Expositiontrèscourte(<10s)");}
elseif(meta.exposure_s>600){notes.push("Longueexposition(>600s)—risquedeguidage");}
elsescore+=0.05;
}

//Temperaturecalibrationdesdarks
if(meta.temperature_c!==undefined&&meta.temperature_c>10){
notes.push("Températurecapteurélevée—bruitthermiqueaccru");
score-=0.1;
}

//Binningélevé=moinsderésolution
if((meta.binning??1)>2){
notes.push("Binningélevé—résolutionréduite");
score-=0.05;
recommendations.push("Préférezbin1x1ou2x2pourlesobjetspetits");
}

//Filtre
if(meta.filter_name){
if(["Ha","OIII","SII","Hbeta"].includes(meta.filter_name)){
score+=0.05;
notes.push(`Filtrenarrowband${meta.filter_name}—excellenterejectiondepollutionlumineuse`);
}
}else{
recommendations.push("Préciserlefiltreutiliséaméliorelematchingdecompatibilité");
}

return{
quality_score:Math.max(0.1,Math.min(0.99,score)),
instrument_group:computeInstrumentGroup(meta),
notes,
recommendations,
rejected:false,
};
}

//——————————————————————————————————————————
//AnalyseIAd'uneframeviadescription/metadata
//——————————————————————————————————————————

exportasyncfunctionanalyzeFrameWithAI(
objectId:string,
frameType:string,
meta:FrameMetadata,
filename:string
):Promise<QualityAnalysis>{
try{
constprovider=getProvider();

constmetaSummary=[
`Objet:${objectId}`,
`Type:${frameType}`,
`Fichier:${filename}`,
meta.telescope?`Télescope:${meta.telescope}`:null,
meta.camera?`Caméra:${meta.camera}`:null,
meta.focal_length_mm?`Focale:${meta.focal_length_mm}mm`:null,
meta.aperture_mm?`Ouverture:f/${(meta.focal_length_mm!/meta.aperture_mm).toFixed(1)}`:null,
meta.exposure_s?`Pose:${meta.exposure_s}s`:null,
meta.gain!==undefined?`Gain:${meta.gain}`:null,
meta.temperature_c!==undefined?`Temp:${meta.temperature_c}°C`:null,
meta.filter_name?`Filtre:${meta.filter_name}`:null,
meta.binning?`Binning:${meta.binning}x${meta.binning}`:null,
meta.latitude?`Lieu:${meta.latitude.toFixed(2)}°,${meta.longitude?.toFixed(2)}°`:null,
]
.filter(Boolean)
.join("\n");

const{text:raw}=awaitgenerateText({
model:provider("gpt-4o"),
messages:[
{
role:"system",
content:`Tuesunexpertenastrophotographieettraitementd'imagesastronomiques.
Analyselesmétadonnéesd'uneframeastrophotographiqueetdonneuneévaluationdesaqualitépotentiellepourunstackingcollaboratifmondial.
RépondsUNIQUEMENTenJSONvalidesansmarkdown:
{
"quality_score":0.0-1.0,
"fwhm_estimate":nombre_ou_null,
"snr_estimate":nombre_ou_null,
"rejected":false,
"rejection_reason":"raisonounull",
"compatibility_notes":["note1","note2"],
"improvement_recommendations":["conseil1"],
"stacking_value":"descriptioncourtedelavaleurpourlemastermondial",
"instrument_tier":"amateur_entry|amateur_mid|amateur_advanced|professional"
}`,
},
{
role:"user",
content:`Évaluecetteframe:\n\n${metaSummary}`,
},
],
});

constparsed=JSON.parse(raw.trim());
constbaseMeta=estimateQualityFromMeta(meta);

return{
quality_score:parsed.quality_score??baseMeta.quality_score??0.5,
fwhm:parsed.fwhm_estimate??undefined,
snr:parsed.snr_estimate??undefined,
rejected:parsed.rejected??false,
rejection_reason:parsed.rejection_reason??undefined,
instrument_group:computeInstrumentGroup(meta),
notes:[
...(baseMeta.notes??[]),
...(parsed.compatibility_notes??[]),
],
recommendations:[
...(baseMeta.recommendations??[]),
...(parsed.improvement_recommendations??[]),
],
ai_analysis:parsed,
};
}catch{
//FallbacksansIA
constbase=estimateQualityFromMeta(meta);
return{
quality_score:base.quality_score??0.5,
rejected:false,
instrument_group:computeInstrumentGroup(meta),
notes:base.notes??[],
recommendations:base.recommendations??[],
ai_analysis:{fallback:true},
};
}
}

//——————————————————————————————————————————
//Simulateurdupipelinedestackingmondial
//(dansunvraisystème,ceseraitunjobasynclourd)
//——————————————————————————————————————————

exportasyncfunctionsimulateStackingPipeline(
objectId:string,
lightsCount:number,
totalExposureHours:number,
contributorsCount:number,
configurationsCount:number
):Promise<{steps:PipelineStep[];summary:string;estimated_snr_gain:number}>{
conststeps:PipelineStep[]=[
{name:"Metadatanormalization",status:"done",result:`${lightsCount}framesanalysées`},
{name:"Objectverification",status:"done",result:`Objet${objectId}confirmé`},
{name:"Platesolving",status:"done",result:`${Math.round(lightsCount*0.97)}framesrésolues`},
{name:"Calibrationcompatibility",status:"done",result:`${configurationsCount}groupesd'instruments`},
{name:"FWHManalysis",status:"done",result:`Médianeestimée:2.1"`},
{name:"PSFanalysis",status:"done",result:"PSFgaussiennedominante"},
{name:"Backgroundanalysis",status:"done",result:`${Math.round(lightsCount*0.05)}framesavecgradient`},
{name:"Clouddetection",status:"done",result:`${Math.round(lightsCount*0.03)}framesrejetées`},
{name:"Gradientdetection",status:"done",result:"Correctiongradientappliquée"},
{name:"Satellite/airplanerejection",status:"done",result:`${Math.round(lightsCount*0.02)}framesrejetées`},
{name:"Photometricnormalization",status:"done",result:`${configurationsCount}calibrationsphotométriques`},
{name:"Instrumentgrouping",status:"done",result:`${configurationsCount}sous-stackscréés`},
{name:"Sub-pixelregistration",status:"done",result:"Précision<0.1px"},
{name:"Weightedintegration",status:"done",result:`PondérationparSNRetFWHM`},
{name:"Multi-resolutionfusion",status:"done",result:`${configurationsCount}résolutionsfusionnées`},
{name:`Master${objectId}`,status:"done",result:"?Mastergénéré"},
];

//GainSNRthéorique:sqrt(N)parrapportàuneseuleframe
constsnrGain=Math.sqrt(lightsCount);

constsummary=`Master${objectId}construitàpartirde${lightsCount.toLocaleString()}lights/${totalExposureHours.toFixed(1)}hdepose/${contributorsCount}contributeurs/${configurationsCount}configurationsoptiques.GainSNRthéorique:×${snrGain.toFixed(1)}.`;

return{steps,summary,estimated_snr_gain:snrGain};
}

//——————————————————————————————————————————
//RecommandationIA:quefaut-ilphotographier?
//——————————————————————————————————————————

exportasyncfunctiongetAIContributionAdvice(
objectId:string,
currentStats:{
total_lights:number;
total_darks:number;
total_flats:number;
total_contributors:number;
total_exposure_hours:number;
},
userInstrument?:FrameMetadata
):Promise<{advice:string;priority:"low"|"medium"|"high";missing:string[]}>{
try{
constprovider=getProvider();
const{text:raw}=awaitgenerateText({
model:provider("gpt-4o"),
messages:[
{
role:"system",
content:`Tuesunexpertenastrophotographiecollaborative.Analyselesdonnéesmanquantesd'unobjetetdonnedesconseilsprécis.
RépondsenJSON:{"advice":"conseilen2-3phrases","priority":"low|medium|high","missing":["type_framemanquant"]}`,
},
{
role:"user",
content:`Objet:${objectId}
Lights:${currentStats.total_lights}(${currentStats.total_exposure_hours.toFixed(1)}h)
Darks:${currentStats.total_darks}
Flats:${currentStats.total_flats}
Contributeurs:${currentStats.total_contributors}
${userInstrument?.focal_length_mm?`Instrumentutilisateur:${userInstrument.focal_length_mm}mmf/${userInstrument.aperture_mm?(userInstrument.focal_length_mm/userInstrument.aperture_mm).toFixed(1):"?"}`:""}

Qu'est-cequimanquelepluspouraméliorerlemastermondialdecetobjet?`,
},
],
});
returnJSON.parse(raw.trim());
}catch{
constmissing:string[]=[];
if(currentStats.total_darks<50)missing.push("darks");
if(currentStats.total_flats<50)missing.push("flats");
if(currentStats.total_lights<100)missing.push("lights");
return{
advice:`${objectId}abesoindeplusde${missing.join(",")}pouraméliorersonmaster.`,
priority:currentStats.total_lights<50?"high":"medium",
missing,
};
}
}
