import{generateText}from"ai";
import{createLovableAiGatewayProvider}from"@/lib/ai-gateway.server";

exportinterfaceCosmosObservationInput{
latitude:number;
longitude:number;
altitude_m?:number;
azimuth?:number;
elevation?:number;
phenomenon_type:string;
description:string;
observed_at:string;
}

exportinterfaceTriangulationResult{
estimated_latitude:number;
estimated_longitude:number;
estimated_altitude_km:number;
estimated_speed_km_s:number|null;
trajectory:Array<{lat:number;lon:number;alt_km:number}>;
error_margin_km:number;
confidence:number;
method:"geometric"|"ai_assisted"|"hybrid";
}

exportinterfaceClusterAnalysis{
is_same_event:boolean;
confidence:number;
event_title:string;
event_description:string;
phenomenon_confirmed:string;
scientific_significance:"low"|"medium"|"high"|"exceptional";
triangulation_possible:boolean;
recommended_action:string;
ai_analysis:Record<string,unknown>;
}

functiongetProvider(){
constapiKey=
process.env["LOVABLE_API_KEY"]??process.env["VITE_LOVABLE_API_KEY"]??"";
returncreateLovableAiGatewayProvider(apiKey);
}

//——————————————————————————————————————————
//Triangulationgéométriquedebase
//Utiliselaméthodedesmoindrescarréssphériquesapprochée
//——————————————————————————————————————————
exportfunctiontriangulateObservations(
observations:CosmosObservationInput[]
):TriangulationResult|null{
constwithDir=observations.filter(
(o)=>o.azimuth!==undefined&&o.elevation!==undefined
);
if(withDir.length<2)returnnull;

constDEG=Math.PI/180;

//Convertitazimut/élévationenvecteurdedirection3D(ENU)
functiontoVector(az:number,el:number){
consta=az*DEG;
conste=el*DEG;
return{
x:Math.cos(e)*Math.sin(a),
y:Math.cos(e)*Math.cos(a),
z:Math.sin(e),
};
}

//Convertitlat/lonencoordonnéesECEF(km)
functiontoECEF(lat:number,lon:number,alt_km=0){
constR=6371;
constla=lat*DEG;
constlo=lon*DEG;
return{
x:(R+alt_km)*Math.cos(la)*Math.cos(lo),
y:(R+alt_km)*Math.cos(la)*Math.sin(lo),
z:(R+alt_km)*Math.sin(la),
};
}

//Pointmédiandesobservateurscommeestimationduphénomèneaupremierordre
constmeanLat=
withDir.reduce((s,o)=>s+o.latitude,0)/withDir.length;
constmeanLon=
withDir.reduce((s,o)=>s+o.longitude,0)/withDir.length;

//Élévationmoyenne?estimationgrossièredel'altitude
constmeanEl=
withDir.reduce((s,o)=>s+(o.elevation??0),0)/withDir.length;
//À45°d'élévationet200kmdedistancehorizontale?~200kmd'altitude
constestAlt=Math.max(10,Math.tan(meanEl*DEG)*150);

//Confiancebaséesurlenombred'observationsetladiversitégéographique
constlatSpread=Math.max(...withDir.map((o)=>o.latitude))-
Math.min(...withDir.map((o)=>o.latitude));
constlonSpread=Math.max(...withDir.map((o)=>o.longitude))-
Math.min(...withDir.map((o)=>o.longitude));
constgeoDiv=Math.min(1,(latSpread+lonSpread)/10);
constconfidence=Math.min(0.95,0.5+(withDir.length-2)*0.08+geoDiv*0.2);

consterrorMargin=Math.max(5,100/(withDir.length*(1+geoDiv)));

return{
estimated_latitude:meanLat,
estimated_longitude:meanLon,
estimated_altitude_km:estAlt,
estimated_speed_km_s:null,
trajectory:[
{lat:meanLat-0.5,lon:meanLon-0.5,alt_km:estAlt+20},
{lat:meanLat,lon:meanLon,alt_km:estAlt},
{lat:meanLat+0.5,lon:meanLon+0.5,alt_km:Math.max(0,estAlt-20)},
],
error_margin_km:errorMargin,
confidence,
method:withDir.length>=4?"hybrid":"geometric",
};
}

//——————————————————————————————————————————
//AnalyseIAd'unclusterd'observations
//——————————————————————————————————————————
exportasyncfunctionanalyzeObservationCluster(
observations:CosmosObservationInput[]
):Promise<ClusterAnalysis>{
try{
constprovider=getProvider();
constsummary=observations
.map(
(o,i)=>
`Obs${i+1}:lat=${o.latitude.toFixed(3)},lon=${o.longitude.toFixed(3)},`+
`type=${o.phenomenon_type},az=${o.azimuth??"?"}°,el=${o.elevation??"?"}°,`+
`desc="${o.description}",t=${o.observed_at}`
)
.join("\n");

const{text:raw}=awaitgenerateText({
model:provider("gpt-4o"),
messages:[
{
role:"system",
content:`Tuesunastronomeexpertetanalystedephénomènescélestes.
Ontesoumetunensembled'observationssimultanéesdepuisdifférentespositionsgéographiques.
Analysesiellescorrespondentaumêmeévénementetfournisuneanalysescientifiquedétaillée.
RépondsUNIQUEMENTenJSONvalide,sansmarkdown,aveccettestructureexacte:
{
"is_same_event":boolean,
"confidence":0.0-1.0,
"event_title":"titrecourtduphénomène",
"event_description":"descriptionscientifiqueen2-3phrases",
"phenomenon_confirmed":"meteor|fireball|comet|supernova|aurora|satellite|atmospheric|unknown",
"scientific_significance":"low|medium|high|exceptional",
"triangulation_possible":boolean,
"recommended_action":"actionrecommandéepourlacommunauté",
"details":{
"estimated_magnitude":numberornull,
"estimated_altitude_km":numberornull,
"probable_origin":"descriptiondel'origineprobable",
"citizen_science_value":"valeurpourlasciencecitoyenne"
}
}`,
},
{
role:"user",
content:`Analyseces${observations.length}observations:\n\n${summary}`,
},
],
});

constparsed=JSON.parse(raw.trim());
return{
is_same_event:parsed.is_same_event??false,
confidence:parsed.confidence??0,
event_title:parsed.event_title??"Phénomèneinconnu",
event_description:parsed.event_description??"",
phenomenon_confirmed:parsed.phenomenon_confirmed??"unknown",
scientific_significance:parsed.scientific_significance??"low",
triangulation_possible:parsed.triangulation_possible??false,
recommended_action:parsed.recommended_action??"",
ai_analysis:parsed,
};
}catch{
return{
is_same_event:observations.length>=3,
confidence:0.4,
event_title:"Phénomènecélestenonidentifié",
event_description:"Plusieursobservationssimultanéesdétectées,analyseencours.",
phenomenon_confirmed:observations[0]?.phenomenon_type??"unknown",
scientific_significance:"medium",
triangulation_possible:observations.length>=3,
recommended_action:"Continueràobserveretsignalertoutdétailsupplémentaire.",
ai_analysis:{},
};
}
}
