exportfunctionrenderErrorPage():string{
return`<!doctypehtml>
<htmllang="en">
<head>
<metacharset="utf-8"/>
<title>Thispagedidn'tload</title>
<metaname="viewport"content="width=device-width,initial-scale=1"/>
<style>
body{font:15px/1.5system-ui,-apple-system,sans-serif;background:#fafafa;color:#111;display:grid;place-items:center;min-height:100vh;margin:0;padding:1.5rem;}
.card{max-width:28rem;width:100%;text-align:center;padding:2rem;}
h1{font-size:1.25rem;margin:000.5rem;}
p{color:#4b5563;margin:001.5rem;}
.actions{display:flex;gap:0.5rem;justify-content:center;flex-wrap:wrap;}
a,button{padding:0.5rem1rem;border-radius:0.375rem;font:inherit;cursor:pointer;text-decoration:none;border:1pxsolidtransparent;}
.primary{background:#111;color:#fff;}
.secondary{background:#fff;color:#111;border-color:#d1d5db;}
</style>
</head>
<body>
<divclass="card">
<h1>Thispagedidn'tload</h1>
<p>Somethingwentwrongonourend.Youcantryrefreshingorheadbackhome.</p>
<divclass="actions">
<buttonclass="primary"onclick="location.reload()">Tryagain</button>
<aclass="secondary"href="/">Gohome</a>
</div>
</div>
</body>
</html>`;
}
