import{
moonPosition,
moonPhaseName,
planetPosition,
sunPosition,
PLANET_NAMES,
DEG,
RAD,
typePlanetName,
}from"@/lib/astro";

exporttypeEventKind=
|"lune"
|"planete"
|"conjonction"
|"meteores"
|"saison";

exportinterfaceSkyEvent{
id:string;
date:Date;
kind:EventKind;
title:string;
detail:string;
/**1=spectaculaire,3=discret*/
rank:1|2|3;
}

constPLANET_LABELS:Record<PlanetName,string>={
mercure:"Mercure",
venus:"Vénus",
mars:"Mars",
jupiter:"Jupiter",
saturne:"Saturne",
uranus:"Uranus",
neptune:"Neptune",
};

functionseparation(
a:{ra:number;dec:number},
b:{ra:number;dec:number},
):number{
constd=
Math.sin(a.dec*DEG)*Math.sin(b.dec*DEG)+
Math.cos(a.dec*DEG)*Math.cos(b.dec*DEG)*Math.cos((a.ra-b.ra)*DEG);
returnMath.acos(Math.max(-1,Math.min(1,d)))*RAD;
}

constSHOWERS:{name:string;month:number;day:number;zhr:number;detail:string}[]=
[
{name:"Quadrantides",month:1,day:3,zhr:110,detail:"Picbrefdequelquesheures,radiantdansleBouvier."},
{name:"Lyrides",month:4,day:22,zhr:18,detail:"MétéoresrapidesissusdelacomèteThatcher."},
{name:"ÊtaAquarides",month:5,day:6,zhr:50,detail:"PoussièresdelacomètedeHalley,meilleuresavantl'aube."},
{name:"DeltaAquarides",month:7,day:30,zhr:25,detail:"Longueactivitéestivale,radiantbasausud."},
{name:"Perséides",month:8,day:12,zhr:100,detail:"Lapluielapluspopulairedel'été,radiantdansPersée."},
{name:"Draconides",month:10,day:8,zhr:10,detail:"Observablesdèsledébutdesoirée,parfoisensursaut."},
{name:"Orionides",month:10,day:21,zhr:20,detail:"SecondepluieissuedelacomètedeHalley."},
{name:"Léonides",month:11,day:17,zhr:15,detail:"Météorestrèsrapides,tempêteshistoriquestousles33ans."},
{name:"Géminides",month:12,day:14,zhr:150,detail:"Laplusrichedel'année,météoreslentsetcolorés."},
{name:"Ursides",month:12,day:22,zhr:10,detail:"Petitepluiediscrèteautourdusolstice."},
];

constSEASONS:Record<number,string>={
0:"Équinoxedeprintemps",
90:"Solsticed'été",
180:"Équinoxed'automne",
270:"Solsticed'hiver",
};

/**Événementsastronomiquesàvenirsur`days`jours.*/
exportfunctionupcomingEvents(from:Date,days=120):SkyEvent[]{
constevents:SkyEvent[]=[];
conststepH=6;
conststeps=(days*24)/stepH;
letprev=snapshot(from);

for(leti=1;i<=steps;i++){
constt=newDate(from.getTime()+i*stepH*3600_000);
constcur=snapshot(t);

//Phaseslunaires
for(const[target,label]of[
[0,"Nouvellelune"],
[0.25,"Premierquartier"],
[0.5,"Pleinelune"],
[0.75,"Dernierquartier"],
]asconst){
if(crossed(prev.moonPhase,cur.moonPhase,target)){
events.push({
id:`moon-${label}-${t.toISOString().slice(0,10)}`,
date:t,
kind:"lune",
title:label,
detail:
target===0
?"Cielleplussombredumois:idéalpourlecielprofond."
:target===0.5
?"Lunetrèslumineusetoutelanuit:privilégiezlescratèresetlesplanètes."
:`${moonPhaseName(cur.moonPhase)}—premièreousecondepartiedenuitdégagée.`,
rank:target===0||target===0.5?1:3,
});
}
}

//Saisons
for(constkeyof[0,90,180,270]){
if(crossed(prev.sunLon/360,cur.sunLon/360,key/360)){
events.push({
id:`season-${key}-${t.toISOString().slice(0,10)}`,
date:t,
kind:"saison",
title:SEASONS[key]!,
detail:"Repèresaisonnier:laduréedesnuitsbascule.",
rank:3,
});
}
}

//Oppositionsetconjonctionsplanétaires
for(constpofPLANET_NAMES){
constel0=prev.elong[p]!;
constel1=cur.elong[p]!;
if(el0<178&&el1>=178&&["mars","jupiter","saturne","uranus","neptune"].includes(p)){
events.push({
id:`opp-${p}-${t.toISOString().slice(0,10)}`,
date:t,
kind:"planete",
title:`Oppositionde${PLANET_LABELS[p]}`,
detail:`${PLANET_LABELS[p]}estauplusprèsdelaTerreetvisibletoutelanuit:lameilleurepériodedel'annéepourl'observer.`,
rank:1,
});
}
}

//Rapprochements(planètesentreellesetaveclaLune)
constbodies:{key:string;label:string;eq:{ra:number;dec:number}}[]=[
{key:"lune",label:"laLune",eq:cur.moon},
...PLANET_NAMES.map((p)=>({
key:p,
label:PLANET_LABELS[p],
eq:cur.planets[p]!,
})),
];
for(leta=0;a<bodies.length;a++){
for(letb=a+1;b<bodies.length;b++){
constA=bodies[a]!;
constB=bodies[b]!;
constsep=separation(A.eq,B.eq);
constprevSep=separation(
A.key==="lune"?prev.moon:prev.planets[A.keyasPlanetName]!,
B.key==="lune"?prev.moon:prev.planets[B.keyasPlanetName]!,
);
if(sep<3&&sep<prevSep){
constnext=newDate(t.getTime()+stepH*3600_000);
constnextSnap=snapshot(next);
constnextSep=separation(
A.key==="lune"?nextSnap.moon:nextSnap.planets[A.keyasPlanetName]!,
B.key==="lune"?nextSnap.moon:nextSnap.planets[B.keyasPlanetName]!,
);
if(nextSep>sep){
events.push({
id:`conj-${A.key}-${B.key}-${t.toISOString().slice(0,10)}`,
date:t,
kind:"conjonction",
title:`Rapprochement${A.label}–${B.label}`,
detail:`Séparationminimaled'environ${sep.toFixed(1)}°:lesdeuxastrestiennentdanslemêmechampdejumelles.`,
rank:sep<1?1:2,
});
}
}
}
}

prev=cur;
}

//Pluiesd'étoilesfilantes
constyear=from.getFullYear();
for(constyof[year,year+1]){
for(constsofSHOWERS){
constd=newDate(y,s.month-1,s.day,2,0,0);
if(d>from&&d.getTime()-from.getTime()<days*86400_000){
events.push({
id:`shower-${s.name}-${y}`,
date:d,
kind:"meteores",
title:`Maximumdes${s.name}`,
detail:`${s.detail}Jusqu'à${s.zhr}météoresparheuresousuncielparfait.`,
rank:s.zhr>=80?1:2,
});
}
}
}

constseen=newSet<string>();
returnevents
.filter((e)=>(seen.has(e.id)?false:(seen.add(e.id),true)))
.sort((a,b)=>a.date.getTime()-b.date.getTime());
}

interfaceSnap{
moonPhase:number;
sunLon:number;
moon:{ra:number;dec:number};
planets:Record<PlanetName,{ra:number;dec:number}>;
elong:Record<PlanetName,number>;
}

functionsnapshot(t:Date):Snap{
constsun=sunPosition(t);
constmoon=moonPosition(t);
constplanets={}asRecord<PlanetName,{ra:number;dec:number}>;
constelong={}asRecord<PlanetName,number>;
for(constpofPLANET_NAMES){
constpos=planetPosition(p,t);
planets[p]={ra:pos.ra,dec:pos.dec};
elong[p]=separation({ra:sun.ra,dec:sun.dec},pos);
}
return{
moonPhase:moon.phase,
sunLon:sun.lon,
moon:{ra:moon.ra,dec:moon.dec},
planets,
elong,
};
}

functioncrossed(a:number,b:number,target:number):boolean{
constnorm=(v:number)=>((v-target)%1+1.5)%1-0.5;
constx=norm(a);
consty=norm(b);
returnx<0&&y>=0&&Math.abs(x)<0.1&&Math.abs(y)<0.1;
}

exportconstEVENT_LABELS:Record<EventKind,string>={
lune:"Lune",
planete:"Planètes",
conjonction:"Rapprochements",
meteores:"Étoilesfilantes",
saison:"Saisons",
};
