typeLovableErrorOptions={
mechanism?:"manual"|"onerror"|"unhandledrejection"|"react_error_boundary";
handled?:boolean;
severity?:"error"|"warning"|"info";
};

typeLovableEvents={
captureException?:(
error:unknown,
context?:Record<string,unknown>,
options?:LovableErrorOptions,
)=>void;
};

declareglobal{
interfaceWindow{
__lovableEvents?:LovableEvents;
__lovableReportRuntimeError?:(payload:{
message:string;
stack?:string;
filename?:string;
})=>void;
}
}

exportfunctionreportLovableError(error:unknown,context:Record<string,unknown>={}){
if(typeofwindow==="undefined")return;
window.__lovableEvents?.captureException?.(
error,
{
source:"react_error_boundary",
route:window.location.pathname,
...context,
},
{
mechanism:"react_error_boundary",
handled:false,
severity:"error",
},
);
//ProdReactdoesnotrethrowboundary-caughterrorstowindow.onerror,sothe
//editor'stelemetryneverseesthem.Forwardtolovable.js'sreportinghook,
//whichispresentonlyinsidetheeditorpreview.
//LoadersandserverfnscommonlythrowarawResponse;String(it)isthe
//opaque"[objectResponse]",sopulloutthestatusandURLinstead.
constmessage=
errorinstanceofResponse
?`Response${error.status}${error.url?`at${error.url}`:""}`
:errorinstanceofError
?error.message
:String(error);
conststack=errorinstanceofError?error.stack:undefined;
window.__lovableReportRuntimeError?.({
message,
...(stack!==undefined&&{stack}),
filename:window.location.pathname,
});
}
