import{
deepSky,
stars,
constellationNames,
TYPE_LABELS,
INSTRUMENT_LABELS,
typeDeepSkyObject,
typeInstrument,
}from"@/data/catalog";
import{
moonPhaseName,
moonPosition,
planetPosition,
sunPosition,
PLANET_NAMES,
typePlanetName,
}from"@/lib/astro";

exporttypeObjectKind="star"|"dso"|"planet"|"moon"|"sun";

exportinterfaceSkyObject{
key:string;
name:string;
subtitle:string;
kind:ObjectKind;
ra:number;
dec:number;
mag:number|null;
constellation:string;
instrument:Instrument;
description:string;
sizeArcmin:number;
extra?:string;
/**requêteutiliséepourretrouverdevraiesphotographies*/
photoQuery:string;
/**requêtescomplémentairespourenrichirlagalerie*/
photoQueries?:string[];
}


constTYPE_EN:Record<string,string>={
gc:"globularcluster",
oc:"opencluster",
pn:"planetarynebula",
snr:"supernovaremnant",
sfr:"nebula",
rn:"reflectionnebula",
dn:"darknebula",
s:"spiralgalaxy",
e:"ellipticalgalaxy",
i:"irregulargalaxy",
g:"galaxy",
pos:"asterism",
};

constPLANET_EN:Record<PlanetName,string>={
mercure:"Mercury",
venus:"Venus",
mars:"Mars",
jupiter:"Jupiter",
saturne:"Saturn",
uranus:"Uranus",
neptune:"Neptune",
};

constPLANET_LABELS:Record<PlanetName,string>={
mercure:"Mercure",
venus:"Vénus",
mars:"Mars",
jupiter:"Jupiter",
saturne:"Saturne",
uranus:"Uranus",
neptune:"Neptune",
};

constPLANET_DESCRIPTIONS:Record<PlanetName,string>={
mercure:
"LaplanètelaplusprocheduSoleil,toujoursbassedansleslueursducrépuscule.MontredesphasescommelaLunedansunpetittélescope.",
venus:
"L'astreleplusbrillantaprèsleSoleiletlaLune.Sesphasessontévidentesauxjumellestenuesbienstables.",
mars:"Laplanèterouge.Sacalottepolaireetsestachessombresapparaissentlorsdesoppositions,avec150mmetunbonciel.",
jupiter:
"Sesquatrelunesgaliléennessontvisiblesauxjumelles,etlesbandesnuageusesdèslepluspetittélescope.",
saturne:
"Lesanneauxsedevinentdès30×degrossissement:leplusbeauchocvisueldel'astronomieamateur.",
uranus:
"Unpetitdisqueverdâtreàpeineplusgrosqu'uneétoile,repérableauxjumellessionsaitoùchercher.",
neptune:
"Unpointbleutédemagnitude8,nécessiteunecartedechamppréciseetuntélescope.",
};

exportfunctiondsoToSkyObject(o:DeepSkyObject):SkyObject{
return{
key:`dso:${o.id}`,
name:o.name,
subtitle:`${o.id}${o.designation&&o.designation!==o.id?`·${o.designation}`:""}·${TYPE_LABELS[o.type]??"Objet"}`,
kind:"dso",
ra:o.ra,
dec:o.dec,
mag:o.mag,
constellation:constellationNames[o.con]??o.con,
instrument:o.instrument,
description:o.description,
sizeArcmin:o.size,
photoQuery:`${o.id}${o.designation&&o.designation!==o.id?o.designation:""}astronomy`,
photoQueries:[
`${o.id}${o.designation&&o.designation!==o.id?o.designation:""}`.trim(),
o.designation&&o.designation!==o.id?o.designation:`${o.id}object`,
`${o.id}${TYPE_EN[o.type]??"deepskyobject"}`,
`${o.id}telescopeimage`,
],
};

}

exportfunctionstarToSkyObject(index:number):SkyObject|null{
consts=stars[index];
if(!s)returnnull;
return{
key:`star:${index}`,
name:s.n||`${s.b||"Étoile"}${constellationNames[s.c]??s.c}`,
subtitle:`Étoile·magnitude${s.m.toFixed(2)}`,
kind:"star",
ra:s.r,
dec:s.d,
mag:s.m,
constellation:constellationNames[s.c]??s.c,
instrument:s.m<=6?"oeil-nu":"jumelles",
description:s.n
?`${s.n}estl'unedesétoilesnomméesduciel,danslaconstellation${constellationNames[s.c]??s.c}.`
:`Étoiledelaconstellation${constellationNames[s.c]??s.c}.`,
sizeArcmin:0,
photoQuery:`${s.n||`${s.b??""}${s.c}`}starastronomy`,
photoQueries:[
`${s.n||`${s.b??""}${s.c}`}star`,
`${s.n||s.b}${s.c}constellation`,
`${s.c}constellationnightsky`,
],
};

}

exportfunctionsolarSystemObjects(date:Date):SkyObject[]{
constsun=sunPosition(date);
constmoon=moonPosition(date);
constlist:SkyObject[]=[
{
key:"sun",
name:"Soleil",
subtitle:"Étoile·notreétoile",
kind:"sun",
ra:sun.ra,
dec:sun.dec,
mag:-26.7,
constellation:"—",
instrument:"oeil-nu",
description:
"NejamaisobserverleSoleilsansfiltresolairecertifié:lerisquedecécitéestimmédiatetdéfinitif.",
sizeArcmin:32,
photoQuery:"Sunphotospheresolartelescopephotograph",
photoQueries:[
"Sunphotospheretelescopephotograph",
"solarprominenceHydrogenalpha",
"sunspotgroupphotograph",
"solareclipsecorona",
],
},
{
key:"moon",
name:"Lune",
subtitle:`Satellite·${moonPhaseName(moon.phase)}`,
kind:"moon",
ra:moon.ra,
dec:moon.dec,
mag:-12.7,
constellation:"—",
instrument:"jumelles",
description:
"Lescratèressedétaillentlemieuxprèsduterminateur,laligned'ombrequiséparelejourdelanuitlunaire.",
sizeArcmin:31,
extra:`${Math.round(moon.illumination*100)}%illuminée`,
photoQuery:"Moonlunarsurfacetelescopephotograph",
photoQueries:[
"Moontelescopephotograph",
"lunarcraterCopernicus",
"lunarterminatoramateurastrophotography",
"fullmoonphotograph",
],
},

];
for(constpofPLANET_NAMES){
constpos=planetPosition(p,date);
list.push({
key:`planet:${p}`,
name:PLANET_LABELS[p],
subtitle:`Planète·magnitude${pos.magnitude.toFixed(1)}`,
kind:"planet",
ra:pos.ra,
dec:pos.dec,
mag:pos.magnitude,
constellation:"—",
instrument:
pos.magnitude<4
?"oeil-nu"
:pos.magnitude<8
?"jumelles"
:"petit-telescope",
description:PLANET_DESCRIPTIONS[p],
sizeArcmin:0.5,
extra:`${pos.distance.toFixed(2)}UAdelaTerre`,
photoQuery:`${PLANET_EN[p]}planetspacecraftphotograph`,
photoQueries:[
`${PLANET_EN[p]}planet`,
`${PLANET_EN[p]}planetspacecraftphotograph`,
`${PLANET_EN[p]}amateurtelescopeimage`,
`${PLANET_EN[p]}surface`,
],
});

}
returnlist;
}

exportfunctionfindSkyObject(key:string,date:Date):SkyObject|null{
if(key.startsWith("dso:")){
consto=deepSky.find((d)=>d.id===key.slice(4));
returno?dsoToSkyObject(o):null;
}
if(key.startsWith("star:")){
returnstarToSkyObject(Number.parseInt(key.slice(5),10));
}
returnsolarSystemObjects(date).find((o)=>o.key===key)??null;
}

exportfunctioninstrumentLabel(i:Instrument){
returnINSTRUMENT_LABELS[i];
}
