import{
deepSky,
stars,
constellationNames,
TYPE_FAMILY,
TYPE_LABELS,
typeInstrument,
}from"@/data/catalog";
import{
dsoToSkyObject,
starToSkyObject,
solarSystemObjects,
typeSkyObject,
}from"@/lib/sky-objects";
import{
equatorialToHorizontal,
localSiderealTime,
riseSetTimes,
cardinalName,
typeGeoPosition,
}from"@/lib/astro";

exporttypeFamily="planete"|"lune"|"soleil"|"etoile"|"amas"|"nebuleuse"|"galaxie";

exportconstFAMILY_LABELS:Record<Family,string>={
planete:"Planètes",
lune:"Lune",
soleil:"Soleil",
etoile:"Étoiles",
amas:"Amas",
nebuleuse:"Nébuleuses",
galaxie:"Galaxies",
};

exportinterfaceCatalogEntryextendsSkyObject{
family:Family;
typeLabel:string;
search:string;
}

/**Cataloguestatique(objetsprofonds+étoilesnommées).*/
exportconststaticCatalog:CatalogEntry[]=[
...deepSky.map((o)=>{
consts=dsoToSkyObject(o);
return{
...s,
family:TYPE_FAMILY[o.type]??"nebuleuse",
typeLabel:TYPE_LABELS[o.type]??"Objetducielprofond",
search:`${o.id}${o.designation}${o.name}${s.constellation}`.toLowerCase(),
}asCatalogEntry;
}),
...stars
.map((s,i)=>(s.n?starToSkyObject(i):null))
.filter((s):sisSkyObject=>Boolean(s))
.map((s)=>({
...s,
family:"etoile"asconst,
typeLabel:"Étoile",
search:`${s.name}${s.constellation}`.toLowerCase(),
})),
];

exportfunctionfullCatalog(date:Date):CatalogEntry[]{
constsolar=solarSystemObjects(date).map((o)=>({
...o,
family:(o.kind==="planet"
?"planete"
:o.kind==="moon"
?"lune"
:"soleil")asFamily,
typeLabel:
o.kind==="planet"?"Planète":o.kind==="moon"?"Satellite":"Étoile",
search:`${o.name}`.toLowerCase(),
}));
return[...solar,...staticCatalog];
}

exportinterfaceVisibility{
altitude:number;
azimuth:number;
direction:string;
visible:boolean;
rise:Date|null;
set:Date|null;
transit:Date|null;
maxAltitude:number;
}

exportfunctioncomputeVisibility(
o:{ra:number;dec:number},
date:Date,
pos:GeoPosition,
):Visibility{
constlst=localSiderealTime(date,pos.longitude);
consthz=equatorialToHorizontal({ra:o.ra,dec:o.dec},lst,pos.latitude);
constrs=riseSetTimes({ra:o.ra,dec:o.dec},date,pos);
return{
altitude:hz.alt,
azimuth:hz.az,
direction:cardinalName(hz.az),
visible:hz.alt>0,
rise:rs.rise,
set:rs.set,
transit:rs.transit,
maxAltitude:rs.maxAltitude,
};
}

exportinterfaceSearchFilters{
query:string;
families:Family[];
instruments:Instrument[];
maxMagnitude:number;
minAltitude:number;
onlyVisible:boolean;
constellation:string;
sort:"nom"|"magnitude"|"hauteur";
}

exportconstDEFAULT_FILTERS:SearchFilters={
query:"",
families:[],
instruments:[],
maxMagnitude:14,
minAltitude:0,
onlyVisible:false,
constellation:"",
sort:"hauteur",
};

exportinterfaceSearchResultextendsCatalogEntry{
vis:Visibility;
}

exportfunctionsearchSky(
filters:SearchFilters,
date:Date,
pos:GeoPosition,
):SearchResult[]{
constq=filters.query.trim().toLowerCase();
constout:SearchResult[]=[];
for(constentryoffullCatalog(date)){
if(filters.families.length&&!filters.families.includes(entry.family))continue;
if(filters.instruments.length&&!filters.instruments.includes(entry.instrument))
continue;
if(entry.mag!==null&&entry.mag>filters.maxMagnitude)continue;
if(filters.constellation&&entry.constellation!==filters.constellation)continue;
if(q&&!(entry.search||entry.name.toLowerCase()).includes(q))continue;
constvis=computeVisibility(entry,date,pos);
if(filters.onlyVisible&&!vis.visible)continue;
if(vis.altitude<filters.minAltitude&&filters.minAltitude>0)continue;
out.push({...entry,vis});
}
out.sort((a,b)=>{
if(filters.sort==="nom")returna.name.localeCompare(b.name,"fr");
if(filters.sort==="magnitude")return(a.mag??99)-(b.mag??99);
returnb.vis.altitude-a.vis.altitude;
});
returnout.slice(0,400);
}

exportconstconstellationOptions=Array.from(
newSet(Object.values(constellationNames)),
).sort((a,b)=>a.localeCompare(b,"fr"));

/**Scored'intérêtpourlasélection«cesoir».*/
exportfunctiontonightHighlights(
date:Date,
pos:GeoPosition,
limit=12,
):SearchResult[]{
constresults=searchSky(
{...DEFAULT_FILTERS,onlyVisible:true,maxMagnitude:10},
date,
pos,
);
returnresults
.map((r)=>({
r,
score:r.vis.altitude/90-(r.mag??8)/20+(r.family==="planete"?0.6:0),
}))
.sort((a,b)=>b.score-a.score)
.slice(0,limit)
.map((x)=>x.r);
}
