import{generateText}from"ai";
import{createLovableAiGatewayProvider}from"@/lib/ai-gateway.server";

exportinterfaceVisionAnalysisResult{
isAiGenerated:boolean;
confidence:number;
detectedFeatures:string[];
astronomicalDetails:{
objectType:string|null;
identifiedFeatures:string[];
technicalDetails:string;
}|null;
}

exportinterfaceImageComparisonResult{
differences:Array<{
description:string;
significance:"low"|"medium"|"high";
}>;
discoveries:Array<{
description:string;
confidence:number;
type:"temporal_change"|"equipment_artifact"|"celestial_feature"|"unknown";
}>;
overallSimilarity:number;
recommendations:string[];
}

functiongetProvider(){
constapiKey=process.env["LOVABLE_API_KEY"]??process.env["VITE_LOVABLE_API_KEY"]??"";
returncreateLovableAiGatewayProvider(apiKey);
}

exportasyncfunctionanalyzeImage(imageUrl:string):Promise<VisionAnalysisResult>{
try{
constprovider=getProvider();

const{text:raw}=awaitgenerateText({
model:provider("gpt-4o"),
messages:[
{
role:"user",
content:[
{
type:"text",
text:`Tuesunexpertendtectiond'imagesgnresparIAetenastronomie.
AnalysecetteimageetrpondsUNIQUEMENTenJSONvalide(sansmarkdown)avecceformatexact:
{"isAiGenerated":boolean,"confidence":number,"reasons":string[],"objectType":string|null,"identifiedFeatures":string[],"technicalDetails":string}
PourisAiGenerated:cherchetexturestroplisses,toilestropuniformes,artefactsdediffusion,patternsrptitifs,incohrencesphysiquesdelalumire.`,
},
{type:"image",image:newURL(imageUrl)},
],
},
],
});

letparsed:Record<string,unknown>;
try{
parsed=JSON.parse(raw.trim());
}catch{
return{
isAiGenerated:false,
confidence:0.5,
detectedFeatures:[],
astronomicalDetails:null,
};
}

return{
isAiGenerated:Boolean(parsed["isAiGenerated"]),
confidence:Number(parsed["confidence"]??0.5),
detectedFeatures:Array.isArray(parsed["reasons"])?(parsed["reasons"]asstring[]):[],
astronomicalDetails:{
objectType:
typeofparsed["objectType"]==="string"?(parsed["objectType"]asstring):null,
identifiedFeatures:Array.isArray(parsed["identifiedFeatures"])
?(parsed["identifiedFeatures"]asstring[])
:[],
technicalDetails:
typeofparsed["technicalDetails"]==="string"
?(parsed["technicalDetails"]asstring)
:"",
},
};
}catch(error){
console.error("Visionanalysiserror:",error);
return{
isAiGenerated:false,
confidence:0.5,
detectedFeatures:[],
astronomicalDetails:null,
};
}
}

exportasyncfunctioncompareImages(
imageUrls:string[],
objectId:string,
):Promise<ImageComparisonResult>{
if(imageUrls.length<2){
return{differences:[],discoveries:[],overallSimilarity:1,recommendations:[]};
}

try{
constprovider=getProvider();
constimagesContent=imageUrls.slice(0,6).map((url)=>({
type:"image"asconst,
image:newURL(url),
}));

const{text:raw}=awaitgenerateText({
model:provider("gpt-4o"),
messages:[
{
role:"user",
content:[
{
type:"text",
text:`Tuesunastronomeexpert.Compareces${imagesContent.length}imagesdummeobjetcleste(${objectId}).
RpondsUNIQUEMENTenJSONvalide(sansmarkdown)avecceformatexact:
{"differences":[{"description":string,"significance":"low"|"medium"|"high"}],"discoveries":[{"description":string,"confidence":number,"type":"temporal_change"|"equipment_artifact"|"celestial_feature"|"unknown"}],"overallSimilarity":number,"recommendations":string[]}
Identifielesvraiesvariationsclestesvsartefacts.Signaletoutedcouvertepotentielle.`,
},
...imagesContent,
],
},
],
});

try{
returnJSON.parse(raw.trim())asImageComparisonResult;
}catch{
return{differences:[],discoveries:[],overallSimilarity:0.8,recommendations:[]};
}
}catch(error){
console.error("Imagecomparisonerror:",error);
return{differences:[],discoveries:[],overallSimilarity:0.8,recommendations:[]};
}
}
