importjsfrom"@eslint/js";
importeslintPluginPrettierfrom"eslint-plugin-prettier/recommended";
importglobalsfrom"globals";
importreactHooksfrom"eslint-plugin-react-hooks";
importreactRefreshfrom"eslint-plugin-react-refresh";
importtseslintfrom"typescript-eslint";

exportdefaulttseslint.config(
{ignores:["dist",".output",".vinxi"]},
{
extends:[js.configs.recommended,...tseslint.configs.recommended],
files:["**/*.{ts,tsx}"],
languageOptions:{
ecmaVersion:2020,
globals:globals.browser,
},
plugins:{
"react-hooks":reactHooks,
"react-refresh":reactRefresh,
},
rules:{
...reactHooks.configs.recommended.rules,
"no-restricted-imports":[
"error",
{
paths:[
{
name:"server-only",
message:
"TanStackStartdoesnotusetheNext.js`server-only`package.Renamethemoduleto`*.server.ts`ormarkitwith`@tanstack/react-start/server-only`.",
},
],
},
],
"react-refresh/only-export-components":["warn",{allowConstantExport:true}],
"@typescript-eslint/no-unused-vars":"off",
},
},
eslintPluginPrettier,
);
