import{QueryClient,QueryClientProvider}from"@tanstack/react-query";
import{
Outlet,
Link,
createRootRouteWithContext,
useRouter,
HeadContent,
Scripts,
}from"@tanstack/react-router";
import{useEffect,typeReactNode}from"react";

importappCssfrom"../styles.css?url";
import{reportLovableError}from"../lib/lovable-error-reporting";
import{SkyProvider}from"@/lib/sky-store";
import{Toaster}from"@/components/ui/sonner";
import{supabase}from"@/integrations/supabase/client";

functionNotFoundComponent(){
return(
<divclassName="flexmin-h-screenitems-centerjustify-centerbg-backgroundpx-4">
<divclassName="max-w-mdtext-center">
<h1className="text-7xlfont-boldtext-foreground">404</h1>
<h2className="mt-4text-xlfont-semiboldtext-foreground">
Cettepagen'existepas
</h2>
<pclassName="mt-2text-smtext-muted-foreground">
Lacarteducielestvaste,maiscetteadressen'yfigurepas.
</p>
<divclassName="mt-6">
<Link
to="/"
className="inline-flexitems-centerjustify-centerrounded-mdbg-primarypx-4py-2text-smfont-mediumtext-primary-foregroundtransition-colorshover:bg-primary/90"
>
Retourauciel
</Link>
</div>
</div>
</div>
);
}

functionErrorComponent({error,reset}:{error:Error;reset:()=>void}){
console.error(error);
constrouter=useRouter();
useEffect(()=>{
reportLovableError(error,{boundary:"tanstack_root_error_component"});
},[error]);

return(
<divclassName="flexmin-h-screenitems-centerjustify-centerbg-backgroundpx-4">
<divclassName="max-w-mdtext-center">
<h1className="text-xlfont-semiboldtracking-tighttext-foreground">
Cettepagen'apaspusecharger
</h1>
<pclassName="mt-2text-smtext-muted-foreground">
Unincidentestsurvenu.Réessayezourevenezàlacarte.
</p>
<divclassName="mt-6flexflex-wrapjustify-centergap-2">
<button
onClick={()=>{
router.invalidate();
reset();
}}
className="inline-flexitems-centerjustify-centerrounded-mdbg-primarypx-4py-2text-smfont-mediumtext-primary-foregroundtransition-colorshover:bg-primary/90"
>
Réessayer
</button>
<a
href="/"
className="inline-flexitems-centerjustify-centerrounded-mdborderborder-inputbg-backgroundpx-4py-2text-smfont-mediumtext-foregroundtransition-colorshover:bg-accent"
>
Retourauciel
</a>
</div>
</div>
</div>
);
}

exportconstRoute=createRootRouteWithContext<{queryClient:QueryClient}>()({
head:()=>({
meta:[
{charSet:"utf-8"},
{name:"viewport",content:"width=device-width,initial-scale=1"},
{name:"author",content:"CarteduCiel"},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
{name:"theme-color",content:"#080d1a"},
],
links:[
{rel:"stylesheet",href:appCss},
{rel:"preconnect",href:"https://fonts.googleapis.com"},
{
rel:"preconnect",
href:"https://fonts.gstatic.com",
crossOrigin:"anonymous",
},
{
rel:"stylesheet",
href:"https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap",
},
{rel:"icon",href:"/favicon.ico",type:"image/x-icon"},
],
}),
shellComponent:RootShell,
component:RootComponent,
notFoundComponent:NotFoundComponent,
errorComponent:ErrorComponent,
});

functionRootShell({children}:{children:ReactNode}){
return(
<htmllang="fr">
<head>
<HeadContent/>
</head>
<body>
{children}
<Scripts/>
</body>
</html>
);
}

functionRootComponent(){
const{queryClient}=Route.useRouteContext();
constrouter=useRouter();

useEffect(()=>{
const{data}=supabase.auth.onAuthStateChange((event)=>{
if(
event!=="SIGNED_IN"&&
event!=="SIGNED_OUT"&&
event!=="USER_UPDATED"
)
return;
router.invalidate();
if(event!=="SIGNED_OUT")queryClient.invalidateQueries();
});
return()=>data.subscription.unsubscribe();
},[router,queryClient]);

return(
<QueryClientProviderclient={queryClient}>
<SkyProvider>
{/*Required:nestedroutesrenderhere.Removing<Outlet/>breaksallchildroutes.*/}
<Outlet/>
<Toasterposition="top-center"/>
</SkyProvider>
</QueryClientProvider>
);
}
