import{createFileRoute}from"@tanstack/react-router";
import{useCallback,useEffect,useRef,useState}from"react";
import{useChat}from"@ai-sdk/react";
import{DefaultChatTransport}from"ai";
import{Mic,MicOff,Compass,Volume2,VolumeX,Telescope}from"lucide-react";
import{toast}from"sonner";
import{PageHeader}from"@/components/AppNav";
import{useSky}from"@/lib/sky-store";
import{Button}from"@/components/ui/button";
import{Badge}from"@/components/ui/badge";
import{
Conversation,
ConversationContent,
ConversationScrollButton,
}from"@/components/ai-elements/conversation";
import{
Message,
MessageContent,
MessageResponse,
}from"@/components/ai-elements/message";
import{
PromptInput,
PromptInputTextarea,
PromptInputFooter,
PromptInputSubmit,
}from"@/components/ai-elements/prompt-input";
import{Shimmer}from"@/components/ai-elements/shimmer";

exportconstRoute=createFileRoute("/assistant")({
head:()=>({
meta:[
{title:"Vega—assistantd'observationastronomique"},
{
name:"description",
content:
"Posezvosquestionsàlavoixouauclavier:Vegasaitoùpointevotretéléphoneetvousorienteverslesplanètes,galaxiesetnébuleusesvisiblesmaintenant.",
},
{property:"og:title",content:"Vega—assistantd'observationastronomique"},
{
property:"og:description",
content:
"Unguided'astronomieconversationnelquiconnaîtvotreposition,l'heureetladirectiondevotretéléphone.",
},
],
}),
component:AssistantPage,
});

constSUGGESTIONS=[
"Quepuis-jeobserverauxjumellescesoir?",
"OùsetrouveSaturneparrapportàmoi?",
"Qu'est-cequejeviselà,maintenant?",
"Quelsévénementsastronomiquesarriventbientôt?",
];

functionAssistantPage(){
const{location,date}=useSky();
const[heading,setHeading]=useState<number|null>(null);
const[pitch,setPitch]=useState<number|null>(null);
const[compassOn,setCompassOn]=useState(false);
const[listening,setListening]=useState(false);
const[speak,setSpeak]=useState(false);
const[input,setInput]=useState("");
consttextareaRef=useRef<HTMLTextAreaElement|null>(null);
constrecognitionRef=useRef<any>(null);
constspokenRef=useRef<string|null>(null);

constctxRef=useRef({location,date,heading,pitch});
ctxRef.current={location,date,heading,pitch};

const{messages,sendMessage,status,error}=useChat({
transport:newDefaultChatTransport({
api:"/api/chat",
prepareSendMessagesRequest:({messages:m})=>({
body:{
messages:m,
context:{
latitude:ctxRef.current.location.latitude,
longitude:ctxRef.current.location.longitude,
locationName:ctxRef.current.location.name,
dateISO:ctxRef.current.date.toISOString(),
heading:ctxRef.current.heading,
pitch:ctxRef.current.pitch,
},
},
}),
}),
onError:(e)=>toast.error(e.message||"L'assistantestindisponible"),
});

constbusy=status==="submitted"||status==="streaming";

useEffect(()=>{
textareaRef.current?.focus();
},[]);
useEffect(()=>{
if(!busy)textareaRef.current?.focus();
},[busy]);

//Boussole
constenableCompass=useCallback(async()=>{
if(compassOn){
setCompassOn(false);
setHeading(null);
setPitch(null);
return;
}
constanyOrientation=DeviceOrientationEventasunknownas{
requestPermission?:()=>Promise<string>;
};
if(typeofanyOrientation?.requestPermission==="function"){
try{
constres=awaitanyOrientation.requestPermission();
if(res!=="granted"){
toast.error("Accèsàlaboussolerefusé");
return;
}
}catch{
toast.error("Boussoleindisponiblesurcetappareil");
return;
}
}
setCompassOn(true);
},[compassOn]);

useEffect(()=>{
if(!compassOn)return;
consthandler=(e:DeviceOrientationEvent&{webkitCompassHeading?:number})=>{
consth=e.webkitCompassHeading??(e.alpha!==null?360-e.alpha:null);
if(h!==null&&Number.isFinite(h))setHeading((h+360)%360);
if(e.beta!==null)setPitch(Math.max(-90,Math.min(90,90-Math.abs(e.beta))));
};
window.addEventListener("deviceorientationabsolute",handlerasEventListener);
window.addEventListener("deviceorientation",handlerasEventListener);
return()=>{
window.removeEventListener("deviceorientationabsolute",handlerasEventListener);
window.removeEventListener("deviceorientation",handlerasEventListener);
};
},[compassOn]);

//Dictéevocale
consttoggleMic=useCallback(()=>{
if(listening){
recognitionRef.current?.stop();
setListening(false);
return;
}
constSR=
(windowasany).SpeechRecognition??(windowasany).webkitSpeechRecognition;
if(!SR){
toast.error("Ladictéevocalen'estpassupportéeparcenavigateur");
return;
}
constrec=newSR();
rec.lang="fr-FR";
rec.interimResults=true;
rec.continuous=false;
rec.onresult=(ev:any)=>{
lettext="";
for(leti=0;i<ev.results.length;i++)text+=ev.results[i][0].transcript;
setInput(text);
};
rec.onerror=()=>{
setListening(false);
toast.error("Microinaccessible");
};
rec.onend=()=>setListening(false);
recognitionRef.current=rec;
rec.start();
setListening(true);
},[listening]);

//Synthèsevocaledesréponses
useEffect(()=>{
if(!speak||busy)return;
constlast=messages[messages.length-1];
if(!last||last.role!=="assistant")return;
consttext=last.parts
.map((p)=>(p.type==="text"?p.text:""))
.join("")
.trim();
if(!text||spokenRef.current===last.id)return;
spokenRef.current=last.id;
constu=newSpeechSynthesisUtterance(text);
u.lang="fr-FR";
window.speechSynthesis.cancel();
window.speechSynthesis.speak(u);
},[messages,speak,busy]);

constsubmit=(text:string)=>{
constvalue=text.trim();
if(!value||busy)return;
setInput("");
voidsendMessage({text:value});
};

return(
<mainclassName="flexmin-h-[100dvh]flex-colbg-background">
<PageHeader
title="Vega,votreguided'observation"
subtitle="Parlez-luiouécrivez:ilconnaîtvotreposition,l'heureetladirectiondevotretéléphone."
/>

<divclassName="mx-autoflexw-fullmax-w-3xlflex-1flex-colpx-4pb-6">
<divclassName="flexflex-wrapitems-centergap-2py-3">
<Badgevariant="outline">{location.name}</Badge>
<Badgevariant="outline"suppressHydrationWarning>
{date.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}
</Badge>
<Button
size="sm"
variant={compassOn?"default":"outline"}
onClick={enableCompass}
>
<CompassclassName="size-4"/>
{compassOn
?heading===null
?"Boussole…"
:`${Math.round(heading)}°`
:"Activerlaboussole"}
</Button>
<Button
size="sm"
variant={speak?"default":"outline"}
onClick={()=>{
setSpeak((v)=>!v);
if(speak)window.speechSynthesis.cancel();
}}
>
{speak?<Volume2className="size-4"/>:<VolumeXclassName="size-4"/>}
Lecturevocale
</Button>
</div>

<ConversationclassName="min-h-[45vh]flex-1rounded-xlborderborder-border/60bg-card/30">
<ConversationContent>
{!messages.length&&(
<divclassName="flexflex-colitems-centergap-4py-12text-center">
<divclassName="rounded-fullbg-primary/10p-4">
<TelescopeclassName="size-7text-primary"/>
</div>
<div>
<pclassName="font-medium">Bonsoir,jesuisVega.</p>
<pclassName="mt-1max-w-smtext-smtext-muted-foreground">
Demandez-moioùpointervotreinstrument,cequiestvisible
maintenant,oucequevousêtesentraindeviser.
</p>
</div>
<divclassName="flexflex-wrapjustify-centergap-2">
{SUGGESTIONS.map((s)=>(
<Button
key={s}
size="sm"
variant="outline"
onClick={()=>submit(s)}
>
{s}
</Button>
))}
</div>
</div>
)}

{messages.map((m)=>(
<Messagekey={m.id}from={m.role}>
<MessageContent>
{m.parts.map((part,i)=>
part.type==="text"?(
<MessageResponsekey={i}>{part.text}</MessageResponse>
):null,
)}
</MessageContent>
</Message>
))}

{status==="submitted"&&(
<ShimmerclassName="px-2text-sm">Vegaconsulteleciel…</Shimmer>
)}
{error&&(
<pclassName="px-2text-smtext-destructive">
{error.message||"Uneerreurestsurvenue."}
</p>
)}
</ConversationContent>
<ConversationScrollButton/>
</Conversation>

<PromptInput
className="mt-3"
onSubmit={(_,e)=>{
e.preventDefault();
submit(input);
}}
>
<PromptInputTextarea
ref={textareaRef}
value={input}
onChange={(e)=>setInput(e.target.value)}
placeholder={
listening?"Jevousécoute…":"Posezvotrequestionsurleciel…"
}
/>
<PromptInputFooterclassName="justify-endgap-2">
<Button
type="button"
size="icon-sm"
variant={listening?"default":"ghost"}
onClick={toggleMic}
aria-label="Dictéevocale"
>
{listening?<MicOffclassName="size-4"/>:<MicclassName="size-4"/>}
</Button>
<PromptInputSubmitstatus={status}disabled={!input.trim()||busy}/>
</PromptInputFooter>
</PromptInput>
</div>
</main>
);
}
