import{createFileRoute}from"@tanstack/react-router";
import{useState}from"react";
import{PageHeader}from"@/components/AppNav";
import{AstroObjectList}from"@/components/AstroObjectList";
import{AstroObjectMaster}from"@/components/AstroObjectMaster";
import{AstroUploadZone}from"@/components/AstroUploadZone";
import{AstroUploadQueue}from"@/components/AstroUploadQueue";
import{useAstroStack}from"@/hooks/useAstroStack";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
import{Tabs,TabsContent,TabsList,TabsTrigger}from"@/components/ui/tabs";
import{Badge}from"@/components/ui/badge";

exportconstRoute=createFileRoute("/astrostack")({
head:()=>({
meta:[
{title:"AstroStackGlobal—Moteurdefusionastrophotographique"},
{
name:"description",
content:
"ContribuezvosframesRAW,calibrezavecdesmillionsd'autresastrophotographesetobtenezlemastermondialdechaqueobjetduciel.",
},
],
}),
component:AstroStackPage,
});

functionGlobalStats({objects}:{objects:ReturnType<typeofuseAstroStack>["objects"]}){
consttotalLights=objects.reduce((s,o)=>s+o.total_lights,0);
consttotalContribs=objects.reduce((s,o)=>s+o.total_contributors,0);
consttotalHours=objects.reduce((s,o)=>s+o.total_exposure_hours,0);
constmastersCount=objects.filter((o)=>o.master_image_url).length;

return(
<divclassName="gridgrid-cols-2gap-3sm:grid-cols-4">
{[
{label:"Framesmondiales",value:totalLights.toLocaleString(),icon:"??"},
{label:"Contributeurs",value:totalContribs.toLocaleString(),icon:"??"},
{label:"Heuresdepose",value:`${totalHours.toFixed(0)}h`,icon:"??"},
{label:"Mastersgénérés",value:mastersCount.toString(),icon:"??"},
].map((s)=>(
<Cardkey={s.label}className="bg-card/50backdrop-blur-sm">
<CardContentclassName="p-3text-center">
<pclassName="text-xl">{s.icon}</p>
<pclassName="text-lgfont-boldtabular-numsmt-1">{s.value}</p>
<pclassName="text-[10px]text-muted-foreground">{s.label}</p>
</CardContent>
</Card>
))}
</div>
);
}

functionAstroStackPage(){
const{
objects,
selectedObject,
masters,
recentJobs,
userUploads,
isLoadingObjects,
isStacking,
searchQuery,
setSearchQuery,
selectObject,
uploadFrames,
triggerStacking,
}=useAstroStack();

const[activeTab,setActiveTab]=useState<"master"|"upload"|"queue">("master");

return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-24">
<PageHeader
title="AstroStackGlobal"
subtitle="Moteurdefusionastrophotographiquemondial—contribuezvosframes,améliorezlemasterdechaqueobjet"
/>

<divclassName="mx-automax-w-7xlpx-4pt-6space-y-6">

{/*En-têteconceptuel*/}
<divclassName="rounded-xlborderborder-primary/20bg-primary/5p-4">
<divclassName="flexitems-startgap-3">
<spanclassName="text-2xlshrink-0">??</span>
<divclassName="text-xstext-muted-foregroundspace-y-1">
<pclassName="text-smfont-semiboldtext-foreground">
Lepremierobservatoiredistribuépilotéparl'IA
</p>
<p>
Chaqueframequevouscontribuezaméliorelemastermondial.L'IAsélectionne
automatiquementlesmeilleuresacquisitions,lescalibre,lesnormaliseetlesstacke
enuneimagetoujoursplusprofonde—provenantdemilliersd'astrophotographes,de
dizainesdepaysetdecentainesdeconfigurationsoptiques.
</p>
</div>
</div>
</div>

{/*Statsglobales*/}
<GlobalStatsobjects={objects}/>

{/*Layoutprincipal:liste+détail*/}
<divclassName="gridgap-6lg:grid-cols-[280px_1fr]"style={{minHeight:700}}>

{/*Panneaugauche:listedesobjets*/}
<divclassName="rounded-xlborderborder-borderoverflow-hiddenflexflex-col"style={{maxHeight:700}}>
<divclassName="px-3py-2border-bborder-borderbg-muted/30">
<pclassName="text-xsfont-semiboldtext-muted-foregrounduppercasetracking-widest">
Objetsducatalogue
</p>
</div>
<AstroObjectList
objects={objects}
selected={selectedObject}
onSelect={selectObject}
searchQuery={searchQuery}
onSearch={setSearchQuery}
isLoading={isLoadingObjects}
/>
</div>

{/*Panneaudroit:onglets*/}
{selectedObject?(
<Tabsvalue={activeTab}onValueChange={(v)=>setActiveTab(vastypeofactiveTab)}>
<TabsListclassName="gridw-fullgrid-cols-3">
<TabsTriggervalue="master">
??Mastermondial
</TabsTrigger>
<TabsTriggervalue="upload">
??Contribuer
</TabsTrigger>
<TabsTriggervalue="queue">
??Filed'upload
{userUploads.length>0&&(
<Badgevariant="secondary"className="ml-1.5text-[10px]">
{userUploads.length}
</Badge>
)}
</TabsTrigger>
</TabsList>

<TabsContentvalue="master"className="mt-4">
<AstroObjectMaster
object={selectedObject}
masters={masters}
recentJobs={recentJobs}
onTriggerStack={()=>triggerStacking(selectedObject.id)}
isStacking={isStacking}
/>
</TabsContent>

<TabsContentvalue="upload"className="mt-4">
<CardclassName="bg-card/50">
<CardHeaderclassName="pb-3">
<CardTitleclassName="text-base">
??Contribuerà{selectedObject.id}
{selectedObject.common_name&&(
<spanclassName="text-smfont-normaltext-muted-foregroundml-2">
—{selectedObject.common_name}
</span>
)}
</CardTitle>
<pclassName="text-xstext-muted-foreground">
Vosframesserontanalyséesparl'IA,qualifiées,puisintégréesauprochainstackingmondial.
</p>
</CardHeader>
<CardContent>
<AstroUploadZone
objectId={selectedObject.id}
onUpload={uploadFrames}
/>
</CardContent>
</Card>

{/*Pipelineexpliqué*/}
<CardclassName="mt-4bg-card/30border-dashed">
<CardContentclassName="p-4">
<pclassName="text-xsfont-semiboldmb-3text-foreground">
??Cequisepasseaprèsvotreupload
</p>
<divclassName="space-y-1.5text-[11px]text-muted-foregroundfont-mono">
{[
["1","ExtractiondesmétadonnéesFITS/EXIF"],
["2","AnalyseIA—FWHM,SNR,gradient,satellites"],
["3","Attributiond'unscorequalité(0–100%)"],
["4","Groupementparconfigurationinstrument"],
["5","Intégrationdanslepooldestackingmondial"],
["6","Recalculdumastersiseuilatteint"],
].map(([n,step])=>(
<divkey={n}className="flexgap-2">
<spanclassName="text-primaryfont-bold">{n}.</span>
<span>{step}</span>
</div>
))}
</div>
</CardContent>
</Card>
</TabsContent>

<TabsContentvalue="queue"className="mt-4">
<CardclassName="bg-card/50">
<CardHeaderclassName="pb-3">
<CardTitleclassName="text-sm">Filedetraitement</CardTitle>
</CardHeader>
<CardContent>
<AstroUploadQueueuploads={userUploads}/>
</CardContent>
</Card>
</TabsContent>
</Tabs>
):(
<divclassName="flexflex-colitems-centerjustify-centerrounded-xlborderborder-dashedborder-borderp-12text-center">
<spanclassName="text-5xlmb-4">??</span>
<pclassName="text-basefont-semibold">Sélectionnezunobjet</p>
<pclassName="mt-2text-xstext-muted-foregroundmax-w-sm">
Choisissezunobjetdanslalistepourvoirsonmastermondial,sesstatistiques
etcontribuervosframes.
</p>
</div>
)}
</div>
</div>
</main>
);
}
