import{createFileRoute,Link,useNavigate}from"@tanstack/react-router";
import{useState}from"react";
import{toast}from"sonner";
import{supabase}from"@/integrations/supabase/client";
import{lovable}from"@/integrations/lovable/index";
import{useAuth}from"@/hooks/useAuth";
import{Button}from"@/components/ui/button";
import{Input}from"@/components/ui/input";
import{Label}from"@/components/ui/label";

exportconstRoute=createFileRoute("/auth")({
head:()=>({
meta:[
{title:"Connexion—CarteduCiel"},
{
name:"description",
content:
"Connectez-vouspourenregistrervosobjetscélestesfavorisetvoslieuxd'observation.",
},
{property:"og:title",content:"Connexion—CarteduCiel"},
{
property:"og:description",
content:"Enregistrezvosfavorisetvoslieuxd'observation.",
},
],
}),
component:AuthPage,
});

functionAuthPage(){
const{user}=useAuth();
constnavigate=useNavigate();
const[mode,setMode]=useState<"signin"|"signup">("signin");
const[email,setEmail]=useState("");
const[password,setPassword]=useState("");
const[busy,setBusy]=useState(false);

asyncfunctionsubmit(e:React.FormEvent){
e.preventDefault();
setBusy(true);
try{
if(mode==="signup"){
const{error}=awaitsupabase.auth.signUp({
email,
password,
options:{emailRedirectTo:window.location.origin},
});
if(error)throwerror;
toast.success("Vérifiezvotreboîtemailpourconfirmervotrecompte.");
}else{
const{error}=awaitsupabase.auth.signInWithPassword({
email,
password,
});
if(error)throwerror;
navigate({to:"/"});
}
}catch(err){
toast.error(errinstanceofError?err.message:"Échecdelaconnexion");
}finally{
setBusy(false);
}
}

asyncfunctiongoogle(){
constresult=awaitlovable.auth.signInWithOAuth("google",{
redirect_uri:window.location.origin,
});
if(result.error){
toast.error("ConnexionGoogleimpossible");
return;
}
if(result.redirected)return;
navigate({to:"/"});
}

if(user){
return(
<mainclassName="mx-autoflexmin-h-[100dvh]max-w-mdflex-coljustify-centergap-4px-6">
<pclassName="label-capstext-primary">Compte</p>
<h1className="text-2xlfont-semibold">{user.email}</h1>
<divclassName="flexgap-2">
<ButtonasChildvariant="secondary">
<Linkto="/">Retourauciel</Link>
</Button>
<Button
variant="ghost"
onClick={async()=>{
awaitsupabase.auth.signOut();
navigate({to:"/"});
}}
>
Sedéconnecter
</Button>
</div>
</main>
);
}

return(
<mainclassName="mx-autoflexmin-h-[100dvh]max-w-mdflex-coljustify-centerpx-6">
<pclassName="label-capstext-primary">CarteduCiel</p>
<h1className="mt-2text-2xlfont-semibold">
{mode==="signin"?"Seconnecter":"Créeruncompte"}
</h1>
<pclassName="mt-2text-smtext-muted-foreground">
Pourretrouvervosfavorisd'unenuitàl'autre.
</p>

<ButtonclassName="mt-6"variant="secondary"onClick={google}>
ContinueravecGoogle
</Button>

<formonSubmit={submit}className="mt-6space-y-3">
<div>
<LabelhtmlFor="email">E-mail</Label>
<Input
id="email"
type="email"
required
value={email}
onChange={(e)=>setEmail(e.target.value)}
/>
</div>
<div>
<LabelhtmlFor="password">Motdepasse</Label>
<Input
id="password"
type="password"
required
minLength={6}
value={password}
onChange={(e)=>setPassword(e.target.value)}
/>
</div>
<Buttontype="submit"className="w-full"disabled={busy}>
{mode==="signin"?"Seconnecter":"Créermoncompte"}
</Button>
</form>

<button
className="mt-4text-smtext-muted-foregroundunderline"
onClick={()=>setMode(mode==="signin"?"signup":"signin")}
>
{mode==="signin"
?"Pasencoredecompte?Encréerun"
:"J'aidéjàuncompte"}
</button>
<Linkto="/"className="mt-6text-smtext-primary">
←Retourauciel
</Link>
</main>
);
}
