import{createFileRoute}from"@tanstack/react-router";
import{PageHeader}from"@/components/AppNav";
import{CosmosLiveMap}from"@/components/CosmosLiveMap";
import{CosmosObservationFeed}from"@/components/CosmosObservationFeed";
import{CosmosReportForm}from"@/components/CosmosReportForm";
import{CosmosTriangulationPanel}from"@/components/CosmosTriangulationPanel";
import{useCosmosLive}from"@/hooks/useCosmosLive";
import{Button}from"@/components/ui/button";
import{Badge}from"@/components/ui/badge";
import{Tabs,TabsContent,TabsList,TabsTrigger}from"@/components/ui/tabs";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";

exportconstRoute=createFileRoute("/cosmos-live")({
head:()=>({
meta:[
{title:"CosmosLive-ObservatoireCollaboratif"},
{
name:"description",
content:
"Participezentempsréelàladétectiondemétéores,bolides,auroresetphénomènesrares.Chaquetéléphonedevientuncapteurscientifique.",
},
],
}),
component:CosmosLivePage,
});

functionCosmosLivePage(){
const{
observations,
events,
userPosition,
positionError,
isSubmitting,
isActive,
activate,
deactivate,
submitObservation,
}=useCosmosLive();

return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-24">
<PageHeader
title="CosmosLive"
subtitle="Observatoirecollaboratifmondial—chaquetéléphonedevientuncapteurscientifique"
/>

<divclassName="mx-automax-w-5xlpx-4pt-6space-y-6">
{/*Statut+activation*/}
<divclassName="flexitems-centerjustify-betweengap-4rounded-xlborderborder-borderbg-card/50p-4backdrop-blur-sm">
<divclassName="space-y-1">
<divclassName="flexitems-centergap-2">
<span
className={`inline-blocksize-2.5rounded-full${
isActive?"animate-pulsebg-green-500":"bg-muted-foreground"
}`}
/>
<spanclassName="text-smfont-semibold">
{isActive?"Modeobservationactif":"Modeobservationinactif"}
</span>
{isActive&&(
<Badgevariant="outline"className="text-[10px]text-green-400border-green-500/40">
ENDIRECT
</Badge>
)}
</div>
{positionError?(
<pclassName="text-xstext-destructive">{positionError}</p>
):userPosition?(
<pclassName="text-xstext-muted-foreground">
??{userPosition.latitude.toFixed(4)}°N,{""}
{userPosition.longitude.toFixed(4)}°E—précision{""}
{Math.round(userPosition.accuracy??0)}m
</p>
):(
<pclassName="text-xstext-muted-foreground">
GPSrequispourparticiperauxobservationsetàlatriangulation
</p>
)}
</div>
<Button
variant={isActive?"destructive":"default"}
onClick={isActive?deactivate:activate}
className="shrink-0"
>
{isActive?"?Désactiver":"?ActiverCosmosLive"}
</Button>
</div>

{/*Statistiquesglobales*/}
<divclassName="gridgrid-cols-3gap-3">
<CardclassName="bg-card/50backdrop-blur-sm">
<CardContentclassName="p-4text-center">
<pclassName="text-2xlfont-boldtabular-nums">{observations.length}</p>
<pclassName="text-[11px]text-muted-foreground">Observations(2h)</p>
</CardContent>
</Card>
<CardclassName="bg-card/50backdrop-blur-sm">
<CardContentclassName="p-4text-center">
<pclassName="text-2xlfont-boldtabular-nums">{events.length}</p>
<pclassName="text-[11px]text-muted-foreground">Événementsdétectés</p>
</CardContent>
</Card>
<CardclassName="bg-card/50backdrop-blur-sm">
<CardContentclassName="p-4text-center">
<pclassName="text-2xlfont-boldtabular-nums">
{events.filter((e)=>e.triangulation!=null).length}
</p>
<pclassName="text-[11px]text-muted-foreground">Triangulations</p>
</CardContent>
</Card>
</div>

{/*Carteendirect*/}
<section>
<h2className="mb-3text-smfont-semiboldtext-muted-foregrounduppercasetracking-widest">
Carteendirect
</h2>
<CosmosLiveMap
observations={observations}
userPosition={userPosition}
/>
</section>

{/*Contenuprincipalendeuxcolonnes*/}
<divclassName="gridgap-6lg:grid-cols-[1fr_380px]">
{/*Colonnegauche:flux+triangulations*/}
<TabsdefaultValue="feed">
<TabsListclassName="gridw-fullgrid-cols-2">
<TabsTriggervalue="feed">
Observations{""}
{observations.length>0&&(
<Badgevariant="secondary"className="ml-1.5text-[10px]">
{observations.length}
</Badge>
)}
</TabsTrigger>
<TabsTriggervalue="triangulations">
Triangulations{""}
{events.filter((e)=>e.triangulation).length>0&&(
<Badgevariant="secondary"className="ml-1.5text-[10px]">
{events.filter((e)=>e.triangulation).length}
</Badge>
)}
</TabsTrigger>
</TabsList>

<TabsContentvalue="feed"className="mt-4">
<CosmosObservationFeed
observations={observations}
events={events}
userPosition={userPosition}
/>
</TabsContent>

<TabsContentvalue="triangulations"className="mt-4">
<CosmosTriangulationPanelevents={events}/>
</TabsContent>
</Tabs>

{/*Colonnedroite:formulairedesignalement*/}
<divclassName="space-y-4">
<CardclassName="bg-card/50backdrop-blur-smstickytop-4">
<CardHeaderclassName="pb-3">
<CardTitleclassName="text-base">
??Signalerunphénomène
</CardTitle>
{!isActive&&(
<pclassName="text-xstext-muted-foreground">
ActivezCosmosLivepourpouvoirsignaleruneobservation.
</p>
)}
{isActive&&!userPosition&&(
<pclassName="text-xstext-yellow-500">
?EnattenteduGPS...
</p>
)}
</CardHeader>
<CardContent>
<CosmosReportForm
onSubmit={submitObservation}
isSubmitting={isSubmitting}
disabled={!isActive||!userPosition}
/>
</CardContent>
</Card>

{/*Explicationdusystème*/}
<CardclassName="bg-card/30border-dashed">
<CardContentclassName="p-4space-y-2text-xstext-muted-foreground">
<pclassName="font-semiboldtext-foreground">Commentçafonctionne?</p>
<olclassName="space-y-1.5list-decimallist-inside">
<li>ActivezlemodepourpartagervotrepositionGPS</li>
<li>Signaleztoutphénomèneinhabitueldansleciel</li>
<li>L'IAregroupelesobservationssimilairesenclusters</li>
<li>Si3+observateursvoientlamêmechose,latriangulationcalculealtitude,vitesseettrajectoire</li>
<li>Lesévénementsexceptionnelssontproposésauxréseauxdesciencecitoyenne</li>
</ol>
</CardContent>
</Card>
</div>
</div>
</div>
</main>
);
}
