import{createFileRoute,Link}from"@tanstack/react-router";
import{useState}from"react";
import{MapPin,Moon,Clock,LocateFixed,Sparkles}from"lucide-react";
import{SkyCanvas}from"@/components/SkyCanvas";
import{ObjectPanel}from"@/components/ObjectPanel";
import{AppNav}from"@/components/AppNav";

import{useSky}from"@/lib/sky-store";
import{useAuth}from"@/hooks/useAuth";
import{Button}from"@/components/ui/button";
import{Slider}from"@/components/ui/slider";

exportconstRoute=createFileRoute("/")({
head:()=>({
meta:[
{title:"CarteduCiel—planétariumendirect"},
{
name:"description",
content:
"Identifiezétoiles,planètes,amasetgalaxiesau-dessusdevous.Carteducielinteractiveentempsréel,avecheuresdeleveretconseilsd'observation.",
},
{property:"og:title",content:"CarteduCiel—planétariumendirect"},
{
property:"og:description",
content:
"Lecieldevotreposition,endirect:constellations,planètesetobjetsducielprofond.",
},
],
}),
component:SkyPage,
});

functionSkyPage(){
const{
location,
geolocate,
geoStatus,
date,
offsetMinutes,
setOffsetMinutes,
resetToNow,
nightMode,
toggleNightMode,
}=useSky();
const{user}=useAuth();
const[compass,setCompass]=useState(false);

return(
<mainclassName="relativeh-[100dvh]w-fulloverflow-hiddenbg-background">
<SkyCanvascompass={compass}/>

<headerclassName="glasspointer-events-autoabsoluteinset-x-3top-3z-20flexflex-wrapitems-centergap-2rounded-xlpx-3py-2">
<h1className="flexitems-centergap-2text-smfont-semibold">
<SparklesclassName="size-4text-primary"/>
CarteduCiel
</h1>
<divclassName="mr-auto">
<AppNavcompact/>
</div>

<button
onClick={geolocate}
className="flexitems-centergap-1.5rounded-mdpx-2py-1font-monotext-xstext-muted-foregroundhover:bg-accent"
>
<MapPinclassName="size-3.5"/>
{location.name}{location.latitude.toFixed(2)}°,{""}
{location.longitude.toFixed(2)}°
{geoStatus==="pending"?"…":""}
</button>
<Button
size="sm"
variant={compass?"default":"ghost"}
onClick={()=>setCompass((v)=>!v)}
title="Boussole"
>
<LocateFixedclassName="size-4"/>
</Button>
<Button
size="sm"
variant={nightMode?"default":"ghost"}
onClick={toggleNightMode}
title="Modenuit"
>
<MoonclassName="size-4"/>
</Button>
<ButtonasChildsize="sm"variant="secondary">
<Linkto="/auth">{user?"Moncompte":"Seconnecter"}</Link>
</Button>
</header>

<divclassName="glasspointer-events-autoabsoluteinset-x-3bottom-3z-10flexitems-centergap-3rounded-xlpx-4py-3sm:inset-x-autosm:left-3sm:w-[360px]">
<ClockclassName="size-4shrink-0text-primary"/>
<divclassName="min-w-0flex-1">
<pclassName="font-monotext-sm"suppressHydrationWarning>
{date.toLocaleString("fr-FR",{
weekday:"short",
day:"2-digit",
month:"short",
hour:"2-digit",
minute:"2-digit",
})}
</p>

<Slider
className="mt-2"
min={-720}
max={720}
step={5}
value={[offsetMinutes]}
onValueChange={(v)=>setOffsetMinutes(v[0]??0)}
/>
</div>
{offsetMinutes!==0&&(
<Buttonsize="sm"variant="ghost"onClick={resetToNow}>
Maintenant
</Button>
)}
</div>

<ObjectPanel/>
</main>
);
}
