import{createFileRoute,Link}from"@tanstack/react-router";
import{ArrowRight,CheckCircle2,Star}from"lucide-react";
import{PageHeader}from"@/components/AppNav";
import{CommonsImage}from"@/components/CommonsImage";
import{CATEGORIES,PROGRESSION}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/")({
head:()=>({
meta:[
{title:"Ressourcesastro—tutoriels,matériel,logicielsetcommunauté"},
{
name:"description",
content:
"Lesommairedesressourcesd'astronomie:tutorielsd'astrophotopasàpas,cataloguedematériel,logicielsdetraitement,outilsdeplanification,blogs,forumsetchaînesvidéo.",
},
{property:"og:title",content:"Ressourcesastro—sommaireparcatégorie"},
{
property:"og:description",
content:
"Sixcatégoriesderessources:tutoriels,matériel,logiciels,planification,communautéetvidéos.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:ResourcesMenu,
});

functionResourcesMenu(){
return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Ressources&tutoriels"
subtitle="Choisissezunecatégorie:guidesd'astrophotographie,matérielparrayon,logiciels,planification,communautéetvidéos."
/>

<divclassName="mx-automax-w-6xlspace-y-12px-4pt-8">
<divclassName="gridgap-5sm:grid-cols-2lg:grid-cols-3">
{CATEGORIES.map((c)=>(
<Link
key={c.slug}
to={c.to}
className="groupoverflow-hiddenrounded-2xlborderborder-border/60bg-card/40transition-colorshover:border-primary/50hover:bg-accent/30"
>
<CommonsImage
query={c.image}
alt={c.title}
className="h-44w-full"
/>
<divclassName="p-5">
<pclassName="font-monotext-[11px]uppercasetracking-widetext-primary">
{c.count}
</p>
<h2className="mt-1flexitems-centergap-1.5text-basefont-semibold">
{c.title}
<ArrowRightclassName="size-4text-muted-foregroundtransition-transformgroup-hover:translate-x-0.5group-hover:text-primary"/>
</h2>
<pclassName="mt-1.5text-smleading-relaxedtext-muted-foreground">
{c.blurb}
</p>
</div>
</Link>
))}
</div>

<sectionclassName="rounded-xlborderborder-border/60bg-card/40p-5">
<h2className="flexitems-centergap-2text-lgfont-semibold">
<StarclassName="size-4text-primary"/>Progressionconseillée
</h2>
<olclassName="mt-3space-y-2.5text-smtext-muted-foreground">
{PROGRESSION.map((s,i)=>(
<likey={i}className="flexgap-2.5">
<CheckCircle2className="mt-0.5size-4shrink-0text-primary"/>
<span>{s}</span>
</li>
))}
</ol>
</section>
</div>
</main>
);
}
