import{createFileRoute}from"@tanstack/react-router";
import{AlertTriangle,Clock}from"lucide-react";
import{PageHeader}from"@/components/AppNav";
import{Badge}from"@/components/ui/badge";
import{CommonsImage}from"@/components/CommonsImage";
import{ResourceBreadcrumb}from"@/components/ResourceSections";
import{TUTORIALS,imageQuery}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/tutoriels")({
head:()=>({
meta:[
{title:"Tutorielsd'astrophotographiepasàpas—CarteduCiel"},
{
name:"description",
content:
"Guidescompletsd'astrophoto:Luneausmartphone,règledes500,empilement,planétaire,bandeétroite.Matériel,étapes,réglagesexactsetpiègesàéviter.",
},
{property:"og:title",content:"Tutorielsd'astrophotographiepasàpas"},
{
property:"og:description",
content:
"Dupremierclichélunaireaucielprofondenbandeétroite:étapes,réglageseterreursàéviter.",
},
{property:"og:type",content:"article"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:TutorialsPage,
});

functionTutorialsPage(){
return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Tutorielsd'astrophotographie"
subtitle={`${TUTORIALS.length}guidescomplets:matérielrequis,étapesdansl'ordre,réglagesexactseterreursàéviter.`}
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Tutorielsd'astrophotographie"/>
<divclassName="space-y-5">
{TUTORIALS.map((t)=>(
<article
key={t.title}
className="groupoverflow-hiddenrounded-xlborderborder-border/60bg-card/40md:flex"
>
<CommonsImage
query={imageQuery(t.title,t.gear)}
alt={t.title}
className="h-44w-fullmd:h-automd:w-64md:shrink-0"
/>
<divclassName="p-5">
<divclassName="flexflex-wrapitems-centergap-2">
<Badgevariant="outline">{t.level}</Badge>
<spanclassName="flexitems-centergap-1text-xstext-muted-foreground">
<ClockclassName="size-3"/>{t.duration}
</span>
</div>
<h2className="mt-2text-basefont-semibold">{t.title}</h2>
<pclassName="mt-1text-xstext-muted-foreground">
Matériel:{t.gear}
</p>
<pclassName="mt-3text-smleading-relaxedtext-foreground/85">
{t.intro}
</p>
<olclassName="mt-4space-y-2">
{t.steps.map((s,i)=>(
<likey={i}className="flexgap-3text-smleading-relaxed">
<spanclassName="mt-0.5flexsize-5shrink-0items-centerjustify-centerrounded-fullbg-primary/15font-monotext-[11px]text-primary">
{i+1}
</span>
<spanclassName="text-muted-foreground">{s}</span>
</li>
))}
</ol>
<pclassName="mt-4rounded-lgborderborder-primary/25bg-primary/5px-3py-2font-monotext-xstext-primary">
{t.settings}
</p>
<ulclassName="mt-3space-y-1.5">
{t.pitfalls.map((p,i)=>(
<li
key={i}
className="flexgap-2text-xsleading-relaxedtext-muted-foreground"
>
<AlertTriangleclassName="mt-0.5size-3.5shrink-0text-amber-400/80"/>
<span>{p}</span>
</li>
))}
</ul>
</div>
</article>
))}
</div>
</div>
</main>
);
}
