import{createFileRoute}from"@tanstack/react-router";
import{PageHeader}from"@/components/AppNav";
import{LinkGrid,ResourceBreadcrumb}from"@/components/ResourceSections";
import{VIDEOS}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/videos")({
head:()=>({
meta:[
{title:"ChaînesYouTubed'astronomieetd'astrophotographie"},
{
name:"description",
content:
"UnesélectiondechaînesYouTubefrancophonesetanglophones:astrophotoducielprofond,testsdematériel,traitementd'imageetsessionsd'observation.",
},
{property:"og:title",content:"Chaînesvidéod'astronomie"},
{
property:"og:description",
content:"Lesmeilleureschaînespourapprendrel'astrophotoenvidéo.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:()=>(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Chaînesvidéo"
subtitle="LesmeilleureschaînesYouTubed'astronomieetd'astrophoto,enfrançaisetenanglais."
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Chaînesvidéo"/>
<LinkGriditems={VIDEOS}/>
</div>
</main>
),
});
