import{createFileRoute,Link}from"@tanstack/react-router";
import{ArrowRight}from"lucide-react";
import{PageHeader}from"@/components/AppNav";
import{CommonsImage}from"@/components/CommonsImage";
import{ResourceBreadcrumb}from"@/components/ResourceSections";
import{GEAR,imageQuery,slugify}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/materiel/")({
head:()=>({
meta:[
{title:"Matérield'astronomie—télescopes,montures,caméras,filtres"},
{
name:"description",
content:
"Cataloguedematérielastroparrayon:télescopes,montures,oculaires,caméras,filtres,jumelles,accessoiresdeterrainetlivres,avecconseilsetordresdeprix.",
},
{property:"og:title",content:"Matérield'astronomieparcatégorie"},
{
property:"og:description",
content:
"Huitrayonsdematérielavecconseilsd'achatetordresdeprixréels.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:GearMenu,
});

functionGearMenu(){
return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Matériel"
subtitle="Choisissezunrayon:chaquecatégoriedétaillelesmodèlestypes,leurusageetleurbudget."
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Matériel"/>
<divclassName="gridgap-5sm:grid-cols-2lg:grid-cols-3">
{GEAR.map((cat)=>(
<Link
key={cat.title}
to="/ressources/materiel/$slug"
params={{slug:slugify(cat.title)}}
className="groupoverflow-hiddenrounded-2xlborderborder-border/60bg-card/40transition-colorshover:border-primary/50hover:bg-accent/30"
>
<CommonsImage
query={imageQuery(cat.title)}
alt={cat.title}
className="h-40w-full"
/>
<divclassName="p-5">
<pclassName="font-monotext-[11px]uppercasetracking-widetext-primary">
{cat.items.length}références
</p>
<h2className="mt-1flexitems-centergap-1.5text-basefont-semibold">
{cat.title}
<ArrowRightclassName="size-4text-muted-foregroundtransition-transformgroup-hover:translate-x-0.5group-hover:text-primary"/>
</h2>
<pclassName="mt-1.5text-smleading-relaxedtext-muted-foreground">
{cat.blurb}
</p>
</div>
</Link>
))}
</div>
</div>
</main>
);
}
