import{createFileRoute}from"@tanstack/react-router";
import{PageHeader}from"@/components/AppNav";
import{LinkGrid,ResourceBreadcrumb}from"@/components/ResourceSections";
import{SOFTWARE}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/logiciels")({
head:()=>({
meta:[
{title:"Logicielsd'astrophotographie—capture,empilement,traitement"},
{
name:"description",
content:
"Siril,DeepSkyStacker,AutoStakkert!,PHD2,N.I.N.A.,GraXpert:leslogicielsgratuitsetpayantspourcapturer,empilerettraitervosimagesduciel.",
},
{property:"og:title",content:"Logicielsd'astrophotographie"},
{
property:"og:description",
content:"Lachaînelogiciellecomplète,delacaptureautraitementfinal.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:()=>(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Logiciels"
subtitle="Capture,empilement,traitementetautoguidage—l'essentielestgratuitetopensource."
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Logiciels"/>
<LinkGriditems={SOFTWARE}/>
</div>
</main>
),
});
