import{createFileRoute}from"@tanstack/react-router";
import{PageHeader}from"@/components/AppNav";
import{LinkGrid,ResourceBreadcrumb}from"@/components/ResourceSections";
import{PLANNING}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/planification")({
head:()=>({
meta:[
{title:"Planification&météoastro—seeing,pollution,éphémérides"},
{
name:"description",
content:
"Prévisionsdeseeingetdecouverturenuageuse,cartesdepollutionlumineuse,éphéméridesofficielles,passagesdel'ISSetplanificateursdecibles.",
},
{property:"og:title",content:"Planification&météopourl'observation"},
{
property:"og:description",
content:"Choisirlabonnenuit,lebonsiteetlabonnecible.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:()=>(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Planification&météo"
subtitle="Seeing,nuages,pollutionlumineuse,éphéméridesetplanificateursdecibles."
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Planification&météo"/>
<LinkGriditems={PLANNING}/>
</div>
</main>
),
});
