import{createFileRoute}from"@tanstack/react-router";
import{PageHeader}from"@/components/AppNav";
import{LinkGrid,ResourceBreadcrumb}from"@/components/ResourceSections";
import{BLOGS}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/communaute")({
head:()=>({
meta:[
{title:"Blogs,forumsetcommunautéastro—sitesderéférence"},
{
name:"description",
content:
"Astrosurf,Webastro,CloudyNights,Astrobin,Ciel&Espace,APOD:lesforums,blogsetgaleriesincontournablespourprogresserenastronomie.",
},
{property:"og:title",content:"Blogs,forumsetcommunautéastro"},
{
property:"og:description",
content:"Lessites,forumsetgaleriesderéférence,enfrançaisetenanglais.",
},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
}),
component:()=>(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeader
title="Blogs,forums&communauté"
subtitle="Lessitesderéférencefrancophonesetinternationaux,lesforumsactifsetlesgaleriesd'images."
/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Blogs,forums&communauté"/>
<LinkGriditems={BLOGS}/>
</div>
</main>
),
});
