import{createFileRoute,notFound}from"@tanstack/react-router";
import{ExternalLink}from"lucide-react";
import{PageHeader}from"@/components/AppNav";
import{CommonsImage}from"@/components/CommonsImage";
import{ResourceBreadcrumb}from"@/components/ResourceSections";
import{GEAR,imageQuery,slugify}from"@/data/resources";

exportconstRoute=createFileRoute("/ressources/materiel/$slug")({
loader:({params})=>{
constcat=GEAR.find((g)=>slugify(g.title)===params.slug);
if(!cat)thrownotFound();
return{title:cat.title,blurb:cat.blurb};
},
head:({loaderData})=>{
if(!loaderData)
return{
meta:[
{title:"Rayonintrouvable—Matérielastro"},
{name:"robots",content:"noindex"},
],
};
return{
meta:[
{title:`${loaderData.title}—matérield'astronomie`},
{name:"description",content:loaderData.blurb.slice(0,155)},
{property:"og:title",content:`${loaderData.title}—matérielastro`},
{property:"og:description",content:loaderData.blurb.slice(0,155)},
{property:"og:type",content:"website"},
{name:"twitter:card",content:"summary_large_image"},
],
};
},
component:GearCategoryPage,
});

functionGearCategoryPage(){
const{slug}=Route.useParams();
constcat=GEAR.find((g)=>slugify(g.title)===slug)!;

return(
<mainclassName="min-h-[100dvh]bg-backgroundpb-20">
<PageHeadertitle={cat.title}subtitle={cat.blurb}/>
<divclassName="mx-automax-w-6xlspace-y-6px-4pt-6">
<ResourceBreadcrumbcurrent="Matériel"/>
<divclassName="gridgap-4sm:grid-cols-2lg:grid-cols-3">
{cat.items.map((i)=>(
<a
key={i.url+i.name}
href={i.url}
target="_blank"
rel="noopenernoreferrer"
className="groupoverflow-hiddenrounded-xlborderborder-border/60bg-card/40transition-colorshover:border-primary/50hover:bg-accent/40"
>
<CommonsImage
query={imageQuery(i.name,cat.title,i.desc)}
alt={i.name}
className="h-32w-full"
/>
<divclassName="p-4">
<pclassName="flexitems-centergap-1.5font-medium">
{i.name}
<ExternalLinkclassName="size-3.5text-muted-foregroundtransition-colorsgroup-hover:text-primary"/>
</p>
<pclassName="mt-1text-smtext-muted-foreground">{i.desc}</p>
<pclassName="mt-2font-monotext-xstext-primary">{i.price}</p>
</div>
</a>
))}
</div>
</div>
</main>
);
}
