import{createFileRoute}from"@tanstack/react-router";
import{convertToModelMessages,streamText,stepCountIs,tool,typeUIMessage}from"ai";
import{z}from"zod";
import{createLovableAiGatewayProvider}from"@/lib/ai-gateway.server";
import{searchSky,tonightHighlights,computeVisibility,DEFAULT_FILTERS}from"@/lib/sky-search";
import{upcomingEvents}from"@/lib/events";
import{twilight,moonPosition,moonPhaseName,formatTime,cardinalName}from"@/lib/astro";

interfaceSkyContext{
latitude:number;
longitude:number;
locationName:string;
dateISO:string;
heading:number|null;
pitch:number|null;
}

functionrelativeDirection(targetAz:number,heading:number):string{
letdiff=((targetAz-heading+540)%360)-180;
constabs=Math.abs(diff);
if(abs<10)return"droitdevantvous";
constside=diff>0?"versladroite":"verslagauche";
if(abs>150)return"derrièrevous(faitesdemi-tour)";
return`${Math.round(abs)}°${side}`;
}

exportconstRoute=createFileRoute("/api/chat")({
server:{
handlers:{
POST:async({request})=>{
constbody=(awaitrequest.json())as{
messages?:UIMessage[];
context?:SkyContext;
};
constmessages=body.messages;
constctx=body.context;
if(!Array.isArray(messages)||!ctx){
returnnewResponse("Requêteinvalide",{status:400});
}
constapiKey=process.env["LOVABLE_API_KEY"];
if(!apiKey)returnnewResponse("CléIAmanquante",{status:500});

constdate=newDate(ctx.dateISO);
constpos={latitude:ctx.latitude,longitude:ctx.longitude};
constmoon=moonPosition(date);
consttw=twilight(date,pos);

constgateway=createLovableAiGatewayProvider(apiKey);

constresult=streamText({
model:gateway("google/gemini-3.6-flash"),
stopWhen:stepCountIs(50),
system:`Tues«Vega»,unguided'observationastronomiqueembarquédansl'applicationCarteduCiel.Turépondsenfrançais,avecchaleuretconcision(3à6phrasesmaximumsaufdemandeexplicite),commeunanimateurdeclubd'astronomiesurleterrain.

Contexted'observationactuel:
-Lieu:${ctx.locationName}(${ctx.latitude.toFixed(3)}°,${ctx.longitude.toFixed(3)}°)
-Heurelocale:${date.toLocaleString("fr-FR")}
-Lune:${moonPhaseName(moon.phase)},${Math.round(moon.illumination*100)}%illuminée
-CoucherduSoleil:${formatTime(tw.sunset)}·nuitnoire:${formatTime(tw.astronomicalDusk)}→${formatTime(tw.astronomicalDawn)}
-Orientationdutéléphone:${
ctx.heading===null
?"inconnue(laboussolen'estpasactivée)"
:`azimut${Math.round(ctx.heading)}°(${cardinalName(ctx.heading)})${
ctx.pitch!==null?`,inclinéà${Math.round(ctx.pitch)}°au-dessusdel'horizon`:""
}`
}

Règles:
-Utilisetoujourstesoutilspourtoutedonnéechiffrée(position,heure,visibilité,événements).N'inventejamaisunehauteurouuneheure.
-Quandontedemandeoùsetrouveunobjet,donneladirectioncardinale,lahauteurendegrés,etsilaboussoleestactive,l'indicationrelative(«tourne40°versladroite,puislèvelesyeuxà30°»).
-Adaptetesconseilsàl'instrument(œilnu,jumelles,télescope)etàlaLunedumoment.
-Siunobjetestsousl'horizon,dis-leetproposeuneheuredeleverouunealternativevisiblemaintenant.
-Réponseentextesimple,pasdetableauxlourds.Tupeuxutiliserdeslistescourtes.`,
messages:awaitconvertToModelMessages(messages),
tools:{
localiser_objet:tool({
description:
"Trouveunobjetcélesteparsonnomousonnumérodecatalogueetrenvoiesapositiondanslecielmaintenant.",
inputSchema:z.object({
nom:z.string().describe("Nomrecherché,ex:Saturne,M31,Vega,Orion"),
}),
execute:async({nom})=>{
constresults=searchSky(
{...DEFAULT_FILTERS,query:nom,sort:"magnitude"},
date,
pos,
);
if(!results.length)return{trouve:false,nom};
return{
trouve:true,
resultats:results.slice(0,3).map((r)=>{
constv=computeVisibility(r,date,pos);
return{
nom:r.name,
type:r.typeLabel,
constellation:r.constellation,
magnitude:r.mag,
hauteur_deg:Math.round(v.altitude),
azimut_deg:Math.round(v.azimuth),
direction:v.direction,
visible_maintenant:v.visible,
lever:formatTime(v.rise),
coucher:formatTime(v.set),
hauteur_max_nuit:Math.round(v.maxAltitude),
instrument:r.instrument,
orientation_relative:
ctx.heading===null
?null
:relativeDirection(v.azimuth,ctx.heading),
};
}),
};
},
}),
objets_visibles:tool({
description:
"Listelesmeilleursobjetsobservablesmaintenantdepuislapositiondel'utilisateur.",
inputSchema:z.object({
limite:z.number().describe("Nombred'objetssouhaités,entre3et15"),
}),
execute:async({limite})=>({
objets:tonightHighlights(date,pos,Math.min(15,Math.max(3,limite))).map(
(r)=>({
nom:r.name,
type:r.typeLabel,
magnitude:r.mag,
hauteur_deg:Math.round(r.vis.altitude),
direction:r.vis.direction,
instrument:r.instrument,
}),
),
}),
}),
evenements:tool({
description:
"Événementsastronomiquesàvenir:phasesdeLune,oppositions,rapprochements,pluiesd'étoilesfilantes.",
inputSchema:z.object({
jours:z.number().describe("Horizonenjours,entre7et120"),
}),
execute:async({jours})=>({
evenements:upcomingEvents(date,Math.min(120,Math.max(7,jours)))
.slice(0,12)
.map((e)=>({
date:e.date.toLocaleDateString("fr-FR",{
day:"numeric",
month:"long",
}),
titre:e.title,
detail:e.detail,
})),
}),
}),
ou_je_pointe:tool({
description:
"Indiquequelsobjetssetrouventdansladirectionoùl'utilisateurpointesontéléphone.",
inputSchema:z.object({
tolerance_deg:z.number().describe("Rayonderechercheendegrés,10à40"),
}),
execute:async({tolerance_deg})=>{
if(ctx.heading===null)
return{
erreur:
"Laboussolen'estpasactivée.Demandeàl'utilisateurd'appuyersurl'icôneboussole.",
};
consttol=Math.min(40,Math.max(10,tolerance_deg));
constall=searchSky(
{...DEFAULT_FILTERS,onlyVisible:true,maxMagnitude:7},
date,
pos,
);
constnear=all
.filter((r)=>{
constdAz=Math.abs(((r.vis.azimuth-ctx.heading!+540)%360)-180);
constdAlt=ctx.pitch===null?0:Math.abs(r.vis.altitude-ctx.pitch);
returndAz<tol&&dAlt<tol;
})
.slice(0,8);
return{
azimut_vise:Math.round(ctx.heading),
direction:cardinalName(ctx.heading),
objets:near.map((r)=>({
nom:r.name,
type:r.typeLabel,
magnitude:r.mag,
hauteur_deg:Math.round(r.vis.altitude),
})),
};
},
}),
},
});

returnresult.toUIMessageStreamResponse({originalMessages:messages});
},
},
},
});
