import{useState,useCallback,useEffect}from"react";
import{supabase}from"@/integrations/supabase/client";
import{useAuth}from"@/hooks/useAuth";
import{toast}from"sonner";

//——————————————————————————————————————————
//TypesexposésauUI
//——————————————————————————————————————————

exportinterfaceAstroObject{
id:string;
common_name:string|null;
type:string;
ra_deg:number;
dec_deg:number;
magnitude:number|null;
size_arcmin:number|null;
total_lights:number;
total_darks:number;
total_flats:number;
total_bias:number;
total_contributors:number;
total_exposure_hours:number;
master_image_url:string|null;
master_updated_at:string|null;
}

exportinterfaceAstroUploadDraft{
file:File;
object_id:string;
frame_type:"light"|"dark"|"flat"|"bias";
//Métadonnéesoptionnelles
telescope?:string;
camera?:string;
focal_length_mm?:number;
aperture_mm?:number;
exposure_s?:number;
gain?:number;
temperature_c?:number;
filter_name?:string;
binning?:number;
latitude?:number;
longitude?:number;
captured_at?:string;
}

exportinterfaceUploadProgress{
id:string;
filename:string;
progress:number;//0–100
status:"uploading"|"qualifying"|"qualified"|"rejected"|"error";
quality_score?:number;
rejection_reason?:string;
error?:string;
}

exportinterfaceAstroMaster{
id:string;
object_id:string;
image_url:string;
thumbnail_url:string|null;
lights_stacked:number;
total_exposure_hours:number;
contributors_count:number;
configurations_count:number;
countries_count:number;
final_snr:number|null;
final_fwhm:number|null;
generation:number;
notes:string|null;
is_current:boolean;
created_at:string;
}

exportinterfaceStackingJob{
id:string;
object_id:string;
lights_count:number;
total_exposure_hours:number;
contributors_count:number;
configurations_count:number;
stacking_method:string;
status:string;
result_image_url:string|null;
ai_pipeline_log:unknown;
started_at:string|null;
completed_at:string|null;
}

//——————————————————————————————————————————
//Hookprincipal
//——————————————————————————————————————————

exportfunctionuseAstroStack(){
const{user}=useAuth();
const[objects,setObjects]=useState<AstroObject[]>([]);
const[selectedObject,setSelectedObject]=useState<AstroObject|null>(null);
const[masters,setMasters]=useState<AstroMaster[]>([]);
const[recentJobs,setRecentJobs]=useState<StackingJob[]>([]);
const[userUploads,setUserUploads]=useState<UploadProgress[]>([]);
const[isLoadingObjects,setIsLoadingObjects]=useState(false);
const[isStacking,setIsStacking]=useState(false);
const[searchQuery,setSearchQuery]=useState("");

//Chargelalistedesobjets
constloadObjects=useCallback(async(query="")=>{
setIsLoadingObjects(true);
try{
letq=supabase
.from("astro_objects")
.select("*")
.order("total_lights",{ascending:false})
.limit(50);

if(query.trim()){
q=q.or(`id.ilike.%${query}%,common_name.ilike.%${query}%`);
}

const{data}=awaitq;
if(data)setObjects(dataasAstroObject[]);
}finally{
setIsLoadingObjects(false);
}
},[]);

//Chargelesmastersetjobspourunobjet
constloadObjectDetail=useCallback(async(objectId:string)=>{
const[mastersRes,jobsRes]=awaitPromise.all([
supabase
.from("astro_masters")
.select("*")
.eq("object_id",objectId)
.order("created_at",{ascending:false})
.limit(5),
supabase
.from("astro_stacking_jobs")
.select("id,object_id,lights_count,total_exposure_hours,contributors_count,configurations_count,stacking_method,status,result_image_url,ai_pipeline_log,started_at,completed_at")
.eq("object_id",objectId)
.order("created_at",{ascending:false})
.limit(3),
]);
if(mastersRes.data)setMasters(mastersRes.dataasAstroMaster[]);
if(jobsRes.data)setRecentJobs(jobsRes.dataasStackingJob[]);
},[]);

useEffect(()=>{
loadObjects(searchQuery);
},[loadObjects,searchQuery]);

//Uploadd'uneouplusieursframes
constuploadFrames=useCallback(
async(drafts:AstroUploadDraft[])=>{
if(!user){
toast.error("Connectez-vouspourcontribuer");
return;
}

for(constdraftofdrafts){
constuploadId=crypto.randomUUID();
constprogress:UploadProgress={
id:uploadId,
filename:draft.file.name,
progress:0,
status:"uploading",
};
setUserUploads((prev)=>[progress,...prev]);

try{
//UploadverslebucketSupabaseStorage
constext=draft.file.name.split(".").pop()??"fit";
conststoragePath=`${user.id}/${draft.object_id}/${draft.frame_type}/${Date.now()}_${draft.file.name}`;

const{error:storageErr}=awaitsupabase.storage
.from("astro-frames")
.upload(storagePath,draft.file,{upsert:false});

if(storageErr)thrownewError(storageErr.message);

setUserUploads((prev)=>
prev.map((u)=>u.id===uploadId?{...u,progress:60}:u)
);

const{data:publicData}=supabase.storage
.from("astro-frames")
.getPublicUrl(storagePath);

//Insèrel'enregistrementenbase
const{data:insertedUpload,error:insertErr}=awaitsupabase
.from("astro_uploads")
.insert({
user_id:user.id,
object_id:draft.object_id,
frame_type:draft.frame_type,
storage_path:storagePath,
file_url:publicData.publicUrl,
file_size_bytes:draft.file.size,
original_filename:draft.file.name,
telescope:draft.telescope??null,
camera:draft.camera??null,
focal_length_mm:draft.focal_length_mm??null,
aperture_mm:draft.aperture_mm??null,
exposure_s:draft.exposure_s??null,
gain:draft.gain??null,
temperature_c:draft.temperature_c??null,
filter_name:draft.filter_name??null,
binning:draft.binning??null,
latitude:draft.latitude??null,
longitude:draft.longitude??null,
captured_at:draft.captured_at??null,
status:"uploaded",
})
.select()
.single();

if(insertErr||!insertedUpload)thrownewError(insertErr?.message);

setUserUploads((prev)=>
prev.map((u)=>u.id===uploadId?{...u,progress:80,status:"qualifying"}:u)
);

//LancelaqualificationIAenarrière-plan
fetch("/api/astrostack/qualify",{
method:"POST",
headers:{"Content-Type":"application/json"},
body:JSON.stringify({upload_id:insertedUpload.id}),
})
.then((r)=>r.json())
.then((result)=>{
if(result.analysis){
setUserUploads((prev)=>
prev.map((u)=>
u.id===uploadId
?{
...u,
progress:100,
status:result.analysis.rejected?"rejected":"qualified",
quality_score:result.analysis.quality_score,
rejection_reason:result.analysis.rejection_reason,
}
:u
)
);
if(result.analysis.rejected){
toast.error(`Framerejetée:${result.analysis.rejection_reason}`);
}else{
toast.success(
`Framequalifiée—Score:${Math.round(result.analysis.quality_score*100)}%`
);
}
}
})
.catch(()=>{});

//Rafraîchitlesstatsdel'objet
if(selectedObject?.id===draft.object_id){
loadObjectDetail(draft.object_id);
}
loadObjects(searchQuery);
}catch(err){
setUserUploads((prev)=>
prev.map((u)=>
u.id===uploadId
?{...u,status:"error",error:String(err),progress:0}
:u
)
);
toast.error(`Erreurupload${draft.file.name}:${String(err)}`);
}
}
},
[user,selectedObject,loadObjectDetail,loadObjects,searchQuery]
);

//Lanceunstackingpourl'objetsélectionné
consttriggerStacking=useCallback(
async(objectId:string)=>{
setIsStacking(true);
try{
constres=awaitfetch("/api/astrostack/stack-trigger",{
method:"POST",
headers:{"Content-Type":"application/json"},
body:JSON.stringify({object_id:objectId,min_quality:0.4}),
});
constdata=awaitres.json();
if(!res.ok)thrownewError(data.error);

toast.success("??Stackinglancéavecsuccès!",{
description:`${data.job.lights_count}frames/${data.job.contributors_count}contributeurs`,
});

awaitloadObjectDetail(objectId);
awaitloadObjects(searchQuery);
}catch(err){
toast.error(`Erreurstacking:${String(err)}`);
}finally{
setIsStacking(false);
}
},
[loadObjectDetail,loadObjects,searchQuery]
);

constselectObject=useCallback(
(obj:AstroObject)=>{
setSelectedObject(obj);
loadObjectDetail(obj.id);
},
[loadObjectDetail]
);

return{
objects,
selectedObject,
masters,
recentJobs,
userUploads,
isLoadingObjects,
isStacking,
searchQuery,
setSearchQuery,
loadObjects,
selectObject,
uploadFrames,
triggerStacking,
refresh:()=>{
loadObjects(searchQuery);
if(selectedObject)loadObjectDetail(selectedObject.id);
},
};
}
