import{useState,useEffect,useCallback,useRef}from"react";
import{supabase}from"@/integrations/supabase/client";
import{useAuth}from"@/hooks/useAuth";
import{toast}from"sonner";

exporttypePhenomenonType=
|"meteor"
|"fireball"
|"comet"
|"supernova"
|"aurora"
|"satellite"
|"atmospheric"
|"unknown";

exportinterfaceCosmosObservation{
id:string;
user_id:string|null;
latitude:number;
longitude:number;
altitude_m:number|null;
azimuth:number|null;
elevation:number|null;
phenomenon_type:PhenomenonType;
description:string;
image_url:string|null;
duration_s:number|null;
magnitude:number|null;
ai_confidence:number|null;
status:string;
event_id:string|null;
observed_at:string;
}

exportinterfaceCosmosEvent{
id:string;
phenomenon_type:string;
title:string;
description:string|null;
observation_count:number;
confidence_score:number|null;
status:string;
event_at:string;
triangulation:unknown;
ai_analysis:unknown;
}

exportinterfaceObservationDraft{
phenomenon_type:PhenomenonType;
description:string;
azimuth?:number;
elevation?:number;
duration_s?:number;
magnitude?:number;
image_url?:string;
}

exportfunctionuseCosmosLive(){
const{user}=useAuth();
const[observations,setObservations]=useState<CosmosObservation[]>([]);
const[events,setEvents]=useState<CosmosEvent[]>([]);
const[userPosition,setUserPosition]=useState<GeolocationCoordinates|null>(null);
const[positionError,setPositionError]=useState<string|null>(null);
const[isSubmitting,setIsSubmitting]=useState(false);
const[isActive,setIsActive]=useState(false);
constchannelRef=useRef<ReturnType<typeofsupabase.channel>|null>(null);

//Géolocalisationcontinue
useEffect(()=>{
if(!isActive)return;
if(!navigator.geolocation){
setPositionError("Lagéolocalisationn'estpassupportéeparcenavigateur.");
return;
}
constwatcher=navigator.geolocation.watchPosition(
(pos)=>{
setUserPosition(pos.coords);
setPositionError(null);
},
(err)=>setPositionError(err.message),
{enableHighAccuracy:true,maximumAge:10000}
);
return()=>navigator.geolocation.clearWatch(watcher);
},[isActive]);

//Chargementinitialdesobservationsrécentesetdesévénements
constloadData=useCallback(async()=>{
const[obsRes,evtRes]=awaitPromise.all([
supabase
.from("cosmos_observations")
.select("*")
.gte("observed_at",newDate(Date.now()-2*60*60*1000).toISOString())
.order("observed_at",{ascending:false})
.limit(200),
supabase
.from("cosmos_events")
.select("id,phenomenon_type,title,description,observation_count,confidence_score,status,event_at,triangulation,ai_analysis")
.gte("event_at",newDate(Date.now()-24*60*60*1000).toISOString())
.neq("status","rejected")
.order("observation_count",{ascending:false})
.limit(50),
]);
if(obsRes.data)setObservations(obsRes.dataasCosmosObservation[]);
if(evtRes.data)setEvents(evtRes.dataasCosmosEvent[]);
},[]);

useEffect(()=>{
loadData();
},[loadData]);

//Realtime—écoutelesnouvellesobservationsetévénements
useEffect(()=>{
if(!isActive){
channelRef.current?.unsubscribe();
channelRef.current=null;
return;
}

constchannel=supabase
.channel("cosmos_live")
.on(
"postgres_changes",
{event:"INSERT",schema:"public",table:"cosmos_observations"},
(payload)=>{
constnewObs=payload.newasCosmosObservation;
setObservations((prev)=>[newObs,...prev].slice(0,500));
}
)
.on(
"postgres_changes",
{event:"INSERT",schema:"public",table:"cosmos_events"},
(payload)=>{
constnewEvt=payload.newasCosmosEvent;
setEvents((prev)=>[newEvt,...prev]);
toast.success(`??Nouvelévénementdétecté:${newEvt.title}`,{
description:`${newEvt.observation_count}observation(s)confirmée(s)`,
duration:8000,
});
}
)
.on(
"postgres_changes",
{event:"UPDATE",schema:"public",table:"cosmos_events"},
(payload)=>{
constupdated=payload.newasCosmosEvent;
setEvents((prev)=>
prev.map((e)=>(e.id===updated.id?{...e,...updated}:e))
);
}
)
.subscribe();

channelRef.current=channel;
return()=>{
channel.unsubscribe();
channelRef.current=null;
};
},[isActive]);

//Soumetuneobservation
constsubmitObservation=useCallback(
async(draft:ObservationDraft):Promise<boolean>=>{
if(!userPosition){
toast.error("PositionGPSrequise.ActivezCosmosLived'abord.");
returnfalse;
}
setIsSubmitting(true);
try{
constres=awaitfetch("/api/cosmos/report",{
method:"POST",
headers:{"Content-Type":"application/json"},
body:JSON.stringify({
user_id:user?.id??null,
latitude:userPosition.latitude,
longitude:userPosition.longitude,
altitude_m:userPosition.altitude??0,
...draft,
}),
});
if(!res.ok)thrownewError(awaitres.text());
toast.success("Observationsoumise!L'IAanalyselecluster...",{
description:"Sid'autresobservateursvoientlamêmechose,unévénementseradétecté.",
});
returntrue;
}catch(err){
toast.error("Erreurlorsdelasoumission",{
description:String(err),
});
returnfalse;
}finally{
setIsSubmitting(false);
}
},
[userPosition,user]
);

constactivate=useCallback(()=>setIsActive(true),[]);
constdeactivate=useCallback(()=>setIsActive(false),[]);

return{
observations,
events,
userPosition,
positionError,
isSubmitting,
isActive,
activate,
deactivate,
submitObservation,
refresh:loadData,
};
}
