import{useCallback,useState}from"react";
import{Button}from"@/components/ui/button";
import{Badge}from"@/components/ui/badge";
import{
Select,SelectContent,SelectItem,SelectTrigger,SelectValue,
}from"@/components/ui/select";
import{Input}from"@/components/ui/input";
import{Label}from"@/components/ui/label";
importtype{AstroUploadDraft}from"@/hooks/useAstroStack";

interfaceProps{
objectId:string;
onUpload:(drafts:AstroUploadDraft[])=>void;
disabled?:boolean;
}

constFRAME_TYPES=[
{value:"light",label:"LIGHT—posesurl'objet",color:"text-blue-400"},
{value:"dark",label:"DARK—mêmetemp/gain/durée",color:"text-red-400"},
{value:"flat",label:"FLAT—calibrationoptique",color:"text-yellow-400"},
{value:"bias",label:"BIAS—offsetcapteur",color:"text-purple-400"},
]asconst;

constACCEPTED=".fit,.fits,.fts,.cr2,.cr3,.nef,.arw,.dng,.tiff,.tif,.png,.xisf";

exportfunctionAstroUploadZone({objectId,onUpload,disabled}:Props){
const[frameType,setFrameType]=useState<"light"|"dark"|"flat"|"bias">("light");
const[isDragOver,setIsDragOver]=useState(false);
//Instrument
const[telescope,setTelescope]=useState("");
const[camera,setCamera]=useState("");
const[focalLength,setFocalLength]=useState("");
const[aperture,setAperture]=useState("");
const[exposure,setExposure]=useState("");
const[gain,setGain]=useState("");
const[temperature,setTemperature]=useState("");
const[filter,setFilter]=useState("");
const[binning,setBinning]=useState("1");

constbuildDraft=useCallback(
(file:File):AstroUploadDraft=>({
file,
object_id:objectId,
frame_type:frameType,
telescope:telescope||undefined,
camera:camera||undefined,
focal_length_mm:focalLength?Number(focalLength):undefined,
aperture_mm:aperture?Number(aperture):undefined,
exposure_s:exposure?Number(exposure):undefined,
gain:gain?Number(gain):undefined,
temperature_c:temperature?Number(temperature):undefined,
filter_name:filter||undefined,
binning:Number(binning),
}),
[objectId,frameType,telescope,camera,focalLength,aperture,exposure,gain,temperature,filter,binning]
);

consthandleFiles=useCallback(
(files:FileList|null)=>{
if(!files||files.length===0)return;
constdrafts=Array.from(files).map(buildDraft);
onUpload(drafts);
},
[buildDraft,onUpload]
);

return(
<divclassName="space-y-4">
{/*Typedeframe*/}
<divclassName="space-y-1.5">
<Label>Typedeframe*</Label>
<divclassName="gridgrid-cols-2gap-2">
{FRAME_TYPES.map((t)=>(
<button
key={t.value}
type="button"
onClick={()=>setFrameType(t.value)}
className={`rounded-lgborderpx-3py-2text-lefttext-xstransition-colors${
frameType===t.value
?"border-primarybg-primary/10"
:"border-borderbg-cardhover:border-primary/50"
}`}
>
<spanclassName={`font-monofont-bold${t.color}`}>
{t.value.toUpperCase()}
</span>
<br/>
<spanclassName="text-[10px]text-muted-foreground">
{t.label.split("—")[1]}
</span>
</button>
))}
</div>
</div>

{/*Zonededrop*/}
<div
onDragOver={(e)=>{e.preventDefault();setIsDragOver(true);}}
onDragLeave={()=>setIsDragOver(false)}
onDrop={(e)=>{e.preventDefault();setIsDragOver(false);handleFiles(e.dataTransfer.files);}}
className={`relativeflexcursor-pointerflex-colitems-centerjustify-centerrounded-xlborder-2border-dashedp-8text-centertransition-all${
isDragOver
?"border-primarybg-primary/10"
:"border-borderbg-muted/20hover:border-primary/50"
}${disabled?"opacity-50cursor-not-allowed":""}`}
onClick={()=>!disabled&&document.getElementById("astro-file-input")?.click()}
>
<input
id="astro-file-input"
type="file"
multiple
accept={ACCEPTED}
className="hidden"
disabled={disabled}
onChange={(e)=>handleFiles(e.target.files)}
/>
<divclassName="text-3xlmb-3">??</div>
<pclassName="text-smfont-medium">
Déposezvosframesici
</p>
<pclassName="mt-1text-xstext-muted-foreground">
FITS,RAW(CR2,NEF,ARW),TIFF,XISF
</p>
<Badgevariant="secondary"className="mt-3text-[10px]">
{frameType.toUpperCase()}pour{objectId}
</Badge>
</div>

{/*Métadonnéesinstrument(collapsibles)*/}
<detailsclassName="group">
<summaryclassName="cursor-pointertext-xstext-muted-foregroundhover:text-foregroundselect-none">
+Métadonnéesinstrument(optionnel—améliorelacompatibilitédestacking)
</summary>
<divclassName="mt-3gridgrid-cols-2gap-2">
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Télescope</Label>
<Inputplaceholder="Ex:SW200/1000"value={telescope}onChange={e=>setTelescope(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Caméra</Label>
<Inputplaceholder="Ex:ASI294MC"value={camera}onChange={e=>setCamera(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Focale(mm)</Label>
<Inputtype="number"placeholder="1000"value={focalLength}onChange={e=>setFocalLength(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Ouverture(mm)</Label>
<Inputtype="number"placeholder="200"value={aperture}onChange={e=>setAperture(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Pose(s)</Label>
<Inputtype="number"placeholder="300"value={exposure}onChange={e=>setExposure(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Gain</Label>
<Inputtype="number"placeholder="120"value={gain}onChange={e=>setGain(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Temp.capteur(°C)</Label>
<Inputtype="number"placeholder="-10"value={temperature}onChange={e=>setTemperature(e.target.value)}className="h-8text-xs"/>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Filtre</Label>
<Selectvalue={filter}onValueChange={setFilter}>
<SelectTriggerclassName="h-8text-xs"><SelectValueplaceholder="Aucun/L"/></SelectTrigger>
<SelectContent>
{["L","R","G","B","Ha","OIII","SII","Hbeta","UV","IR"].map(f=>(
<SelectItemkey={f}value={f}>{f}</SelectItem>
))}
</SelectContent>
</Select>
</div>
<divclassName="space-y-1">
<LabelclassName="text-[11px]">Binning</Label>
<Selectvalue={binning}onValueChange={setBinning}>
<SelectTriggerclassName="h-8text-xs"><SelectValue/></SelectTrigger>
<SelectContent>
{["1","2","3","4"].map(b=><SelectItemkey={b}value={b}>{b}×{b}</SelectItem>)}
</SelectContent>
</Select>
</div>
</div>
</details>
</div>
);
}
