importtype{AstroObject}from"@/hooks/useAstroStack";
import{Input}from"@/components/ui/input";
import{Badge}from"@/components/ui/badge";
import{cn}from"@/lib/utils";

interfaceProps{
objects:AstroObject[];
selected:AstroObject|null;
onSelect:(o:AstroObject)=>void;
searchQuery:string;
onSearch:(q:string)=>void;
isLoading:boolean;
}

constTYPE_ICONS:Record<string,string>={
galaxy:"??",
nebula:"???",
cluster_open:"?",
cluster_globular:"?",
planetary_nebula:"??",
supernova_remnant:"??",
double_star:"?",
other:"??",
};

functionshortExposure(h:number){
if(h<0.1)return"";
if(h<1)return`${Math.round(h*60)}min`;
return`${h.toFixed(0)}h`;
}

exportfunctionAstroObjectList({objects,selected,onSelect,searchQuery,onSearch,isLoading}:Props){
return(
<divclassName="flexflex-colh-full">
<divclassName="p-3border-bborder-border">
<Input
placeholder="RechercherM31,NGC224,Andromède…"
value={searchQuery}
onChange={(e)=>onSearch(e.target.value)}
className="h-8text-xs"
/>
</div>

<divclassName="flex-1overflow-y-auto">
{isLoading?(
<divclassName="flexitems-centerjustify-centerpy-12text-smtext-muted-foreground">
Chargement…
</div>
):objects.length===0?(
<divclassName="flexitems-centerjustify-centerpy-12text-smtext-muted-foreground">
Aucunobjettrouvé
</div>
):(
objects.map((obj)=>(
<button
key={obj.id}
type="button"
onClick={()=>onSelect(obj)}
className={cn(
"w-fullflexitems-centergap-3px-3py-2.5text-lefttext-xstransition-colorsborder-bborder-border/50",
selected?.id===obj.id
?"bg-primary/10border-l-2border-l-primary"
:"hover:bg-muted/50"
)}
>
<spanclassName="text-xlshrink-0">{TYPE_ICONS[obj.type]??"??"}</span>
<divclassName="flex-1min-w-0">
<divclassName="flexitems-centergap-1.5">
<spanclassName="font-bold">{obj.id}</span>
{obj.master_image_url&&(
<spanclassName="text-[9px]text-green-400">?master</span>
)}
</div>
{obj.common_name&&(
<pclassName="text-[11px]text-muted-foregroundtruncate">{obj.common_name}</p>
)}
<divclassName="flexitems-centergap-2mt-0.5">
{obj.total_lights>0&&(
<spanclassName="text-[10px]text-blue-400">
{obj.total_lights.toLocaleString()}L
</span>
)}
{obj.total_contributors>0&&(
<spanclassName="text-[10px]text-muted-foreground">
{obj.total_contributors}contrib.
</span>
)}
{obj.total_exposure_hours>0&&(
<spanclassName="text-[10px]text-muted-foreground">
{shortExposure(obj.total_exposure_hours)}
</span>
)}
</div>
</div>
{obj.total_lights===0&&(
<Badgevariant="outline"className="text-[9px]shrink-0">vide</Badge>
)}
</button>
))
)}
</div>
</div>
);
}
