importtype{AstroObject,AstroMaster,StackingJob}from"@/hooks/useAstroStack";
import{Button}from"@/components/ui/button";
import{Badge}from"@/components/ui/badge";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
import{Progress}from"@/components/ui/progress";

interfaceProps{
object:AstroObject;
masters:AstroMaster[];
recentJobs:StackingJob[];
onTriggerStack:()=>void;
isStacking:boolean;
}

constTYPE_ICONS:Record<string,string>={
galaxy:"??",
nebula:"???",
cluster_open:"?",
cluster_globular:"?",
planetary_nebula:"??",
supernova_remnant:"??",
double_star:"?",
other:"??",
};

functionformatHours(h:number){
if(h<1)return`${Math.round(h*60)}min`;
return`${h.toFixed(1)}h`;
}

functionPipelineStep({name,status,result}:{name:string;status:string;result?:string}){
consticon=status==="done"?"?":status==="running"?"?":status==="failed"?"?":"·";
constcolor=
status==="done"?"text-green-400":
status==="running"?"text-blue-400animate-pulse":
status==="failed"?"text-red-400":"text-muted-foreground";
return(
<divclassName="flexitems-centerjustify-betweenpy-0.5text-[11px]">
<spanclassName="flexitems-centergap-1.5">
<spanclassName={`font-monofont-bold${color}`}>{icon}</span>
<spanclassName={status==="done"?"text-foreground":"text-muted-foreground"}>{name}</span>
</span>
{result&&<spanclassName="text-[10px]text-muted-foregroundml-2">{result}</span>}
</div>
);
}

exportfunctionAstroObjectMaster({object,masters,recentJobs,onTriggerStack,isStacking}:Props){
constcurrentMaster=masters.find((m)=>m.is_current);
constlatestJob=recentJobs[0];
constpipelineLog=latestJob?.ai_pipeline_logas{steps?:Array<{name:string;status:string;result?:string}>}|null;
consthasEnoughData=object.total_lights>=3;

//Indicateursdecomplétude
constlightsOk=object.total_lights>=50;
constdarksOk=object.total_darks>=30;
constflatsOk=object.total_flats>=20;
constbiasOk=object.total_bias>=10;
constcompleteness=[lightsOk,darksOk,flatsOk,biasOk].filter(Boolean).length/4;

return(
<divclassName="space-y-4">
{/*Headerobjet*/}
<divclassName="flexitems-startgap-3rounded-xlborderborder-borderbg-card/50p-4">
<spanclassName="text-3xl">{TYPE_ICONS[object.type]??"??"}</span>
<divclassName="flex-1min-w-0">
<divclassName="flexitems-centergap-2flex-wrap">
<h2className="text-lgfont-bold">{object.id}</h2>
{object.common_name&&(
<spanclassName="text-smtext-muted-foreground">—{object.common_name}</span>
)}
<Badgevariant="outline"className="text-[10px]">{object.type.replace("_","")}</Badge>
</div>
<pclassName="mt-0.5text-xstext-muted-foregroundfont-mono">
?{object.ra_deg.toFixed(4)}°?{object.dec_deg.toFixed(4)}°
{object.magnitude&&`·mag${object.magnitude}`}
{object.size_arcmin&&`·${object.size_arcmin}?`}
</p>
</div>
</div>

{/*Statsmondiales*/}
<divclassName="gridgrid-cols-2gap-3sm:grid-cols-4">
{[
{label:"LIGHTS",value:object.total_lights.toLocaleString(),ok:lightsOk,color:"text-blue-400"},
{label:"DARKS",value:object.total_darks.toLocaleString(),ok:darksOk,color:"text-red-400"},
{label:"FLATS",value:object.total_flats.toLocaleString(),ok:flatsOk,color:"text-yellow-400"},
{label:"BIAS",value:object.total_bias.toLocaleString(),ok:biasOk,color:"text-purple-400"},
].map((s)=>(
<Cardkey={s.label}className={`bg-card/50border${s.ok?"border-green-500/20":"border-border"}`}>
<CardContentclassName="p-3text-center">
<pclassName={`text-xlfont-boldtabular-nums${s.color}`}>{s.value}</p>
<pclassName="text-[10px]font-monotext-muted-foreground">{s.label}</p>
{!s.ok&&<pclassName="text-[10px]text-yellow-500mt-0.5">?manquant</p>}
</CardContent>
</Card>
))}
</div>

{/*Métriquesglobales*/}
<divclassName="gridgrid-cols-3gap-3text-centertext-xs">
<divclassName="rounded-lgborderborder-borderbg-card/30p-3">
<pclassName="text-lgfont-bold">{object.total_contributors.toLocaleString()}</p>
<pclassName="text-muted-foreground">contributeurs</p>
</div>
<divclassName="rounded-lgborderborder-borderbg-card/30p-3">
<pclassName="text-lgfont-bold">{formatHours(object.total_exposure_hours)}</p>
<pclassName="text-muted-foreground">deposetotale</p>
</div>
<divclassName="rounded-lgborderborder-borderbg-card/30p-3">
<pclassName="text-lgfont-bold">{Math.round(completeness*100)}%</p>
<pclassName="text-muted-foreground">complétude</p>
<Progressvalue={completeness*100}className="mt-1h-1"/>
</div>
</div>

{/*Masteractuel*/}
{currentMaster?(
<CardclassName="bg-card/50">
<CardHeaderclassName="pb-2pt-3px-4">
<divclassName="flexitems-centerjustify-between">
<CardTitleclassName="text-sm">
??Masteractuel—Génération{currentMaster.generation}
</CardTitle>
<Badgevariant="secondary"className="text-[10px]">
SNR×{Math.sqrt(currentMaster.lights_stacked).toFixed(1)}
</Badge>
</div>
</CardHeader>
<CardContentclassName="px-4pb-4space-y-3">
<img
src={currentMaster.image_url}
alt={`Master${object.id}`}
className="w-fullrounded-lgobject-coverbg-muted"
style={{maxHeight:200}}
/>
<divclassName="gridgrid-cols-3gap-2text-xstext-center">
<div>
<pclassName="font-semibold">{currentMaster.lights_stacked.toLocaleString()}</p>
<pclassName="text-muted-foreground">framesstackées</p>
</div>
<div>
<pclassName="font-semibold">{formatHours(currentMaster.total_exposure_hours)}</p>
<pclassName="text-muted-foreground">posetotale</p>
</div>
<div>
<pclassName="font-semibold">{currentMaster.contributors_count}</p>
<pclassName="text-muted-foreground">contributeurs</p>
</div>
</div>
{currentMaster.notes&&(
<pclassName="text-[11px]text-muted-foregrounditalic">{currentMaster.notes}</p>
)}
</CardContent>
</Card>
):(
<divclassName="rounded-xlborderborder-dashedborder-borderp-8text-center">
<pclassName="text-4xlmb-3">??</p>
<pclassName="text-smfont-medium">Aucunmasterdisponible</p>
<pclassName="text-xstext-muted-foregroundmt-1">
{hasEnoughData
?"Cliquezsur«Lancerlestacking»pourgénérerlepremiermaster."
:`Ilfautauminimum3lightspourlancerlestacking(actuellement${object.total_lights}).`}
</p>
</div>
)}

{/*Boutonstacking*/}
<Button
className="w-full"
onClick={onTriggerStack}
disabled={!hasEnoughData||isStacking}
variant={currentMaster?"outline":"default"}
>
{isStacking
?"??Stackingencours..."
:currentMaster
?"??Recalculerlemaster"
:"??Lancerlestackingmondial"}
</Button>

{/*Pipelinelog*/}
{pipelineLog?.steps&&pipelineLog.steps.length>0&&(
<CardclassName="bg-card/30border-dashed">
<CardHeaderclassName="pb-2pt-3px-4">
<CardTitleclassName="text-xsfont-mono">Pipelinelog—dernierjob</CardTitle>
</CardHeader>
<CardContentclassName="px-4pb-3">
{pipelineLog.steps.map((step,i)=>(
<PipelineStepkey={i}name={step.name}status={step.status}result={step.result}/>
))}
</CardContent>
</Card>
)}
</div>
);
}
