import{useQuery}from"@tanstack/react-query";
import{Sparkles}from"lucide-react";
import{cn}from"@/lib/utils";

asyncfunctionfetchThumb(query:string):Promise<string|null>{
consturl=
"https://commons.wikimedia.org/w/api.php?"+
newURLSearchParams({
action:"query",
generator:"search",
gsrsearch:`filetype:bitmap${query}`,
gsrnamespace:"6",
gsrlimit:"5",
prop:"imageinfo",
iiprop:"url",
iiurlwidth:"640",
format:"json",
origin:"*",
}).toString();
constres=awaitfetch(url);
if(!res.ok)thrownewError("imageindisponible");
constdata=(awaitres.json())as{query?:{pages?:Record<string,any>}};
constpages=Object.values(data.query?.pages??{}).sort(
(a:any,b:any)=>(a.index??0)-(b.index??0),
);
for(constpofpagesasany[]){
constt=p.imageinfo?.[0]?.thumburl;
if(t)returntasstring;
}
returnnull;
}

/**VignetteillustrativeissuedeWikimediaCommons,avecrepligraphique.*/
exportfunctionCommonsImage({
query,
alt,
className,
}:{
query:string;
alt:string;
className?:string;
}){
const{data,isLoading}=useQuery({
queryKey:["commons-thumb",query],
queryFn:()=>fetchThumb(query),
staleTime:1000*60*60*24,
retry:1,
});

return(
<div
className={cn(
"relativeoverflow-hiddenbg-gradient-to-brfrom-primary/15via-muted/40to-background",
className,
)}
>
{data?(
<img
src={data}
alt={alt}
loading="lazy"
className="size-fullobject-covertransition-transformduration-500group-hover:scale-105"
/>
):(
<divclassName="flexsize-fullitems-centerjustify-center">
{!isLoading&&<SparklesclassName="size-5text-primary/50"/>}
</div>
)}
<divclassName="pointer-events-noneabsoluteinset-0bg-gradient-to-tfrom-background/80via-background/10to-transparent"/>
</div>
);
}
