import{useQuery}from"@tanstack/react-query";
import{Loader2,ImageOff,Telescope,FlaskConical}from"lucide-react";
import{supabase}from"@/integrations/supabase/client";
import{Badge}from"@/components/ui/badge";
import{Card,CardContent}from"@/components/ui/card";

interfaceGalleryImage{
id:string;
image_url:string;
object_name:string;
uploaded_at:string;
vision_analysis:{
astronomicalDetails?:{
objectType?:string;
};
}|null;
}

interfaceComparison{
id:string;
object_id:string;
discoveries:Array<{description:string;confidence:number;type:string}>|null;
created_at:string;
}

functiontimeAgo(dateStr:string):string{
constdiff=Date.now()-newDate(dateStr).getTime();
constm=Math.floor(diff/60000);
if(m<60)return`ilya${m}min`;
consth=Math.floor(m/60);
if(h<24)return`ilya${h}h`;
return`ilya${Math.floor(h/24)}j`;
}

exportfunctionCommunityGallery({objectId}:{objectId?:string}){
const{data:images,isLoading}=useQuery({
queryKey:["community-gallery",objectId],
queryFn:async()=>{
letquery=supabase
.from("user_images")
.select("id,image_url,object_name,uploaded_at,vision_analysis")
.eq("is_ai_generated",false)
.order("uploaded_at",{ascending:false})
.limit(24);

if(objectId)query=query.eq("object_id",objectId);

const{data,error}=awaitquery;
if(error)throwerror;
returndataasGalleryImage[];
},
staleTime:60_000,
});

const{data:comparisons}=useQuery({
queryKey:["image-comparisons",objectId],
queryFn:async()=>{
letquery=supabase
.from("image_comparisons")
.select("id,object_id,discoveries,created_at")
.order("created_at",{ascending:false})
.limit(5);

if(objectId)query=query.eq("object_id",objectId);

const{data,error}=awaitquery;
if(error)throwerror;
returndataasComparison[];
},
staleTime:120_000,
});

constdiscoveries=
comparisons
?.flatMap((c:Comparison)=>c.discoveries??[])
.filter((d:{description:string;confidence:number;type:string})=>d.confidence>0.5)
.slice(0,3)??[];

if(isLoading){
return(
<divclassName="flexitems-centerjustify-centerpy-16">
<Loader2className="size-6animate-spintext-muted-foreground"/>
</div>
);
}

return(
<divclassName="space-y-6">
{discoveries.length>0&&(
<CardclassName="border-primary/30bg-primary/5">
<CardContentclassName="pt-4">
<pclassName="mb-3flexitems-centergap-2font-semiboldtext-primary">
<FlaskConicalclassName="size-4"/>
Dcouvertescollaborativesrcentes
</p>
<ulclassName="space-y-2">
{discoveries.map((d:{description:string;confidence:number},i:number)=>(
<likey={i}className="flexitems-startgap-2text-sm">
<Badgevariant="secondary"className="mt-0.5shrink-0text-xs">
{Math.round(d.confidence*100)}%
</Badge>
<span>{d.description}</span>
</li>
))}
</ul>
</CardContent>
</Card>
)}

{!images||images.length===0?(
<divclassName="flexflex-colitems-centerjustify-centergap-3py-16text-muted-foreground">
<ImageOffclassName="size-10"/>
<p>Aucuneimagepourlemoment.Soyezlepremierpartager!</p>
</div>
):(
<divclassName="gridgrid-cols-2gap-3sm:grid-cols-3md:grid-cols-4">
{images.map((img:GalleryImage)=>(
<div
key={img.id}
className="grouprelativeaspect-squareoverflow-hiddenrounded-lgbg-muted"
>
<img
src={img.image_url}
alt={img.object_name}
className="h-fullw-fullobject-covertransition-transformduration-300group-hover:scale-105"
loading="lazy"
/>
<divclassName="absoluteinset-0flexflex-coljustify-endbg-gradient-to-tfrom-black/70to-transparentp-2opacity-0transition-opacitygroup-hover:opacity-100">
<pclassName="truncatetext-xsfont-mediumtext-white">{img.object_name}</p>
<divclassName="mt-1flexitems-centergap-1.5">
<TelescopeclassName="size-3text-white/80"/>
<pclassName="text-[10px]text-white/80">{timeAgo(img.uploaded_at)}</p>
</div>
{img.vision_analysis?.astronomicalDetails?.objectType&&(
<Badgevariant="secondary"className="mt-1w-fittext-[10px]">
{img.vision_analysis.astronomicalDetails.objectType}
</Badge>
)}
</div>
</div>
))}
</div>
)}
</div>
);
}
