import{useMemo}from"react";
import{Badge}from"@/components/ui/badge";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
importtype{CosmosEvent}from"@/hooks/useCosmosLive";

interfaceTriangulationData{
estimated_latitude?:number;
estimated_longitude?:number;
estimated_altitude_km?:number;
estimated_speed_km_s?:number|null;
error_margin_km?:number;
confidence?:number;
method?:string;
trajectory?:Array<{lat:number;lon:number;alt_km:number}>;
}

interfaceProps{
events:CosmosEvent[];
}

constSIG_COLORS:Record<string,string>={
exceptional:"text-red-400bg-red-500/10border-red-500/30",
high:"text-orange-400bg-orange-500/10border-orange-500/30",
medium:"text-yellow-400bg-yellow-500/10border-yellow-500/30",
low:"text-muted-foregroundbg-muted/30",
};

functiongetSignificance(evt:CosmosEvent):string{
constanalysis=evt.ai_analysisasRecord<string,unknown>|null;
return(analysis?.scientific_significanceasstring)??"low";
}

exportfunctionCosmosTriangulationPanel({events}:Props){
consttriangulated=useMemo(
()=>
events.filter((e)=>e.triangulation!=null).slice(0,5),
[events]
);

if(triangulated.length===0){
return(
<divclassName="rounded-lgborderborder-dashedborder-borderp-8text-center">
<pclassName="text-smtext-muted-foreground">
Aucunetriangulationdisponiblepourlemoment.
</p>
<pclassName="mt-1text-xstext-muted-foreground">
3observateursouplusdepuisdespositionsdifférentessontnécessaires.
</p>
</div>
);
}

return(
<divclassName="space-y-3">
{triangulated.map((evt)=>{
consttri=evt.triangulationasTriangulationData;
constsig=getSignificance(evt);

return(
<Card
key={evt.id}
className={`border${SIG_COLORS[sig]??""}backdrop-blur-sm`}
>
<CardHeaderclassName="pb-2pt-3px-4">
<divclassName="flexitems-startjustify-betweengap-2">
<CardTitleclassName="text-smfont-semibold">
{evt.title}
</CardTitle>
<Badge
variant="outline"
className={`shrink-0text-[10px]border${SIG_COLORS[sig]??""}`}
>
{sig==="exceptional"
?"??Exceptionnel"
:sig==="high"
?"?Élevé"
:sig==="medium"
?"??Moyen"
:"•Faible"}
</Badge>
</div>
</CardHeader>
<CardContentclassName="space-y-3px-4pb-4">
{/*Positiontriangulée*/}
{tri.estimated_latitude&&tri.estimated_longitude&&(
<divclassName="gridgrid-cols-3gap-2rounded-mdbg-muted/30p-2text-xs">
<divclassName="text-center">
<pclassName="text-[10px]text-muted-foreground">Latitude</p>
<pclassName="font-monofont-medium">
{tri.estimated_latitude.toFixed(3)}°
</p>
</div>
<divclassName="text-center">
<pclassName="text-[10px]text-muted-foreground">Longitude</p>
<pclassName="font-monofont-medium">
{tri.estimated_longitude.toFixed(3)}°
</p>
</div>
<divclassName="text-center">
<pclassName="text-[10px]text-muted-foreground">Altitude</p>
<pclassName="font-monofont-medium">
{tri.estimated_altitude_km
?`${Math.round(tri.estimated_altitude_km)}km`
:"—"}
</p>
</div>
</div>
)}

{/*Trajectoire*/}
{tri.trajectory&&tri.trajectory.length>0&&(
<divclassName="text-xs">
<pclassName="mb-1text-[10px]text-muted-foreground">
Trajectoireestimée({tri.trajectory.length}points)
</p>
<divclassName="flexitems-centergap-1.5overflow-x-auto">
{tri.trajectory.map((pt,i)=>(
<span
key={i}
className="shrink-0roundedbg-muted/50px-1.5py-0.5font-monotext-[10px]"
>
{pt.lat.toFixed(1)},{pt.lon.toFixed(1)}@{Math.round(pt.alt_km)}km
</span>
))}
</div>
</div>
)}

{/*Métadonnées*/}
<divclassName="flexflex-wrapgap-x-4gap-y-1text-[10px]text-muted-foreground">
{tri.error_margin_km&&(
<span>±{Math.round(tri.error_margin_km)}kmd'erreur</span>
)}
{tri.confidence&&(
<span>Confiance{Math.round(tri.confidence*100)}%</span>
)}
{tri.method&&(
<spanclassName="capitalize">Méthode:{tri.method}</span>
)}
<span>{evt.observation_count}observation(s)</span>
</div>

{/*RecommandationIA*/}
{(evt.ai_analysisasRecord<string,unknown>)?.recommended_action&&(
<pclassName="rounded-mdborderborder-primary/20bg-primary/5px-3py-2text-xsitalic">
??{""}
{
(evt.ai_analysisasRecord<string,string>)
.recommended_action
}
</p>
)}
</CardContent>
</Card>
);
})}
</div>
);
}
