import{useState}from"react";
import{Button}from"@/components/ui/button";
import{Textarea}from"@/components/ui/textarea";
import{Label}from"@/components/ui/label";
import{Input}from"@/components/ui/input";
import{
Select,
SelectContent,
SelectItem,
SelectTrigger,
SelectValue,
}from"@/components/ui/select";
importtype{ObservationDraft,PhenomenonType}from"@/hooks/useCosmosLive";

constPHENOMENA:Array<{value:PhenomenonType;label:string;hint:string}>=[
{value:"meteor",label:"??Météore",hint:"Trainéelumineuserapide"},
{value:"fireball",label:"??Bolide",hint:"Météoretrèsbrillant,mag<-4"},
{value:"aurora",label:"??Auroreboréale/australe",hint:"Lumièrescoloréesdansleciel"},
{value:"comet",label:"??Comète",hint:"Objetavecqueuevisible"},
{value:"supernova",label:"??Supernovapotentielle",hint:"Nouvelleétoiletrèsbrillante"},
{value:"satellite",label:"??Satellite/trainStarlink",hint:"Pointlumineuxsedéplaçant"},
{value:"atmospheric",label:"??Phénomèneatmosphérique",hint:"Halo,arc,nacrés,etc."},
{value:"unknown",label:"?Inconnu",hint:"Phénomènenonidentifié"},
];

interfaceProps{
onSubmit:(draft:ObservationDraft)=>Promise<boolean>;
isSubmitting:boolean;
disabled?:boolean;
}

exportfunctionCosmosReportForm({onSubmit,isSubmitting,disabled}:Props){
const[phenomenon,setPhenomenon]=useState<PhenomenonType>("meteor");
const[description,setDescription]=useState("");
const[azimuth,setAzimuth]=useState("");
const[elevation,setElevation]=useState("");
const[duration,setDuration]=useState("");
const[magnitude,setMagnitude]=useState("");

consthandleSubmit=async(e:React.FormEvent)=>{
e.preventDefault();
if(!description.trim())return;

constdraft:ObservationDraft={
phenomenon_type:phenomenon,
description:description.trim(),
azimuth:azimuth?Number(azimuth):undefined,
elevation:elevation?Number(elevation):undefined,
duration_s:duration?Number(duration):undefined,
magnitude:magnitude?Number(magnitude):undefined,
};

constok=awaitonSubmit(draft);
if(ok){
setDescription("");
setAzimuth("");
setElevation("");
setDuration("");
setMagnitude("");
}
};

constselectedHint=PHENOMENA.find((p)=>p.value===phenomenon)?.hint;

return(
<formonSubmit={handleSubmit}className="space-y-4">
<divclassName="space-y-1.5">
<LabelhtmlFor="phenomenon">Phénomèneobservé</Label>
<Select
value={phenomenon}
onValueChange={(v)=>setPhenomenon(vasPhenomenonType)}
disabled={disabled}
>
<SelectTriggerid="phenomenon">
<SelectValue/>
</SelectTrigger>
<SelectContent>
{PHENOMENA.map((p)=>(
<SelectItemkey={p.value}value={p.value}>
{p.label}
</SelectItem>
))}
</SelectContent>
</Select>
{selectedHint&&(
<pclassName="text-[11px]text-muted-foreground">{selectedHint}</p>
)}
</div>

<divclassName="space-y-1.5">
<LabelhtmlFor="description">Description*</Label>
<Textarea
id="description"
placeholder="Décrivezprécisémentcequevousobservez:direction,couleur,durée,intensité..."
value={description}
onChange={(e)=>setDescription(e.target.value)}
rows={3}
disabled={disabled}
required
/>
</div>

<divclassName="gridgrid-cols-2gap-3">
<divclassName="space-y-1.5">
<LabelhtmlFor="azimuth">Azimut(°)</Label>
<Input
id="azimuth"
type="number"
min={0}
max={360}
placeholder="0–360"
value={azimuth}
onChange={(e)=>setAzimuth(e.target.value)}
disabled={disabled}
/>
</div>
<divclassName="space-y-1.5">
<LabelhtmlFor="elevation">Élévation(°)</Label>
<Input
id="elevation"
type="number"
min={0}
max={90}
placeholder="0–90"
value={elevation}
onChange={(e)=>setElevation(e.target.value)}
disabled={disabled}
/>
</div>
<divclassName="space-y-1.5">
<LabelhtmlFor="duration">Durée(s)</Label>
<Input
id="duration"
type="number"
min={0}
placeholder="ensecondes"
value={duration}
onChange={(e)=>setDuration(e.target.value)}
disabled={disabled}
/>
</div>
<divclassName="space-y-1.5">
<LabelhtmlFor="magnitude">Magnitude</Label>
<Input
id="magnitude"
type="number"
step={0.1}
placeholder="ex:-3"
value={magnitude}
onChange={(e)=>setMagnitude(e.target.value)}
disabled={disabled}
/>
</div>
</div>

<Button
type="submit"
className="w-full"
disabled={disabled||isSubmitting||!description.trim()}
>
{isSubmitting?"Envoiencours...":"??Signalerl'observation"}
</Button>
</form>
);
}
