import{useMemo}from"react";
import{Badge}from"@/components/ui/badge";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
importtype{CosmosObservation,CosmosEvent}from"@/hooks/useCosmosLive";

constPHENOMENON_LABELS:Record<string,string>={
meteor:"??Météore",
fireball:"??Bolide",
comet:"??Comète",
supernova:"??Supernova",
aurora:"??Aurore",
satellite:"??Satellite",
atmospheric:"??Atmosphérique",
unknown:"?Inconnu",
};

constPHENOMENON_COLORS:Record<string,string>={
meteor:"bg-blue-500/20text-blue-300border-blue-500/30",
fireball:"bg-orange-500/20text-orange-300border-orange-500/30",
comet:"bg-cyan-500/20text-cyan-300border-cyan-500/30",
supernova:"bg-red-500/20text-red-300border-red-500/30",
aurora:"bg-green-500/20text-green-300border-green-500/30",
satellite:"bg-purple-500/20text-purple-300border-purple-500/30",
atmospheric:"bg-yellow-500/20text-yellow-300border-yellow-500/30",
unknown:"bg-mutedtext-muted-foreground",
};

interfaceProps{
observations:CosmosObservation[];
events:CosmosEvent[];
userPosition:GeolocationCoordinates|null;
}

functiontimeAgo(iso:string){
constdiff=Date.now()-newDate(iso).getTime();
consts=Math.floor(diff/1000);
if(s<60)return`ilya${s}s`;
constm=Math.floor(s/60);
if(m<60)return`ilya${m}min`;
consth=Math.floor(m/60);
return`ilya${h}h`;
}

functiondistance(lat1:number,lon1:number,lat2:number,lon2:number){
constR=6371;
constdLat=((lat2-lat1)*Math.PI)/180;
constdLon=((lon2-lon1)*Math.PI)/180;
consta=
Math.sin(dLat/2)**2+
Math.cos((lat1*Math.PI)/180)*
Math.cos((lat2*Math.PI)/180)*
Math.sin(dLon/2)**2;
returnMath.round(R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)));
}

exportfunctionCosmosObservationFeed({observations,events,userPosition}:Props){
constrecentObs=useMemo(
()=>observations.slice(0,50),
[observations]
);

return(
<divclassName="space-y-3">
{/*Événementsconfirmésenhaut*/}
{events.length>0&&(
<divclassName="space-y-2">
<pclassName="text-xsfont-semibolduppercasetracking-widesttext-muted-foreground">
Événementsdétectés({events.length})
</p>
{events.slice(0,5).map((evt)=>(
<Card
key={evt.id}
className="border-primary/30bg-primary/5backdrop-blur-sm"
>
<CardHeaderclassName="pb-2pt-3px-4">
<divclassName="flexitems-startjustify-betweengap-2">
<CardTitleclassName="text-smfont-semiboldleading-tight">
{PHENOMENON_LABELS[evt.phenomenon_type]??evt.phenomenon_type}{""}
—{evt.title}
</CardTitle>
<Badge
variant="outline"
className="shrink-0text-[10px]"
>
{evt.observation_count}obs.
</Badge>
</div>
</CardHeader>
<CardContentclassName="px-4pb-3">
{evt.description&&(
<pclassName="text-xstext-muted-foregroundline-clamp-2">
{evt.description}
</p>
)}
<divclassName="mt-2flexitems-centergap-2text-[10px]text-muted-foreground">
<span>{timeAgo(evt.event_at)}</span>
<span>·</span>
<spanclassName="capitalize">{evt.status}</span>
{evt.confidence_score!=null&&(
<>
<span>·</span>
<span>
Confiance{Math.round(evt.confidence_score*100)}%
</span>
</>
)}
</div>
</CardContent>
</Card>
))}
</div>
)}

{/*Fluxdesobservationsbrutes*/}
<pclassName="text-xsfont-semibolduppercasetracking-widesttext-muted-foreground">
Observationsendirect({observations.length})
</p>
{recentObs.length===0&&(
<pclassName="py-8text-centertext-smtext-muted-foreground">
Aucuneobservationrécente.Soyezlepremieràsignalerunphénomène!
</p>
)}
<divclassName="space-y-2">
{recentObs.map((obs)=>(
<div
key={obs.id}
className="flexitems-startgap-3rounded-lgborderborder-border/50bg-card/50p-3backdrop-blur-sm"
>
<span
className={`shrink-0rounded-mdborderpx-2py-0.5text-[11px]font-medium${PHENOMENON_COLORS[obs.phenomenon_type]??""}`}
>
{PHENOMENON_LABELS[obs.phenomenon_type]??obs.phenomenon_type}
</span>
<divclassName="min-w-0flex-1">
<pclassName="text-xstext-foregroundline-clamp-2">
{obs.description}
</p>
<pclassName="mt-1text-[10px]text-muted-foreground">
{timeAgo(obs.observed_at)}
{userPosition&&(
<>
{""}·à~
{distance(
userPosition.latitude,
userPosition.longitude,
obs.latitude,
obs.longitude
)}{""}
km
</>
)}
{obs.event_id&&(
<spanclassName="ml-2text-primary">?clustérisé</span>
)}
</p>
</div>
</div>
))}
</div>
</div>
);
}
