import{useMemo}from"react";
importtype{CosmosObservation}from"@/hooks/useCosmosLive";

constTYPE_COLOR:Record<string,string>={
meteor:"#60a5fa",
fireball:"#fb923c",
comet:"#22d3ee",
supernova:"#f87171",
aurora:"#4ade80",
satellite:"#c084fc",
atmospheric:"#fbbf24",
unknown:"#94a3b8",
};

interfaceProps{
observations:CosmosObservation[];
userPosition:GeolocationCoordinates|null;
widthPx?:number;
heightPx?:number;
}

/**
*MinicarteSVGdesobservations—projectionéquirectangulairesimplifiée.
*Pasdedépendanceexterne,fonctionneentièrementenSVGReact.
*/
exportfunctionCosmosLiveMap({observations,userPosition,widthPx=600,heightPx=300}:Props){
constrecentObs=useMemo(
()=>
observations
.filter((o)=>Date.now()-newDate(o.observed_at).getTime()<2*3600_000)
.slice(0,200),
[observations]
);

//Déterminelesbornesdelacarte
constbounds=useMemo(()=>{
constlats=[
...recentObs.map((o)=>o.latitude),
userPosition?.latitude??0,
];
constlons=[
...recentObs.map((o)=>o.longitude),
userPosition?.longitude??0,
];
constminLat=Math.min(...lats)-5;
constmaxLat=Math.max(...lats)+5;
constminLon=Math.min(...lons)-5;
constmaxLon=Math.max(...lons)+5;
return{minLat,maxLat,minLon,maxLon};
},[recentObs,userPosition]);

functionproject(lat:number,lon:number):[number,number]{
constx=
((lon-bounds.minLon)/(bounds.maxLon-bounds.minLon))*widthPx;
consty=
((bounds.maxLat-lat)/(bounds.maxLat-bounds.minLat))*heightPx;
return[x,y];
}

return(
<divclassName="overflow-hiddenrounded-xlborderborder-borderbg-background/80backdrop-blur-sm">
<svg
viewBox={`00${widthPx}${heightPx}`}
className="h-autow-full"
style={{background:"radial-gradient(ellipseatcenter,#0f172a0%,#020617100%)"}}
>
{/*Grilledefond*/}
{Array.from({length:6}).map((_,i)=>(
<line
key={`v${i}`}
x1={(i*widthPx)/5}
y1={0}
x2={(i*widthPx)/5}
y2={heightPx}
stroke="#1e293b"
strokeWidth={0.5}
/>
))}
{Array.from({length:4}).map((_,i)=>(
<line
key={`h${i}`}
x1={0}
y1={(i*heightPx)/3}
x2={widthPx}
y2={(i*heightPx)/3}
stroke="#1e293b"
strokeWidth={0.5}
/>
))}

{/*Observations*/}
{recentObs.map((obs)=>{
const[x,y]=project(obs.latitude,obs.longitude);
constage=Date.now()-newDate(obs.observed_at).getTime();
constopacity=Math.max(0.2,1-age/(2*3600_000));
constcolor=TYPE_COLOR[obs.phenomenon_type]??"#94a3b8";
constr=obs.event_id?5:3;
return(
<gkey={obs.id}opacity={opacity}>
{obs.event_id&&(
<circle
cx={x}
cy={y}
r={r+4}
fill="none"
stroke={color}
strokeWidth={1}
opacity={0.4}
/>
)}
<circlecx={x}cy={y}r={r}fill={color}/>
</g>
);
})}

{/*Positiondel'utilisateur*/}
{userPosition&&(()=>{
const[x,y]=project(userPosition.latitude,userPosition.longitude);
return(
<g>
<circlecx={x}cy={y}r={6}fill="none"stroke="#38bdf8"strokeWidth={2}/>
<circlecx={x}cy={y}r={3}fill="#38bdf8"/>
<circlecx={x}cy={y}r={12}fill="none"stroke="#38bdf8"strokeWidth={0.5}opacity={0.4}>
<animate
attributeName="r"
values="10;20;10"
dur="2s"
repeatCount="indefinite"
/>
<animate
attributeName="opacity"
values="0.4;0;0.4"
dur="2s"
repeatCount="indefinite"
/>
</circle>
</g>
);
})()}

{/*Légende*/}
{Object.entries(TYPE_COLOR).slice(0,4).map(([type,color],i)=>(
<gkey={type}transform={`translate(${widthPx-120},${10+i*16})`}>
<circlecx={5}cy={5}r={4}fill={color}/>
<textx={13}y={9}fill="#94a3b8"fontSize={9}fontFamily="monospace">
{type}
</text>
</g>
))}
</svg>

{/*Compteurs*/}
<divclassName="flexitems-centergap-4border-tborder-borderpx-4py-2text-xstext-muted-foreground">
<span>
<spanclassName="font-mediumtext-foreground">{recentObs.length}</span>observations(2h)
</span>
{userPosition&&(
<span>
??{userPosition.latitude.toFixed(2)}°,{userPosition.longitude.toFixed(2)}°
</span>
)}
<spanclassName="ml-autoflexitems-centergap-1.5">
<spanclassName="inline-blocksize-2animate-pulserounded-fullbg-green-500"/>
ENDIRECT
</span>
</div>
</div>
);
}
