import{useCallback,useRef,useState}from"react";
import{Upload,ImageasImageIcon,AlertCircle,CheckCircle2,Loader2,X}from"lucide-react";
import{Card,CardContent,CardDescription,CardHeader,CardTitle}from"@/components/ui/card";
import{Button}from"@/components/ui/button";
import{Progress}from"@/components/ui/progress";
import{Alert,AlertDescription}from"@/components/ui/alert";
import{useImageUpload}from"@/hooks/useImageUpload";
importtype{SkyObject}from"@/lib/sky-objects";

exportfunctionImageUploadCard({skyObject}:{skyObject:SkyObject}){
const{uploadImage,uploadState,reset}=useImageUpload(skyObject.key,skyObject.name);
const[preview,setPreview]=useState<string|null>(null);
const[isDragging,setIsDragging]=useState(false);
constinputRef=useRef<HTMLInputElement>(null);

consthandleFile=useCallback(
(file:File)=>{
constobjectUrl=URL.createObjectURL(file);
setPreview(objectUrl);
uploadImage(file).then((id)=>{
if(!id){
URL.revokeObjectURL(objectUrl);
setPreview(null);
}
});
},
[uploadImage],
);

consthandleDrop=useCallback(
(e:React.DragEvent)=>{
e.preventDefault();
setIsDragging(false);
constfile=e.dataTransfer.files[0];
if(file)handleFile(file);
},
[handleFile],
);

consthandleChange=useCallback(
(e:React.ChangeEvent<HTMLInputElement>)=>{
constfile=e.target.files?.[0];
if(file)handleFile(file);
},
[handleFile],
);

consthandleReset=()=>{
if(preview)URL.revokeObjectURL(preview);
setPreview(null);
reset();
if(inputRef.current)inputRef.current.value="";
};

constisActive=uploadState.status!=="idle";

return(
<Card>
<CardHeader>
<CardTitleclassName="flexitems-centergap-2text-base">
<ImageIconclassName="size-4"/>
Partagervotreobservationde{skyObject.name}
</CardTitle>
<CardDescription>
Votrephotoseraanalyseparl'IA,puiscompareaveccellesdesautresastronomespour
dtecterd'ventuellesdcouvertes.
</CardDescription>
</CardHeader>
<CardContentclassName="space-y-4">
<Alert>
<AlertCircleclassName="size-4"/>
<AlertDescription>
<strong>Photosuniquement.</strong>LesimagesgnresparIAsontautomatiquementdtectes
etrejetes.
</AlertDescription>
</Alert>

{uploadState.status==="idle"&&(
<div
role="button"
tabIndex={0}
aria-label="Zoned'uploadd'image"
className={`relativeflexmin-h-40cursor-pointerflex-colitems-centerjustify-centergap-3rounded-lgborder-2border-dashedp-6text-centertransition-colors${
isDragging?"border-primarybg-primary/5":"border-borderhover:border-primary/50"
}`}
onClick={()=>inputRef.current?.click()}
onKeyDown={(e)=>e.key==="Enter"&&inputRef.current?.click()}
onDragOver={(e)=>{
e.preventDefault();
setIsDragging(true);
}}
onDragLeave={()=>setIsDragging(false)}
onDrop={handleDrop}
>
<UploadclassName="size-8text-muted-foreground"/>
<div>
<pclassName="font-medium">Cliquezouglissez-dposezvotreimage</p>
<pclassName="mt-1text-smtext-muted-foreground">JPEG,PNGouWebPmax10Mo</p>
</div>
<input
ref={inputRef}
type="file"
accept="image/jpeg,image/png,image/webp"
className="sr-only"
onChange={handleChange}
/>
</div>
)}

{isActive&&(
<divclassName="space-y-3">
<divclassName="relativeoverflow-hiddenrounded-lgbg-muted">
{preview&&(
<img
src={preview}
alt="Aperudel'image"
className="max-h-64w-fullobject-contain"
/>
)}
{uploadState.status!=="complete"&&uploadState.status!=="error"&&(
<divclassName="absoluteinset-0flexitems-centerjustify-centerbg-background/60">
<Loader2className="size-8animate-spintext-primary"/>
</div>
)}
</div>

<divclassName="space-y-1.5">
<divclassName="flexitems-centerjustify-betweentext-sm">
<spanclassName="font-mediumtext-muted-foreground">
{uploadState.status==="uploading"&&"Envoiencours"}
{uploadState.status==="analyzing"&&
"AnalyseVisionIA(dtection&astronomie)"}
{uploadState.status==="complete"&&"Valideetenregistre!"}
{uploadState.status==="error"&&(uploadState.errorMessage??"Erreur")}
</span>
<spanclassName="tabular-nums">{uploadState.progress}%</span>
</div>
<Progressvalue={uploadState.progress}/>
</div>

{uploadState.status==="complete"&&(
<Alert>
<CheckCircle2className="size-4"/>
<AlertDescription>
Imageajoutelagaleriecollaborative.Elleseracompareaveclesautres
observationspourdtecterdenouvellesdcouvertes.
</AlertDescription>
</Alert>
)}

{(uploadState.status==="complete"||uploadState.status==="error")&&(
<Buttonvariant="outline"size="sm"className="gap-2"onClick={handleReset}>
<XclassName="size-3.5"/>
Uploaderuneautreimage
</Button>
)}
</div>
)}
</CardContent>
</Card>
);
}
