import{useMemo}from"react";
import{Heart,X,Compass}from"lucide-react";
import{toast}from"sonner";
import{Link}from"@tanstack/react-router";
import{useSky}from"@/lib/sky-store";
import{findSkyObject,instrumentLabel}from"@/lib/sky-objects";
import{
equatorialToHorizontal,
localSiderealTime,
riseSetTimes,
formatTime,
formatDegrees,
cardinalName,
}from"@/lib/astro";
import{useFavorites}from"@/hooks/useFavorites";
import{Button}from"@/components/ui/button";
import{ObjectGallery}from"@/components/ObjectGallery";

exportfunctionObjectPanel(){
const{selected,select,date,location}=useSky();
const{user,isFavorite,toggle}=useFavorites();

constobject=useMemo(
()=>(selected?findSkyObject(selected,date):null),
[selected,date],
);

constinfo=useMemo(()=>{
if(!object)returnnull;
constlst=localSiderealTime(date,location.longitude);
consthz=equatorialToHorizontal(
{ra:object.ra,dec:object.dec},
lst,
location.latitude,
);
constrs=riseSetTimes({ra:object.ra,dec:object.dec},date,{
latitude:location.latitude,
longitude:location.longitude,
});
return{hz,rs};
},[object,date,location]);

if(!object||!info)returnnull;

constvisible=info.hz.alt>0;

return(
<divclassName="glasspointer-events-autoabsoluteinset-x-3bottom-3z-20max-h-[58vh]overflow-y-autorounded-xlp-4sm:inset-x-autosm:right-3sm:top-20sm:bottom-autosm:w-[340px]">
<divclassName="flexitems-startjustify-betweengap-3">
<div>
<pclassName="label-capstext-primary">{object.subtitle}</p>
<h2className="mt-1text-xlfont-semiboldleading-tight">
{object.name}
</h2>
</div>
<button
onClick={()=>select(null)}
aria-label="Fermer"
className="rounded-mdp-1text-muted-foregroundhover:bg-accent"
>
<XclassName="size-4"/>
</button>
</div>

<div
className={`mt-3inline-flexitems-centergap-2rounded-fullpx-3py-1text-xsfont-medium${
visible
?"bg-primary/15text-primary"
:"bg-mutedtext-muted-foreground"
}`}
>
<CompassclassName="size-3.5"/>
{visible
?`Visible—${formatDegrees(info.hz.alt)}au-dessusdel'horizon,versle${cardinalName(info.hz.az)}`
:"Sousl'horizonencemoment"}
</div>

<dlclassName="mt-4gridgrid-cols-2gap-x-3gap-y-3text-sm">
<Rowlabel="Magnitude"value={object.mag?.toFixed(1)??"—"}/>
<Rowlabel="Constellation"value={object.constellation}/>
<Rowlabel="Lever"value={formatTime(info.rs.rise)}/>
<Rowlabel="Coucher"value={formatTime(info.rs.set)}/>
<Rowlabel="Culmination"value={formatTime(info.rs.transit)}/>
<Row
label="Hauteurmax"
value={formatDegrees(info.rs.maxAltitude)}
/>
</dl>

<ObjectGallery
query={object.photoQuery}
queries={object.photoQueries}
name={object.name}
/>

<pclassName="mt-4rounded-lgbg-secondary/60p-3text-smleading-relaxedtext-foreground/85">
{object.description}
</p>
<pclassName="label-capsmt-3text-muted-foreground">
Observationconseillée:{instrumentLabel(object.instrument)}
{object.extra?`·${object.extra}`:""}
</p>


<divclassName="mt-4">
{user?(
<Button
variant={isFavorite(object.key)?"secondary":"default"}
size="sm"
className="w-full"
onClick={()=>
toggle.mutate(object.key,{
onSuccess:(r)=>
toast.success(
r==="added"
?"Ajoutéàvosfavoris"
:"Retirédevosfavoris",
),
onError:()=>toast.error("Actionimpossible"),
})
}
>
<Heart
className={`size-4${isFavorite(object.key)?"fill-current":""}`}
/>
{isFavorite(object.key)?"Dansmesfavoris":"Ajouterauxfavoris"}
</Button>
):(
<ButtonasChildvariant="secondary"size="sm"className="w-full">
<Linkto="/auth">Seconnecterpourenregistrer</Link>
</Button>
)}
</div>
</div>
);
}

functionRow({label,value}:{label:string;value:string}){
return(
<div>
<dtclassName="label-capstext-muted-foreground">{label}</dt>
<ddclassName="mt-0.5font-monotext-sm">{value}</dd>
</div>
);
}
