import{useEffect,useState}from"react";
import{useQuery}from"@tanstack/react-query";
import{ImageOff,Loader2,X}from"lucide-react";

exportinterfaceCommonsPhoto{
title:string;
thumb:string;
full:string;
page:string;
credit:string;
license:string;
}

functionstripHtml(v:string|undefined){
if(!v)return"";
returnv.replace(/<[^>]*>/g,"").trim();
}

asyncfunctionsearchCommons(query:string,limit:number):Promise<CommonsPhoto[]>{
consturl=
"https://commons.wikimedia.org/w/api.php?"+
newURLSearchParams({
action:"query",
generator:"search",
gsrsearch:`filetype:bitmap${query}`,
gsrnamespace:"6",
gsrlimit:String(limit),
prop:"imageinfo",
iiprop:"url|extmetadata",
iiurlwidth:"800",
format:"json",
origin:"*",
}).toString();

constres=awaitfetch(url);
if(!res.ok)thrownewError("Imagesindisponibles");
constdata=(awaitres.json())as{
query?:{pages?:Record<string,any>};
};
constpages=Object.values(data.query?.pages??{});
returnpages
.sort((a,b)=>(a.index??0)-(b.index??0))
.map((p)=>{
constii=p.imageinfo?.[0];
constmeta=ii?.extmetadata??{};
return{
title:String(p.title??"").replace(/^File:/,""),
thumb:ii?.thumburl??"",
full:ii?.url??"",
page:ii?.descriptionurl??"",
credit:stripHtml(meta.Artist?.value)||"WikimediaCommons",
license:stripHtml(meta.LicenseShortName?.value)||"",
};
})
.filter((p)=>p.thumb);
}

constMAX_PHOTOS=12;

asyncfunctionfetchPhotos(queries:string[]):Promise<CommonsPhoto[]>{
constresults=awaitPromise.allSettled(
queries.filter(Boolean).map((q)=>searchCommons(q,12)),
);
constseen=newSet<string>();
constout:CommonsPhoto[]=[];
//entrelacelesrésultatspourvarierlessources
constlists=results
.filter((r):risPromiseFulfilledResult<CommonsPhoto[]>=>r.status==="fulfilled")
.map((r)=>r.value);
constdepth=Math.max(0,...lists.map((l)=>l.length));
for(leti=0;i<depth&&out.length<MAX_PHOTOS;i++){
for(constlistoflists){
constp=list[i];
if(!p||seen.has(p.title))continue;
seen.add(p.title);
out.push(p);
if(out.length>=MAX_PHOTOS)break;
}
}
if(out.length===0&&results.every((r)=>r.status==="rejected")){
thrownewError("Imagesindisponibles");
}
returnout;
}

exportfunctionObjectGallery({
query,
queries,
name,
}:{
query:string;
queries?:string[]|undefined;
name:string;
}){
const[lightbox,setLightbox]=useState<CommonsPhoto|null>(null);

constallQueries=Array.from(
newSet([query,...(queries??[])].map((q)=>q?.trim()).filter(Boolean)asstring[]),
);

const{data,isLoading,isError}=useQuery({
queryKey:["commons-photos",allQueries],
queryFn:()=>fetchPhotos(allQueries),
staleTime:1000*60*60,
retry:1,
});

useEffect(()=>setLightbox(null),[query]);

if(isLoading){
return(
<divclassName="mt-4flexh-24items-centerjustify-centerrounded-lgbg-secondary/50text-muted-foreground">
<Loader2className="size-4animate-spin"/>
</div>
);
}

if(isError||!data||data.length===0){
return(
<divclassName="mt-4flexh-16items-centerjustify-centergap-2rounded-lgbg-secondary/50text-xstext-muted-foreground">
<ImageOffclassName="size-3.5"/>
Aucunephototrouvée
</div>
);
}

return(
<>
<divclassName="mt-4">
<pclassName="label-capsmb-2text-muted-foreground">
Photographies({data.length})
</p>
<divclassName="gridgrid-cols-3gap-2">
{data.map((p)=>(
<button
key={p.title}
onClick={()=>setLightbox(p)}
className="grouprelativeaspect-squareoverflow-hiddenrounded-lgbg-secondaryring-1ring-border/60transitionhover:ring-primary"
title={p.title}
>
<img
src={p.thumb}
alt={`${name}—${p.title}`}
loading="lazy"
className="size-fullobject-covertransitiongroup-hover:scale-105"
/>
</button>
))}
</div>
<pclassName="mt-2text-[11px]leading-snugtext-muted-foreground">
Images:WikimediaCommons
</p>
</div>

{lightbox&&(
<div
className="fixedinset-0z-50flexitems-centerjustify-centerbg-background/90p-4backdrop-blur-sm"
onClick={()=>setLightbox(null)}
>
<div
className="max-h-fullw-fullmax-w-3xloverflow-y-auto"
onClick={(e)=>e.stopPropagation()}
>
<divclassName="flexitems-startjustify-betweengap-3">
<pclassName="text-smfont-medium">{lightbox.title}</p>
<button
onClick={()=>setLightbox(null)}
aria-label="Fermer"
className="rounded-mdp-1text-muted-foregroundhover:bg-accent"
>
<XclassName="size-4"/>
</button>
</div>
<img
src={lightbox.full}
alt={`${name}—${lightbox.title}`}
className="mt-3w-fullrounded-xl"
/>
<pclassName="mt-2text-xstext-muted-foreground">
{lightbox.credit}
{lightbox.license?`·${lightbox.license}`:""}·{""}
<a
href={lightbox.page}
target="_blank"
rel="noreferrer"
className="underline"
>
source
</a>
</p>
</div>
</div>
)}
</>
);
}
