import{Link}from"@tanstack/react-router";
import{ExternalLink}from"lucide-react";
import{CommonsImage}from"@/components/CommonsImage";
import{CATEGORIES,imageQuery,typeLinkItem}from"@/data/resources";

exportfunctionResourceBreadcrumb({current}:{current:string}){
return(
<navclassName="flexflex-wrapitems-centergap-2text-xs">
<Link
to="/ressources"
className="rounded-mdpx-2py-1text-muted-foregroundtransition-colorshover:bg-accenthover:text-foreground"
>
Ressources
</Link>
<spanclassName="text-muted-foreground/50">/</span>
<spanclassName="rounded-mdbg-primary/15px-2py-1font-mediumtext-primary">
{current}
</span>
<spanclassName="ml-autoflexflex-wrapgap-1">
{CATEGORIES.filter((c)=>c.title!==current).map((c)=>(
<Link
key={c.slug}
to={c.to}
className="rounded-mdpx-2py-1text-muted-foregroundtransition-colorshover:bg-accenthover:text-foreground"
>
{c.title}
</Link>
))}
</span>
</nav>
);
}

exportfunctionLinkGrid({items}:{items:readonlyLinkItem[]}){
return(
<divclassName="gridgap-4sm:grid-cols-2lg:grid-cols-3">
{items.map((i)=>(
<a
key={i.url}
href={i.url}
target="_blank"
rel="noopenernoreferrer"
className="groupoverflow-hiddenrounded-xlborderborder-border/60bg-card/40transition-colorshover:border-primary/50hover:bg-accent/40"
>
<CommonsImage
query={imageQuery(i.name,i.desc)}
alt={i.name}
className="h-32w-full"
/>
<divclassName="p-4">
<pclassName="flexitems-centergap-1.5font-medium">
{i.name}
<ExternalLinkclassName="size-3.5text-muted-foregroundtransition-colorsgroup-hover:text-primary"/>
</p>
<pclassName="mt-1text-smtext-muted-foreground">{i.desc}</p>
</div>
</a>
))}
</div>
);
}
