import{useCallback,useEffect,useMemo,useRef,useState}from"react";
import{
constellations,
stars,
deepSky,
starColor,
TYPE_FAMILY,
}from"@/data/catalog";
import{
DEG,
RAD,
equatorialToHorizontal,
localSiderealTime,
obliquity,
dayNumber,
}from"@/lib/astro";
import{solarSystemObjects}from"@/lib/sky-objects";
import{useSky}from"@/lib/sky-store";

interfaceHit{
key:string;
x:number;
y:number;
r:number;
}

interfaceView{
az:number;
alt:number;
fov:number;
}

constMIN_FOV=4;
constMAX_FOV=150;

functiondirFromAltAz(alt:number,az:number){
constca=Math.cos(alt*DEG);
return[ca*Math.sin(az*DEG),ca*Math.cos(az*DEG),Math.sin(alt*DEG)];
}

exportfunctionSkyCanvas({compass}:{compass:boolean}){
constcanvasRef=useRef<HTMLCanvasElement|null>(null);
constwrapRef=useRef<HTMLDivElement|null>(null);
const{date,location,select,selected,target,setTarget,showLines,showLabels}=
useSky();
const[view,setView]=useState<View>({az:180,alt:35,fov:100});
consthitsRef=useRef<Hit[]>([]);
constviewRef=useRef(view);
viewRef.current=view;
constdragRef=useRef<{x:number;y:number;moved:boolean}|null>(null);
const[size,setSize]=useState({w:800,h:600});

constlst=useMemo(
()=>localSiderealTime(date,location.longitude),
[date,location.longitude],
);

//Cibledemandéedepuisuneautrepage:oncentrelavuedessus.
useEffect(()=>{
if(!target)return;
constall=[
...deepSky.map((o)=>({key:`dso:${o.id}`,ra:o.ra,dec:o.dec})),
...solarSystemObjects(date).map((o)=>({
key:o.key,
ra:o.ra,
dec:o.dec,
})),
];
constfound=all.find((o)=>o.key===target);
if(found){
consth=equatorialToHorizontal(
{ra:found.ra,dec:found.dec},
lst,
location.latitude,
);
setView((v)=>({az:h.az,alt:h.alt,fov:Math.min(v.fov,40)}));
select(target);
}
setTarget(null);
},[target,date,lst,location.latitude,select,setTarget]);

useEffect(()=>{
constel=wrapRef.current;
if(!el)return;
constro=newResizeObserver(()=>{
setSize({w:el.clientWidth,h:el.clientHeight});
});
ro.observe(el);
setSize({w:el.clientWidth,h:el.clientHeight});
return()=>ro.disconnect();
},[]);

//Boussole:orientationdel'appareil
useEffect(()=>{
if(!compass)return;
consthandler=(e:DeviceOrientationEvent&{webkitCompassHeading?:number})=>{
constheading=
typeofe.webkitCompassHeading==="number"
?e.webkitCompassHeading
:e.alpha!=null
?360-e.alpha
:null;
if(heading==null)return;
constbeta=e.beta??0;
setView((v)=>({
...v,
az:(heading+360)%360,
alt:Math.max(-20,Math.min(89,beta-90+90-(90-beta)*0+(beta-90))),
}));
};
window.addEventListener("deviceorientation",handlerasEventListener,true);
return()=>
window.removeEventListener("deviceorientation",handlerasEventListener,true);
},[compass]);

constprojector=useCallback(
(v:View,w:number,h:number)=>{
consta=v.alt*DEG;
constA=v.az*DEG;
constc=[
Math.cos(a)*Math.sin(A),
Math.cos(a)*Math.cos(A),
Math.sin(a),
];
constright=[Math.cos(A),-Math.sin(A),0];
constup=[
-Math.sin(a)*Math.sin(A),
-Math.sin(a)*Math.cos(A),
Math.cos(a),
];
constscale=h/2/(2*Math.tan((v.fov*DEG)/4));
constcx=w/2;
constcy=h/2;
return{
project(dir:number[]){
constX=dir[0]!*right[0]!+dir[1]!*right[1]!+dir[2]!*right[2]!;
constY=dir[0]!*up[0]!+dir[1]!*up[1]!+dir[2]!*up[2]!;
constZ=dir[0]!*c[0]!+dir[1]!*c[1]!+dir[2]!*c[2]!;
if(Z<-0.6)returnnull;
constk=2/(1+Z);
return[cx+X*k*scale,cy-Y*k*scale]asconst;
},
unproject(px:number,py:number){
constX=(px-cx)/scale;
constY=-(py-cy)/scale;
constr=Math.hypot(X,Y);
consttheta=2*Math.atan(r/2);
if(r===0)returnc;
constst=Math.sin(theta)/r;
constct=Math.cos(theta);
return[
ct*c[0]!+st*(X*right[0]!+Y*up[0]!),
ct*c[1]!+st*(X*right[1]!+Y*up[1]!),
ct*c[2]!+st*(X*right[2]!+Y*up[2]!),
];
},
};
},
[],
);

constdraw=useCallback(()=>{
constcanvas=canvasRef.current;
if(!canvas)return;
const{w,h}=size;
if(w===0||h===0)return;
constdpr=Math.min(window.devicePixelRatio||1,2);
canvas.width=w*dpr;
canvas.height=h*dpr;
canvas.style.width=`${w}px`;
canvas.style.height=`${h}px`;
constctx=canvas.getContext("2d");
if(!ctx)return;
ctx.setTransform(dpr,0,0,dpr,0,0);

constv=viewRef.current;
const{project}=projector(v,w,h);
consthits:Hit[]=[];
constlat=location.latitude;

constsun=solarSystemObjects(date).find((o)=>o.key==="sun")!;
constsunAlt=equatorialToHorizontal(
{ra:sun.ra,dec:sun.dec},
lst,
lat,
).alt;
constdayFactor=Math.max(0,Math.min(1,(sunAlt+12)/18));

//Fondduciel
constgrad=ctx.createLinearGradient(0,0,0,h);
if(dayFactor>0.6){
grad.addColorStop(0,"#2f6ea8");
grad.addColorStop(1,"#9dc6e3");
}elseif(dayFactor>0.05){
grad.addColorStop(0,"#0b1734");
grad.addColorStop(1,"#6b4a63");
}else{
grad.addColorStop(0,"#03060f");
grad.addColorStop(1,"#0a1226");
}
ctx.fillStyle=grad;
ctx.fillRect(0,0,w,h);

conststarAlpha=1-dayFactor;
consteq2dir=(ra:number,dec:number)=>{
consthz=equatorialToHorizontal({ra,dec},lst,lat);
return{dir:dirFromAltAz(hz.alt,hz.az),alt:hz.alt,az:hz.az};
};

//Écliptique
ctx.strokeStyle="rgba(255,196,120,0.25)";
ctx.lineWidth=1;
ctx.setLineDash([4,6]);
ctx.beginPath();
constecl=obliquity(dayNumber(date));
letstarted=false;
for(letl=0;l<=360;l+=2){
constra=
(Math.atan2(
Math.cos(ecl*DEG)*Math.sin(l*DEG),
Math.cos(l*DEG),
)*
RAD+
360)%
360;
constdec=Math.asin(Math.sin(ecl*DEG)*Math.sin(l*DEG))*RAD;
constp=project(eq2dir(ra,dec).dir);
if(!p){
started=false;
continue;
}
if(!started){
ctx.moveTo(p[0],p[1]);
started=true;
}elsectx.lineTo(p[0],p[1]);
}
ctx.stroke();
ctx.setLineDash([]);

//Lignesdeconstellation
if(showLines&&starAlpha>0.15){
ctx.strokeStyle=`rgba(122,164,255,${0.32*starAlpha})`;
ctx.lineWidth=1;
for(constcofconstellations){
ctx.beginPath();
for(constsegofc.l){
letbegun=false;
for(const[ra,dec]ofseg){
constp=project(eq2dir(ra!,dec!).dir);
if(!p){
begun=false;
continue;
}
if(!begun){
ctx.moveTo(p[0],p[1]);
begun=true;
}elsectx.lineTo(p[0],p[1]);
}
}
ctx.stroke();
}
if(showLabels){
ctx.fillStyle=`rgba(150,180,240,${0.5*starAlpha})`;
ctx.font="50011px'IBMPlexMono',monospace";
ctx.textAlign="center";
for(constcofconstellations){
constp=project(eq2dir(c.r,c.d).dir);
if(p)ctx.fillText(c.n.toUpperCase(),p[0],p[1]);
}
}
}

//Étoiles
constlimitMag=v.fov>80?5.0:v.fov>40?5.4:5.6;
constsizeScale=Math.max(0.8,Math.min(2.6,70/v.fov));
for(leti=0;i<stars.length;i++){
consts=stars[i]!;
if(s.m>limitMag)continue;
const{dir,alt}=eq2dir(s.r,s.d);
if(alt<-2)continue;
constp=project(dir);
if(!p)continue;
if(p[0]<-20||p[0]>w+20||p[1]<-20||p[1]>h+20)continue;
constradius=Math.max(0.5,(6.2-s.m)*0.42*sizeScale);
ctx.globalAlpha=starAlpha*Math.min(1,(6.4-s.m)/2.2);
ctx.fillStyle=starColor(s.v);
ctx.beginPath();
ctx.arc(p[0],p[1],radius,0,Math.PI*2);
ctx.fill();
if(radius>2.4){
ctx.globalAlpha=starAlpha*0.25;
ctx.beginPath();
ctx.arc(p[0],p[1],radius*2.4,0,Math.PI*2);
ctx.fill();
}
if(radius>1.6)hits.push({key:`star:${i}`,x:p[0],y:p[1],r:10});
if(showLabels&&s.n&&s.m<2.2&&v.fov<130){
ctx.globalAlpha=starAlpha*0.8;
ctx.fillStyle="rgba(226,235,255,0.85)";
ctx.font="50011px'IBMPlexSans',sans-serif";
ctx.textAlign="left";
ctx.fillText(s.n,p[0]+radius+4,p[1]+3);
}
}
ctx.globalAlpha=1;

//Objetsducielprofond
for(constoofdeepSky){
const{dir,alt}=eq2dir(o.ra,o.dec);
if(alt<-2)continue;
constp=project(dir);
if(!p)continue;
if(p[0]<-30||p[0]>w+30||p[1]<-30||p[1]>h+30)continue;
constfamily=TYPE_FAMILY[o.type]??"nebuleuse";
constisSel=selected===`dso:${o.id}`;
constrr=Math.max(
4,
Math.min(26,((o.size||8)/60)*(h/v.fov)*0.9),
);
ctx.globalAlpha=starAlpha*0.95;
ctx.lineWidth=isSel?2:1.2;
ctx.strokeStyle=isSel
?"#ffc76b"
:family==="galaxie"
?"rgba(196,150,255,0.85)"
:family==="amas"
?"rgba(255,236,168,0.85)"
:"rgba(120,230,206,0.85)";
ctx.beginPath();
if(family==="galaxie"){
ctx.ellipse(p[0],p[1],rr,rr*0.55,0.5,0,Math.PI*2);
}elseif(family==="amas"){
ctx.arc(p[0],p[1],rr,0,Math.PI*2);
ctx.setLineDash([3,3]);
}else{
ctx.rect(p[0]-rr,p[1]-rr*0.8,rr*2,rr*1.6);
}
ctx.stroke();
ctx.setLineDash([]);
if(showLabels&&(v.fov<60||(o.mag??12)<6)){
ctx.fillStyle=isSel?"#ffc76b":"rgba(210,224,255,0.75)";
ctx.font="50010px'IBMPlexMono',monospace";
ctx.textAlign="center";
ctx.fillText(o.id,p[0],p[1]-rr-5);
}
hits.push({key:`dso:${o.id}`,x:p[0],y:p[1],r:Math.max(14,rr)});
}
ctx.globalAlpha=1;

//Systèmesolaire
for(constoofsolarSystemObjects(date)){
const{dir,alt}=eq2dir(o.ra,o.dec);
if(alt<-3)continue;
constp=project(dir);
if(!p)continue;
constisSel=selected===o.key;
letrr=4;
letcolor="#ffe9b0";
if(o.kind==="sun"){
rr=Math.max(10,(16/v.fov)*h*0.05);
color="#ffd873";
}elseif(o.kind==="moon"){
rr=Math.max(8,(0.52/v.fov)*h*0.9);
color="#e8ecf5";
}else{
rr=Math.max(3.5,7-(o.mag??3));
color="#ffd0a0";
}
ctx.fillStyle=color;
ctx.shadowColor=color;
ctx.shadowBlur=o.kind==="sun"?40:12;
ctx.beginPath();
ctx.arc(p[0],p[1],rr,0,Math.PI*2);
ctx.fill();
ctx.shadowBlur=0;
if(isSel){
ctx.strokeStyle="#ffc76b";
ctx.lineWidth=2;
ctx.beginPath();
ctx.arc(p[0],p[1],rr+6,0,Math.PI*2);
ctx.stroke();
}
if(showLabels){
ctx.fillStyle="rgba(255,236,200,0.9)";
ctx.font="60011px'IBMPlexSans',sans-serif";
ctx.textAlign="center";
ctx.fillText(o.name,p[0],p[1]+rr+14);
}
hits.push({key:o.key,x:p[0],y:p[1],r:Math.max(16,rr+6)});
}

//Horizonetsol
ctx.beginPath();
lethorizonStarted=false;
consthorizonPts:(readonly[number,number])[]=[];
for(letaz=0;az<=360;az+=2){
constp=project(dirFromAltAz(0,az));
if(!p){
horizonStarted=false;
continue;
}
horizonPts.push(p);
if(!horizonStarted){
ctx.moveTo(p[0],p[1]);
horizonStarted=true;
}elsectx.lineTo(p[0],p[1]);
}
ctx.strokeStyle="rgba(140,170,220,0.55)";
ctx.lineWidth=1.5;
ctx.stroke();

//Voiledusol:onassombrittoutcequiestsousl'horizon
ctx.save();
ctx.beginPath();
ctx.rect(0,0,w,h);
for(letaz=0;az<=360;az+=2){
constp=project(dirFromAltAz(-0.1,az));
if(!p)continue;
}
ctx.restore();
for(letaz=0;az<360;az+=90){
constp=project(dirFromAltAz(1.5,az));
if(!p)continue;
ctx.fillStyle="rgba(160,190,235,0.85)";
ctx.font="60013px'IBMPlexMono',monospace";
ctx.textAlign="center";
ctx.fillText(["N","E","S","O"][az/90]!,p[0],p[1]);
}

//Zénith
constzen=project(dirFromAltAz(90,0));
if(zen){
ctx.strokeStyle="rgba(140,170,220,0.4)";
ctx.lineWidth=1;
ctx.beginPath();
ctx.moveTo(zen[0]-7,zen[1]);
ctx.lineTo(zen[0]+7,zen[1]);
ctx.moveTo(zen[0],zen[1]-7);
ctx.lineTo(zen[0],zen[1]+7);
ctx.stroke();
}

hitsRef.current=hits;
},[size,date,lst,location.latitude,selected,showLines,showLabels,projector]);

useEffect(()=>{
constid=requestAnimationFrame(draw);
return()=>cancelAnimationFrame(id);
},[draw,view]);

//Zoommolette/pincement(listenernonpassif)
useEffect(()=>{
constel=canvasRef.current;
if(!el)return;
constonWheel=(e:WheelEvent)=>{
e.preventDefault();
constdy=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?100:1);
constv=viewRef.current;
constnext=Math.max(
MIN_FOV,
Math.min(MAX_FOV,v.fov*Math.exp(dy*0.0015)),
);
if(next===v.fov)return;
constrect=el.getBoundingClientRect();
const{unproject}=projector(v,rect.width,rect.height);
constdir=unproject(e.clientX-rect.left,e.clientY-rect.top);
constcursorAlt=Math.asin(Math.max(-1,Math.min(1,dir[2]!)))*RAD;
constcursorAz=
(Math.atan2(dir[0]!,dir[1]!)*RAD+360)%360;
constk=1-next/v.fov;
letdAz=((cursorAz-v.az+540)%360)-180;
setView({
fov:next,
az:(v.az+dAz*k+360)%360,
alt:Math.max(-30,Math.min(89,v.alt+(cursorAlt-v.alt)*k)),
});
};
el.addEventListener("wheel",onWheel,{passive:false});
return()=>el.removeEventListener("wheel",onWheel);
},[projector]);

constonPointerDown=(e:React.PointerEvent)=>{
if(compass)return;
(e.targetasElement).setPointerCapture(e.pointerId);
dragRef.current={x:e.clientX,y:e.clientY,moved:false};
};

constonPointerMove=(e:React.PointerEvent)=>{
constd=dragRef.current;
if(!d)return;
constdx=e.clientX-d.x;
constdy=e.clientY-d.y;
if(Math.abs(dx)+Math.abs(dy)>3)d.moved=true;
d.x=e.clientX;
d.y=e.clientY;
setView((v)=>{
constperPx=v.fov/size.h;
return{
...v,
az:(v.az-dx*perPx+360)%360,
alt:Math.max(-30,Math.min(89,v.alt+dy*perPx)),
};
});
};

constonPointerUp=(e:React.PointerEvent)=>{
constd=dragRef.current;
dragRef.current=null;
if(!d||d.moved)return;
constrect=(e.currentTargetasHTMLElement).getBoundingClientRect();
constx=e.clientX-rect.left;
consty=e.clientY-rect.top;
letbest:Hit|null=null;
letbestDist=Infinity;
for(consthitofhitsRef.current){
constdist=Math.hypot(hit.x-x,hit.y-y);
if(dist<hit.r&&dist<bestDist){
best=hit;
bestDist=dist;
}
}
select(best?best.key:null);
};

return(
<divref={wrapRef}className="absoluteinset-0overflow-hidden">
<canvas
ref={canvasRef}
className="h-fullw-fulltouch-noneselect-none"
onPointerDown={onPointerDown}
onPointerMove={onPointerMove}
onPointerUp={onPointerUp}
onPointerCancel={()=>(dragRef.current=null)}
/>
<divclassName="pointer-events-noneabsolutebottom-3left-3font-monotext-[11px]uppercasetracking-widesttext-foreground/40">
{Math.round(view.az)}°az·{Math.round(view.alt)}°h·champ{""}
{Math.round(view.fov)}°
</div>
</div>
);
}
