import{useState}from"react";
import{useQuery,useMutation,useQueryClient}from"@tanstack/react-query";
import{
Heart,
MessageCircle,
Share2,
MoreHorizontal,
Telescope,
Send,
ChevronDown,
ChevronUp,
}from"lucide-react";
import{supabase}from"@/integrations/supabase/client";
import{Card,CardContent,CardHeader}from"@/components/ui/card";
import{Button}from"@/components/ui/button";
import{Avatar,AvatarFallback,AvatarImage}from"@/components/ui/avatar";
import{Textarea}from"@/components/ui/textarea";
import{Input}from"@/components/ui/input";
import{Separator}from"@/components/ui/separator";
import{toast}from"sonner";
import{useAuth}from"@/hooks/useAuth";
import{Link}from"@tanstack/react-router";

interfaceFeedPost{
post_id:string;
author_id:string;
display_name:string|null;
avatar_url:string|null;
content:string;
object_id:string|null;
object_name:string|null;
image_ids:string[];
likes_count:number;
comments_count:number;
shares_count:number;
created_at:string;
user_liked:boolean;
}

interfaceComment{
id:string;
user_id:string;
content:string;
created_at:string;
}

functiontimeAgo(dateStr:string):string{
constdiff=Date.now()-newDate(dateStr).getTime();
constm=Math.floor(diff/60000);
if(m<1)return"l'instant";
if(m<60)return`ilya${m}min`;
consth=Math.floor(m/60);
if(h<24)return`ilya${h}h`;
return`ilya${Math.floor(h/24)}j`;
}

functionImageGrid({imageIds}:{imageIds:string[]}){
const{data:images}=useQuery({
queryKey:["post-images",imageIds],
queryFn:async()=>{
const{data,error}=awaitsupabase
.from("user_images")
.select("id,image_url,object_name")
.in("id",imageIds);
if(error)throwerror;
returndata;
},
enabled:imageIds.length>0,
});

if(!images?.length)returnnull;

return(
<divclassName={`gridgap-1.5${images.length===1?"":"grid-cols-2"}`}>
{images.slice(0,4).map((img:{id:string;image_url:string;object_name:string})=>(
<divkey={img.id}className="aspect-videooverflow-hiddenrounded-lgbg-muted">
<img
src={img.image_url}
alt={img.object_name}
className="h-fullw-fullobject-cover"
loading="lazy"
/>
</div>
))}
</div>
);
}

functionPostCard({post}:{post:FeedPost}){
const{user}=useAuth();
constqueryClient=useQueryClient();
const[showComments,setShowComments]=useState(false);
const[commentText,setCommentText]=useState("");

const{data:comments}=useQuery({
queryKey:["comments",post.post_id],
queryFn:async()=>{
const{data,error}=awaitsupabase
.from("comments")
.select("id,user_id,content,created_at")
.eq("post_id",post.post_id)
.is("parent_comment_id",null)
.order("created_at",{ascending:true})
.limit(20);
if(error)throwerror;
returndataasComment[];
},
enabled:showComments,
});

constlikeMutation=useMutation({
mutationFn:async()=>{
if(!user)thrownewError("Nonauthentifi");
if(post.user_liked){
awaitsupabase.from("likes").delete().eq("post_id",post.post_id).eq("user_id",user.id);
}else{
awaitsupabase.from("likes").insert({post_id:post.post_id,user_id:user.id});
}
},
onSuccess:()=>queryClient.invalidateQueries({queryKey:["social-feed"]}),
onError:()=>toast.error("Impossibledelikercepost."),
});

constcommentMutation=useMutation({
mutationFn:async(content:string)=>{
if(!user)thrownewError("Nonauthentifi");
const{error}=awaitsupabase
.from("comments")
.insert({post_id:post.post_id,user_id:user.id,content});
if(error)throwerror;
},
onSuccess:()=>{
setCommentText("");
queryClient.invalidateQueries({queryKey:["comments",post.post_id]});
queryClient.invalidateQueries({queryKey:["social-feed"]});
},
onError:()=>toast.error("Impossibled'envoyerlecommentaire."),
});

constshareMutation=useMutation({
mutationFn:async()=>{
if(!user)thrownewError("Nonauthentifi");
awaitsupabase.from("shares").insert({post_id:post.post_id,user_id:user.id});
awaitnavigator.clipboard.writeText(`${window.location.origin}/communaute`);
},
onSuccess:()=>toast.success("Liencopidanslepresse-papier!"),
onError:()=>toast.error("Impossibledepartager."),
});

return(
<Card>
<CardHeaderclassName="pb-3">
<divclassName="flexitems-startjustify-betweengap-2">
<divclassName="flexitems-centergap-3">
<Linkto="/profil/$userId"params={{userId:post.author_id}}>
<AvatarclassName="size-9">
<AvatarImagesrc={post.avatar_url??undefined}/>
<AvatarFallback>
<TelescopeclassName="size-4"/>
</AvatarFallback>
</Avatar>
</Link>
<div>
<Link
to="/profil/$userId"
params={{userId:post.author_id}}
className="text-smfont-semiboldhover:underline"
>
{post.display_name??"Astronome"}
</Link>
<pclassName="text-xstext-muted-foreground">{timeAgo(post.created_at)}</p>
</div>
</div>
<Buttonvariant="ghost"size="icon"className="size-8shrink-0">
<MoreHorizontalclassName="size-4"/>
</Button>
</div>
</CardHeader>

<CardContentclassName="space-y-3">
<pclassName="text-smleading-relaxedwhitespace-pre-wrap">{post.content}</p>

{post.object_name&&(
<divclassName="flexitems-centergap-2rounded-mdbg-mutedpx-3py-2">
<TelescopeclassName="size-3.5shrink-0text-primary"/>
<spanclassName="text-smfont-medium">{post.object_name}</span>
</div>
)}

{post.image_ids.length>0&&<ImageGridimageIds={post.image_ids}/>}

<Separator/>

<divclassName="flexitems-centergap-1">
<Button
variant="ghost"
size="sm"
className={`gap-1.5${post.user_liked?"text-red-500":""}`}
onClick={()=>user&&likeMutation.mutate()}
disabled={!user||likeMutation.isPending}
>
<HeartclassName={`size-4${post.user_liked?"fill-current":""}`}/>
<spanclassName="tabular-nums">{post.likes_count}</span>
</Button>

<Button
variant="ghost"
size="sm"
className="gap-1.5"
onClick={()=>setShowComments((v)=>!v)}
>
<MessageCircleclassName="size-4"/>
<spanclassName="tabular-nums">{post.comments_count}</span>
{showComments?<ChevronUpclassName="size-3"/>:<ChevronDownclassName="size-3"/>}
</Button>

<Button
variant="ghost"
size="sm"
className="gap-1.5"
onClick={()=>user&&shareMutation.mutate()}
disabled={!user||shareMutation.isPending}
>
<Share2className="size-4"/>
<spanclassName="tabular-nums">{post.shares_count}</span>
</Button>
</div>

{showComments&&(
<divclassName="space-y-3border-tpt-3">
{comments?.map((c:Comment)=>(
<divkey={c.id}className="flexgap-2text-sm">
<AvatarclassName="size-6shrink-0">
<AvatarFallbackclassName="text-[10px]">
<TelescopeclassName="size-3"/>
</AvatarFallback>
</Avatar>
<divclassName="rounded-lgbg-mutedpx-3py-2">
<pclassName="mb-0.5text-xsfont-mediumtext-muted-foreground">Astronome</p>
<p>{c.content}</p>
</div>
</div>
))}

{user&&(
<divclassName="flexgap-2">
<AvatarclassName="size-6shrink-0">
<AvatarFallbackclassName="text-[10px]">
<TelescopeclassName="size-3"/>
</AvatarFallback>
</Avatar>
<divclassName="flexflex-1gap-2">
<Input
value={commentText}
onChange={(e)=>setCommentText(e.target.value)}
placeholder="Votrecommentaire"
className="h-8text-sm"
onKeyDown={(e)=>{
if(e.key==="Enter"&&!e.shiftKey&&commentText.trim()){
e.preventDefault();
commentMutation.mutate(commentText.trim());
}
}}
/>
<Button
size="sm"
className="size-8shrink-0p-0"
disabled={!commentText.trim()||commentMutation.isPending}
onClick={()=>commentMutation.mutate(commentText.trim())}
>
<SendclassName="size-3.5"/>
</Button>
</div>
</div>
)}
</div>
)}
</CardContent>
</Card>
);
}

exportfunctionSocialFeed(){
const{user}=useAuth();
constqueryClient=useQueryClient();
const[newPost,setNewPost]=useState("");

const{data:posts,isLoading}=useQuery({
queryKey:["social-feed"],
queryFn:async()=>{
if(!user){
const{data,error}=awaitsupabase
.from("posts")
.select(
"id,user_id,content,object_id,object_name,image_ids,likes_count,comments_count,shares_count,created_at",
)
.order("created_at",{ascending:false})
.limit(30);
if(error)throwerror;
return(data??[]).map((p)=>({
post_id:p.id,
author_id:p.user_id,
display_name:null,
avatar_url:null,
content:p.content,
object_id:p.object_id,
object_name:p.object_name,
image_ids:p.image_ids,
likes_count:p.likes_count,
comments_count:p.comments_count,
shares_count:p.shares_count,
created_at:p.created_at,
user_liked:false,
}))asFeedPost[];
}

const{data,error}=awaitsupabase.rpc("get_user_feed",{
p_user_id:user.id,
p_limit:30,
p_offset:0,
});
if(error)throwerror;
return(data??[])asFeedPost[];
},
refetchInterval:60_000,
});

constcreatePostMutation=useMutation({
mutationFn:async(content:string)=>{
if(!user)thrownewError("Nonauthentifi");
const{error}=awaitsupabase.from("posts").insert({user_id:user.id,content});
if(error)throwerror;
},
onSuccess:()=>{
setNewPost("");
queryClient.invalidateQueries({queryKey:["social-feed"]});
toast.success("Publicationpartage!");
},
onError:()=>toast.error("Impossibledepublier."),
});

return(
<divclassName="space-y-4">
{user&&(
<Card>
<CardContentclassName="space-y-3pt-4">
<Textarea
placeholder="Partagezvotredernireobservation,unequestion,unedcouverte"
value={newPost}
onChange={(e)=>setNewPost(e.target.value)}
rows={3}
className="resize-none"
/>
<divclassName="flexjustify-end">
<Button
onClick={()=>createPostMutation.mutate(newPost.trim())}
disabled={!newPost.trim()||createPostMutation.isPending}
size="sm"
>
Publier
</Button>
</div>
</CardContent>
</Card>
)}

{!user&&(
<Card>
<CardContentclassName="py-6text-centertext-smtext-muted-foreground">
<Linkto="/auth"className="text-primaryunderline">
Connectez-vous
</Link>{""}
pourpublieretinteragiraveclacommunaut.
</CardContent>
</Card>
)}

{isLoading?(
<divclassName="flexjustify-centerpy-12">
<spanclassName="text-smtext-muted-foreground">Chargementdufil</span>
</div>
):posts?.length===0?(
<Card>
<CardContentclassName="py-12text-centertext-smtext-muted-foreground">
Aucunepublicationpourlemoment.Soyezlepremierpartageruneobservation!
</CardContent>
</Card>
):(
posts?.map((post:FeedPost)=><PostCardkey={post.post_id}post={post}/>)
)}
</div>
);
}
