import{useQuery,useMutation,useQueryClient}from"@tanstack/react-query";
import{Telescope,MapPin,UserPlus,UserMinus,Settings}from"lucide-react";
import{supabase}from"@/integrations/supabase/client";
import{Card,CardContent}from"@/components/ui/card";
import{Button}from"@/components/ui/button";
import{Avatar,AvatarFallback,AvatarImage}from"@/components/ui/avatar";
import{toast}from"sonner";
import{useAuth}from"@/hooks/useAuth";
import{Link}from"@tanstack/react-router";

interfaceProfile{
id:string;
display_name:string|null;
avatar_url:string|null;
bio:string|null;
location:string|null;
followers_count:number;
following_count:number;
posts_count:number;
}

exportfunctionUserProfile({userId}:{userId:string}){
const{user}=useAuth();
constqueryClient=useQueryClient();
constisOwnProfile=user?.id===userId;

const{data:profile,isLoading}=useQuery({
queryKey:["profile",userId],
queryFn:async()=>{
const{data,error}=awaitsupabase
.from("profiles")
.select(
"id,display_name,avatar_url,bio,location,followers_count,following_count,posts_count",
)
.eq("id",userId)
.single();
if(error)throwerror;
returndataasProfile;
},
});

const{data:isFollowing}=useQuery({
queryKey:["is-following",user?.id,userId],
queryFn:async()=>{
if(!user)returnfalse;
const{data}=awaitsupabase
.from("follows")
.select("id")
.eq("follower_id",user.id)
.eq("following_id",userId)
.maybeSingle();
return!!data;
},
enabled:!!user&&!isOwnProfile,
});

constfollowMutation=useMutation({
mutationFn:async()=>{
if(!user)thrownewError("Nonauthentifi");
if(isFollowing){
awaitsupabase
.from("follows")
.delete()
.eq("follower_id",user.id)
.eq("following_id",userId);
}else{
awaitsupabase.from("follows").insert({follower_id:user.id,following_id:userId});
}
},
onSuccess:()=>{
queryClient.invalidateQueries({queryKey:["is-following"]});
queryClient.invalidateQueries({queryKey:["profile",userId]});
toast.success(isFollowing?"Abonnementannul.":"Voussuivezcetastronome!");
},
onError:()=>toast.error("Actionimpossible."),
});

if(isLoading){
return(
<Card>
<CardContentclassName="py-12text-centertext-smtext-muted-foreground">
Chargementduprofil
</CardContent>
</Card>
);
}

if(!profile){
return(
<Card>
<CardContentclassName="py-12text-centertext-smtext-muted-foreground">
Profilintrouvable.
</CardContent>
</Card>
);
}

return(
<Card>
<CardContentclassName="pt-6">
<divclassName="flexitems-startgap-4">
<AvatarclassName="size-16shrink-0">
<AvatarImagesrc={profile.avatar_url??undefined}/>
<AvatarFallbackclassName="text-lg">
<TelescopeclassName="size-7"/>
</AvatarFallback>
</Avatar>

<divclassName="min-w-0flex-1">
<divclassName="flexflex-wrapitems-centerjustify-betweengap-2">
<h2className="truncatetext-lgfont-semibold">
{profile.display_name??"Astronome"}
</h2>

{isOwnProfile?(
<Buttonvariant="outline"size="sm"className="gap-1.5"asChild>
<Linkto="/auth">
<SettingsclassName="size-3.5"/>
Modifier
</Link>
</Button>
):user?(
<Button
size="sm"
variant={isFollowing?"outline":"default"}
className="gap-1.5"
onClick={()=>followMutation.mutate()}
disabled={followMutation.isPending}
>
{isFollowing?(
<>
<UserMinusclassName="size-3.5"/>
Neplussuivre
</>
):(
<>
<UserPlusclassName="size-3.5"/>
Suivre
</>
)}
</Button>
):null}
</div>

{profile.location&&(
<pclassName="mt-1flexitems-centergap-1text-xstext-muted-foreground">
<MapPinclassName="size-3"/>
{profile.location}
</p>
)}

{profile.bio&&(
<pclassName="mt-2text-smleading-relaxedtext-muted-foreground">{profile.bio}</p>
)}

<divclassName="mt-3flexgap-4">
<divclassName="text-center">
<pclassName="tabular-numstext-lgfont-bold">{profile.posts_count}</p>
<pclassName="text-xstext-muted-foreground">Publications</p>
</div>
<divclassName="text-center">
<pclassName="tabular-numstext-lgfont-bold">{profile.followers_count}</p>
<pclassName="text-xstext-muted-foreground">Abonns</p>
</div>
<divclassName="text-center">
<pclassName="tabular-numstext-lgfont-bold">{profile.following_count}</p>
<pclassName="text-xstext-muted-foreground">Abonnements</p>
</div>
</div>
</div>
</div>
</CardContent>
</Card>
);
}
