/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AstrostackRouteImport } from './routes/astrostack'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as CosmosLiveRouteImport } from './routes/cosmos-live'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as MosaicRouteImport } from './routes/mosaic'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProfilUserIdRouteImport } from './routes/profil.$userId'
import { Route as RessourcesIndexRouteImport } from './routes/ressources.index'
import { Route as RessourcesCommunauteRouteImport } from './routes/ressources.communaute'
import { Route as RessourcesLogicielsRouteImport } from './routes/ressources.logiciels'
import { Route as RessourcesPlanificationRouteImport } from './routes/ressources.planification'
import { Route as RessourcesTutorielsRouteImport } from './routes/ressources.tutoriels'
import { Route as RessourcesVideosRouteImport } from './routes/ressources.videos'
import { Route as ApiAstrostackQualifyRouteImport } from './routes/api/astrostack/qualify'
import { Route as ApiAstrostackStackTriggerRouteImport } from './routes/api/astrostack/stack-trigger'
import { Route as ApiAstrostackStatusRouteImport } from './routes/api/astrostack/status'
import { Route as ApiAstrostackUploadRouteImport } from './routes/api/astrostack/upload'
import { Route as ApiCosmosAnalyzeClusterRouteImport } from './routes/api/cosmos/analyze-cluster'
import { Route as ApiCosmosFeedRouteImport } from './routes/api/cosmos/feed'
import { Route as ApiCosmosReportRouteImport } from './routes/api/cosmos/report'
import { Route as ApiMosaicCellsRouteImport } from './routes/api/mosaic/cells'
import { Route as ApiMosaicJobsRouteImport } from './routes/api/mosaic/jobs'
import { Route as ApiMosaicStatsRouteImport } from './routes/api/mosaic/stats'
import { Route as ApiVisionAnalyzeRouteImport } from './routes/api/vision/analyze'
import { Route as ApiVisionCompareRouteImport } from './routes/api/vision/compare'
import { Route as RessourcesMaterielIndexRouteImport } from './routes/ressources.materiel.index'
import { Route as RessourcesMaterielSlugRouteImport } from './routes/ressources.materiel.$slug'
import { Route as ApiMosaicHipsSplatRouteImport } from './routes/api/mosaic/hips/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrostackRoute = AstrostackRouteImport.update({
  id: '/astrostack',
  path: '/astrostack',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmosLiveRoute = CosmosLiveRouteImport.update({
  id: '/cosmos-live',
  path: '/cosmos-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const MosaicRoute = MosaicRouteImport.update({
  id: '/mosaic',
  path: '/mosaic',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilUserIdRoute = ProfilUserIdRouteImport.update({
  id: '/profil/$userId',
  path: '/profil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesCommunauteRoute = RessourcesCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesLogicielsRoute = RessourcesLogicielsRouteImport.update({
  id: '/logiciels',
  path: '/logiciels',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesPlanificationRoute = RessourcesPlanificationRouteImport.update({
  id: '/planification',
  path: '/planification',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesTutorielsRoute = RessourcesTutorielsRouteImport.update({
  id: '/tutoriels',
  path: '/tutoriels',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesVideosRoute = RessourcesVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => RessourcesRoute,
} as any)
const ApiAstrostackQualifyRoute = ApiAstrostackQualifyRouteImport.update({
  id: '/api/astrostack/qualify',
  path: '/api/astrostack/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstrostackStackTriggerRoute =
  ApiAstrostackStackTriggerRouteImport.update({
    id: '/api/astrostack/stack-trigger',
    path: '/api/astrostack/stack-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAstrostackStatusRoute = ApiAstrostackStatusRouteImport.update({
  id: '/api/astrostack/status',
  path: '/api/astrostack/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstrostackUploadRoute = ApiAstrostackUploadRouteImport.update({
  id: '/api/astrostack/upload',
  path: '/api/astrostack/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCosmosAnalyzeClusterRoute = ApiCosmosAnalyzeClusterRouteImport.update({
  id: '/api/cosmos/analyze-cluster',
  path: '/api/cosmos/analyze-cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCosmosFeedRoute = ApiCosmosFeedRouteImport.update({
  id: '/api/cosmos/feed',
  path: '/api/cosmos/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCosmosReportRoute = ApiCosmosReportRouteImport.update({
  id: '/api/cosmos/report',
  path: '/api/cosmos/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMosaicCellsRoute = ApiMosaicCellsRouteImport.update({
  id: '/api/mosaic/cells',
  path: '/api/mosaic/cells',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMosaicJobsRoute = ApiMosaicJobsRouteImport.update({
  id: '/api/mosaic/jobs',
  path: '/api/mosaic/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMosaicStatsRoute = ApiMosaicStatsRouteImport.update({
  id: '/api/mosaic/stats',
  path: '/api/mosaic/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionAnalyzeRoute = ApiVisionAnalyzeRouteImport.update({
  id: '/api/vision/analyze',
  path: '/api/vision/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionCompareRoute = ApiVisionCompareRouteImport.update({
  id: '/api/vision/compare',
  path: '/api/vision/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesMaterielIndexRoute = RessourcesMaterielIndexRouteImport.update({
  id: '/materiel/',
  path: '/materiel/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesMaterielSlugRoute = RessourcesMaterielSlugRouteImport.update({
  id: '/materiel/$slug',
  path: '/materiel/$slug',
  getParentRoute: () => RessourcesRoute,
} as any)
const ApiMosaicHipsSplatRoute = ApiMosaicHipsSplatRouteImport.update({
  id: '/api/mosaic/hips/$',
  path: '/api/mosaic/hips/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/astrostack': typeof AstrostackRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/cosmos-live': typeof CosmosLiveRoute
  '/explorer': typeof ExplorerRoute
  '/mosaic': typeof MosaicRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/api/astrostack/qualify': typeof ApiAstrostackQualifyRoute
  '/api/astrostack/stack-trigger': typeof ApiAstrostackStackTriggerRoute
  '/api/astrostack/status': typeof ApiAstrostackStatusRoute
  '/api/astrostack/upload': typeof ApiAstrostackUploadRoute
  '/api/cosmos/analyze-cluster': typeof ApiCosmosAnalyzeClusterRoute
  '/api/cosmos/feed': typeof ApiCosmosFeedRoute
  '/api/cosmos/report': typeof ApiCosmosReportRoute
  '/api/mosaic/cells': typeof ApiMosaicCellsRoute
  '/api/mosaic/jobs': typeof ApiMosaicJobsRoute
  '/api/mosaic/stats': typeof ApiMosaicStatsRoute
  '/api/vision/analyze': typeof ApiVisionAnalyzeRoute
  '/api/vision/compare': typeof ApiVisionCompareRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel/': typeof RessourcesMaterielIndexRoute
  '/api/mosaic/hips/$': typeof ApiMosaicHipsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/astrostack': typeof AstrostackRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/cosmos-live': typeof CosmosLiveRoute
  '/explorer': typeof ExplorerRoute
  '/mosaic': typeof MosaicRoute
  '/api/chat': typeof ApiChatRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources': typeof RessourcesIndexRoute
  '/api/astrostack/qualify': typeof ApiAstrostackQualifyRoute
  '/api/astrostack/stack-trigger': typeof ApiAstrostackStackTriggerRoute
  '/api/astrostack/status': typeof ApiAstrostackStatusRoute
  '/api/astrostack/upload': typeof ApiAstrostackUploadRoute
  '/api/cosmos/analyze-cluster': typeof ApiCosmosAnalyzeClusterRoute
  '/api/cosmos/feed': typeof ApiCosmosFeedRoute
  '/api/cosmos/report': typeof ApiCosmosReportRoute
  '/api/mosaic/cells': typeof ApiMosaicCellsRoute
  '/api/mosaic/jobs': typeof ApiMosaicJobsRoute
  '/api/mosaic/stats': typeof ApiMosaicStatsRoute
  '/api/vision/analyze': typeof ApiVisionAnalyzeRoute
  '/api/vision/compare': typeof ApiVisionCompareRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel': typeof RessourcesMaterielIndexRoute
  '/api/mosaic/hips/$': typeof ApiMosaicHipsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/astrostack': typeof AstrostackRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/cosmos-live': typeof CosmosLiveRoute
  '/explorer': typeof ExplorerRoute
  '/mosaic': typeof MosaicRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/api/astrostack/qualify': typeof ApiAstrostackQualifyRoute
  '/api/astrostack/stack-trigger': typeof ApiAstrostackStackTriggerRoute
  '/api/astrostack/status': typeof ApiAstrostackStatusRoute
  '/api/astrostack/upload': typeof ApiAstrostackUploadRoute
  '/api/cosmos/analyze-cluster': typeof ApiCosmosAnalyzeClusterRoute
  '/api/cosmos/feed': typeof ApiCosmosFeedRoute
  '/api/cosmos/report': typeof ApiCosmosReportRoute
  '/api/mosaic/cells': typeof ApiMosaicCellsRoute
  '/api/mosaic/jobs': typeof ApiMosaicJobsRoute
  '/api/mosaic/stats': typeof ApiMosaicStatsRoute
  '/api/vision/analyze': typeof ApiVisionAnalyzeRoute
  '/api/vision/compare': typeof ApiVisionCompareRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel/': typeof RessourcesMaterielIndexRoute
  '/api/mosaic/hips/$': typeof ApiMosaicHipsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/astrostack'
    | '/auth'
    | '/communaute'
    | '/cosmos-live'
    | '/explorer'
    | '/mosaic'
    | '/ressources'
    | '/api/chat'
    | '/profil/$userId'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources/'
    | '/api/astrostack/qualify'
    | '/api/astrostack/stack-trigger'
    | '/api/astrostack/status'
    | '/api/astrostack/upload'
    | '/api/cosmos/analyze-cluster'
    | '/api/cosmos/feed'
    | '/api/cosmos/report'
    | '/api/mosaic/cells'
    | '/api/mosaic/jobs'
    | '/api/mosaic/stats'
    | '/api/vision/analyze'
    | '/api/vision/compare'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel/'
    | '/api/mosaic/hips/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/astrostack'
    | '/auth'
    | '/communaute'
    | '/cosmos-live'
    | '/explorer'
    | '/mosaic'
    | '/api/chat'
    | '/profil/$userId'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources'
    | '/api/astrostack/qualify'
    | '/api/astrostack/stack-trigger'
    | '/api/astrostack/status'
    | '/api/astrostack/upload'
    | '/api/cosmos/analyze-cluster'
    | '/api/cosmos/feed'
    | '/api/cosmos/report'
    | '/api/mosaic/cells'
    | '/api/mosaic/jobs'
    | '/api/mosaic/stats'
    | '/api/vision/analyze'
    | '/api/vision/compare'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel'
    | '/api/mosaic/hips/$'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/astrostack'
    | '/auth'
    | '/communaute'
    | '/cosmos-live'
    | '/explorer'
    | '/mosaic'
    | '/ressources'
    | '/api/chat'
    | '/profil/$userId'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources/'
    | '/api/astrostack/qualify'
    | '/api/astrostack/stack-trigger'
    | '/api/astrostack/status'
    | '/api/astrostack/upload'
    | '/api/cosmos/analyze-cluster'
    | '/api/cosmos/feed'
    | '/api/cosmos/report'
    | '/api/mosaic/cells'
    | '/api/mosaic/jobs'
    | '/api/mosaic/stats'
    | '/api/vision/analyze'
    | '/api/vision/compare'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel/'
    | '/api/mosaic/hips/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AstrostackRoute: typeof AstrostackRoute
  AuthRoute: typeof AuthRoute
  CommunauteRoute: typeof CommunauteRoute
  CosmosLiveRoute: typeof CosmosLiveRoute
  ExplorerRoute: typeof ExplorerRoute
  MosaicRoute: typeof MosaicRoute
  RessourcesRoute: typeof RessourcesRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ProfilUserIdRoute: typeof ProfilUserIdRoute
  ApiAstrostackQualifyRoute: typeof ApiAstrostackQualifyRoute
  ApiAstrostackStackTriggerRoute: typeof ApiAstrostackStackTriggerRoute
  ApiAstrostackStatusRoute: typeof ApiAstrostackStatusRoute
  ApiAstrostackUploadRoute: typeof ApiAstrostackUploadRoute
  ApiCosmosAnalyzeClusterRoute: typeof ApiCosmosAnalyzeClusterRoute
  ApiCosmosFeedRoute: typeof ApiCosmosFeedRoute
  ApiCosmosReportRoute: typeof ApiCosmosReportRoute
  ApiMosaicCellsRoute: typeof ApiMosaicCellsRoute
  ApiMosaicJobsRoute: typeof ApiMosaicJobsRoute
  ApiMosaicStatsRoute: typeof ApiMosaicStatsRoute
  ApiVisionAnalyzeRoute: typeof ApiVisionAnalyzeRoute
  ApiVisionCompareRoute: typeof ApiVisionCompareRoute
  ApiMosaicHipsSplatRoute: typeof ApiMosaicHipsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrostack': {
      id: '/astrostack'
      path: '/astrostack'
      fullPath: '/astrostack'
      preLoaderRoute: typeof AstrostackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmos-live': {
      id: '/cosmos-live'
      path: '/cosmos-live'
      fullPath: '/cosmos-live'
      preLoaderRoute: typeof CosmosLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosaic': {
      id: '/mosaic'
      path: '/mosaic'
      fullPath: '/mosaic'
      preLoaderRoute: typeof MosaicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$userId': {
      id: '/profil/$userId'
      path: '/profil/$userId'
      fullPath: '/profil/$userId'
      preLoaderRoute: typeof ProfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/communaute': {
      id: '/ressources/communaute'
      path: '/communaute'
      fullPath: '/ressources/communaute'
      preLoaderRoute: typeof RessourcesCommunauteRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/logiciels': {
      id: '/ressources/logiciels'
      path: '/logiciels'
      fullPath: '/ressources/logiciels'
      preLoaderRoute: typeof RessourcesLogicielsRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/planification': {
      id: '/ressources/planification'
      path: '/planification'
      fullPath: '/ressources/planification'
      preLoaderRoute: typeof RessourcesPlanificationRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/tutoriels': {
      id: '/ressources/tutoriels'
      path: '/tutoriels'
      fullPath: '/ressources/tutoriels'
      preLoaderRoute: typeof RessourcesTutorielsRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/videos': {
      id: '/ressources/videos'
      path: '/videos'
      fullPath: '/ressources/videos'
      preLoaderRoute: typeof RessourcesVideosRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/api/astrostack/qualify': {
      id: '/api/astrostack/qualify'
      path: '/api/astrostack/qualify'
      fullPath: '/api/astrostack/qualify'
      preLoaderRoute: typeof ApiAstrostackQualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astrostack/stack-trigger': {
      id: '/api/astrostack/stack-trigger'
      path: '/api/astrostack/stack-trigger'
      fullPath: '/api/astrostack/stack-trigger'
      preLoaderRoute: typeof ApiAstrostackStackTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astrostack/status': {
      id: '/api/astrostack/status'
      path: '/api/astrostack/status'
      fullPath: '/api/astrostack/status'
      preLoaderRoute: typeof ApiAstrostackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astrostack/upload': {
      id: '/api/astrostack/upload'
      path: '/api/astrostack/upload'
      fullPath: '/api/astrostack/upload'
      preLoaderRoute: typeof ApiAstrostackUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cosmos/analyze-cluster': {
      id: '/api/cosmos/analyze-cluster'
      path: '/api/cosmos/analyze-cluster'
      fullPath: '/api/cosmos/analyze-cluster'
      preLoaderRoute: typeof ApiCosmosAnalyzeClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cosmos/feed': {
      id: '/api/cosmos/feed'
      path: '/api/cosmos/feed'
      fullPath: '/api/cosmos/feed'
      preLoaderRoute: typeof ApiCosmosFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cosmos/report': {
      id: '/api/cosmos/report'
      path: '/api/cosmos/report'
      fullPath: '/api/cosmos/report'
      preLoaderRoute: typeof ApiCosmosReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mosaic/cells': {
      id: '/api/mosaic/cells'
      path: '/api/mosaic/cells'
      fullPath: '/api/mosaic/cells'
      preLoaderRoute: typeof ApiMosaicCellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mosaic/jobs': {
      id: '/api/mosaic/jobs'
      path: '/api/mosaic/jobs'
      fullPath: '/api/mosaic/jobs'
      preLoaderRoute: typeof ApiMosaicJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mosaic/stats': {
      id: '/api/mosaic/stats'
      path: '/api/mosaic/stats'
      fullPath: '/api/mosaic/stats'
      preLoaderRoute: typeof ApiMosaicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/analyze': {
      id: '/api/vision/analyze'
      path: '/api/vision/analyze'
      fullPath: '/api/vision/analyze'
      preLoaderRoute: typeof ApiVisionAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/compare': {
      id: '/api/vision/compare'
      path: '/api/vision/compare'
      fullPath: '/api/vision/compare'
      preLoaderRoute: typeof ApiVisionCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/materiel/': {
      id: '/ressources/materiel/'
      path: '/materiel'
      fullPath: '/ressources/materiel/'
      preLoaderRoute: typeof RessourcesMaterielIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/materiel/$slug': {
      id: '/ressources/materiel/$slug'
      path: '/materiel/$slug'
      fullPath: '/ressources/materiel/$slug'
      preLoaderRoute: typeof RessourcesMaterielSlugRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/api/mosaic/hips/$': {
      id: '/api/mosaic/hips/$'
      path: '/api/mosaic/hips/$'
      fullPath: '/api/mosaic/hips/$'
      preLoaderRoute: typeof ApiMosaicHipsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RessourcesRouteChildren {
  RessourcesCommunauteRoute: typeof RessourcesCommunauteRoute
  RessourcesLogicielsRoute: typeof RessourcesLogicielsRoute
  RessourcesPlanificationRoute: typeof RessourcesPlanificationRoute
  RessourcesTutorielsRoute: typeof RessourcesTutorielsRoute
  RessourcesVideosRoute: typeof RessourcesVideosRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
  RessourcesMaterielSlugRoute: typeof RessourcesMaterielSlugRoute
  RessourcesMaterielIndexRoute: typeof RessourcesMaterielIndexRoute
}

const RessourcesRouteChildren: RessourcesRouteChildren = {
  RessourcesCommunauteRoute: RessourcesCommunauteRoute,
  RessourcesLogicielsRoute: RessourcesLogicielsRoute,
  RessourcesPlanificationRoute: RessourcesPlanificationRoute,
  RessourcesTutorielsRoute: RessourcesTutorielsRoute,
  RessourcesVideosRoute: RessourcesVideosRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
  RessourcesMaterielSlugRoute: RessourcesMaterielSlugRoute,
  RessourcesMaterielIndexRoute: RessourcesMaterielIndexRoute,
}

const RessourcesRouteWithChildren = RessourcesRoute._addFileChildren(
  RessourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AstrostackRoute: AstrostackRoute,
  AuthRoute: AuthRoute,
  CommunauteRoute: CommunauteRoute,
  CosmosLiveRoute: CosmosLiveRoute,
  ExplorerRoute: ExplorerRoute,
  MosaicRoute: MosaicRoute,
  RessourcesRoute: RessourcesRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ProfilUserIdRoute: ProfilUserIdRoute,
  ApiAstrostackQualifyRoute: ApiAstrostackQualifyRoute,
  ApiAstrostackStackTriggerRoute: ApiAstrostackStackTriggerRoute,
  ApiAstrostackStatusRoute: ApiAstrostackStatusRoute,
  ApiAstrostackUploadRoute: ApiAstrostackUploadRoute,
  ApiCosmosAnalyzeClusterRoute: ApiCosmosAnalyzeClusterRoute,
  ApiCosmosFeedRoute: ApiCosmosFeedRoute,
  ApiCosmosReportRoute: ApiCosmosReportRoute,
  ApiMosaicCellsRoute: ApiMosaicCellsRoute,
  ApiMosaicJobsRoute: ApiMosaicJobsRoute,
  ApiMosaicStatsRoute: ApiMosaicStatsRoute,
  ApiVisionAnalyzeRoute: ApiVisionAnalyzeRoute,
  ApiVisionCompareRoute: ApiVisionCompareRoute,
  ApiMosaicHipsSplatRoute: ApiMosaicHipsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
