/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as RessourcesIndexRouteImport } from './routes/ressources.index'
import { Route as RessourcesCommunauteRouteImport } from './routes/ressources.communaute'
import { Route as RessourcesLogicielsRouteImport } from './routes/ressources.logiciels'
import { Route as RessourcesPlanificationRouteImport } from './routes/ressources.planification'
import { Route as RessourcesTutorielsRouteImport } from './routes/ressources.tutoriels'
import { Route as RessourcesVideosRouteImport } from './routes/ressources.videos'
import { Route as RessourcesMaterielIndexRouteImport } from './routes/ressources.materiel.index'
import { Route as RessourcesMaterielSlugRouteImport } from './routes/ressources.materiel.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesCommunauteRoute = RessourcesCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesLogicielsRoute = RessourcesLogicielsRouteImport.update({
  id: '/logiciels',
  path: '/logiciels',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesPlanificationRoute = RessourcesPlanificationRouteImport.update({
  id: '/planification',
  path: '/planification',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesTutorielsRoute = RessourcesTutorielsRouteImport.update({
  id: '/tutoriels',
  path: '/tutoriels',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesVideosRoute = RessourcesVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesMaterielIndexRoute = RessourcesMaterielIndexRouteImport.update({
  id: '/materiel/',
  path: '/materiel/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesMaterielSlugRoute = RessourcesMaterielSlugRouteImport.update({
  id: '/materiel/$slug',
  path: '/materiel/$slug',
  getParentRoute: () => RessourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel/': typeof RessourcesMaterielIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/api/chat': typeof ApiChatRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources': typeof RessourcesIndexRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel': typeof RessourcesMaterielIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/ressources/communaute': typeof RessourcesCommunauteRoute
  '/ressources/logiciels': typeof RessourcesLogicielsRoute
  '/ressources/planification': typeof RessourcesPlanificationRoute
  '/ressources/tutoriels': typeof RessourcesTutorielsRoute
  '/ressources/videos': typeof RessourcesVideosRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/ressources/materiel/$slug': typeof RessourcesMaterielSlugRoute
  '/ressources/materiel/': typeof RessourcesMaterielIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/explorer'
    | '/ressources'
    | '/api/chat'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources/'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/explorer'
    | '/api/chat'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/explorer'
    | '/ressources'
    | '/api/chat'
    | '/ressources/communaute'
    | '/ressources/logiciels'
    | '/ressources/planification'
    | '/ressources/tutoriels'
    | '/ressources/videos'
    | '/ressources/'
    | '/ressources/materiel/$slug'
    | '/ressources/materiel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  RessourcesRoute: typeof RessourcesRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/communaute': {
      id: '/ressources/communaute'
      path: '/communaute'
      fullPath: '/ressources/communaute'
      preLoaderRoute: typeof RessourcesCommunauteRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/logiciels': {
      id: '/ressources/logiciels'
      path: '/logiciels'
      fullPath: '/ressources/logiciels'
      preLoaderRoute: typeof RessourcesLogicielsRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/planification': {
      id: '/ressources/planification'
      path: '/planification'
      fullPath: '/ressources/planification'
      preLoaderRoute: typeof RessourcesPlanificationRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/tutoriels': {
      id: '/ressources/tutoriels'
      path: '/tutoriels'
      fullPath: '/ressources/tutoriels'
      preLoaderRoute: typeof RessourcesTutorielsRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/videos': {
      id: '/ressources/videos'
      path: '/videos'
      fullPath: '/ressources/videos'
      preLoaderRoute: typeof RessourcesVideosRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/materiel/': {
      id: '/ressources/materiel/'
      path: '/materiel'
      fullPath: '/ressources/materiel/'
      preLoaderRoute: typeof RessourcesMaterielIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/materiel/$slug': {
      id: '/ressources/materiel/$slug'
      path: '/materiel/$slug'
      fullPath: '/ressources/materiel/$slug'
      preLoaderRoute: typeof RessourcesMaterielSlugRouteImport
      parentRoute: typeof RessourcesRoute
    }
  }
}

interface RessourcesRouteChildren {
  RessourcesCommunauteRoute: typeof RessourcesCommunauteRoute
  RessourcesLogicielsRoute: typeof RessourcesLogicielsRoute
  RessourcesPlanificationRoute: typeof RessourcesPlanificationRoute
  RessourcesTutorielsRoute: typeof RessourcesTutorielsRoute
  RessourcesVideosRoute: typeof RessourcesVideosRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
  RessourcesMaterielSlugRoute: typeof RessourcesMaterielSlugRoute
  RessourcesMaterielIndexRoute: typeof RessourcesMaterielIndexRoute
}

const RessourcesRouteChildren: RessourcesRouteChildren = {
  RessourcesCommunauteRoute: RessourcesCommunauteRoute,
  RessourcesLogicielsRoute: RessourcesLogicielsRoute,
  RessourcesPlanificationRoute: RessourcesPlanificationRoute,
  RessourcesTutorielsRoute: RessourcesTutorielsRoute,
  RessourcesVideosRoute: RessourcesVideosRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
  RessourcesMaterielSlugRoute: RessourcesMaterielSlugRoute,
  RessourcesMaterielIndexRoute: RessourcesMaterielIndexRoute,
}

const RessourcesRouteWithChildren = RessourcesRoute._addFileChildren(
  RessourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ExplorerRoute: ExplorerRoute,
  RessourcesRoute: RessourcesRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
