CREATETABLEpublic.profiles(
iduuidPRIMARYKEYREFERENCESauth.usersONDELETECASCADE,
display_nametext,
created_attimestamptzNOTNULLDEFAULTnow(),
updated_attimestamptzNOTNULLDEFAULTnow()
);
GRANTSELECT,INSERT,UPDATE,DELETEONpublic.profilesTOauthenticated;
GRANTALLONpublic.profilesTOservice_role;
ALTERTABLEpublic.profilesENABLEROWLEVELSECURITY;
CREATEPOLICY"ownprofile"ONpublic.profilesFORALLTOauthenticatedUSING(auth.uid()=id)WITHCHECK(auth.uid()=id);

CREATETABLEpublic.saved_locations(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidNOTNULLREFERENCESauth.usersONDELETECASCADE,
nametextNOTNULL,
latitudedoubleprecisionNOTNULL,
longitudedoubleprecisionNOTNULL,
is_defaultbooleanNOTNULLDEFAULTfalse,
created_attimestamptzNOTNULLDEFAULTnow()
);
GRANTSELECT,INSERT,UPDATE,DELETEONpublic.saved_locationsTOauthenticated;
GRANTALLONpublic.saved_locationsTOservice_role;
ALTERTABLEpublic.saved_locationsENABLEROWLEVELSECURITY;
CREATEPOLICY"ownlocations"ONpublic.saved_locationsFORALLTOauthenticatedUSING(auth.uid()=user_id)WITHCHECK(auth.uid()=user_id);

CREATETABLEpublic.favorites(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidNOTNULLREFERENCESauth.usersONDELETECASCADE,
object_idtextNOTNULL,
created_attimestamptzNOTNULLDEFAULTnow(),
UNIQUE(user_id,object_id)
);
GRANTSELECT,INSERT,UPDATE,DELETEONpublic.favoritesTOauthenticated;
GRANTALLONpublic.favoritesTOservice_role;
ALTERTABLEpublic.favoritesENABLEROWLEVELSECURITY;
CREATEPOLICY"ownfavorites"ONpublic.favoritesFORALLTOauthenticatedUSING(auth.uid()=user_id)WITHCHECK(auth.uid()=user_id);

CREATETABLEpublic.observations(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidNOTNULLREFERENCESauth.usersONDELETECASCADE,
object_idtextNOTNULL,
object_nametextNOTNULL,
observed_attimestamptzNOTNULLDEFAULTnow(),
instrumenttext,
notestext,
created_attimestamptzNOTNULLDEFAULTnow()
);
GRANTSELECT,INSERT,UPDATE,DELETEONpublic.observationsTOauthenticated;
GRANTALLONpublic.observationsTOservice_role;
ALTERTABLEpublic.observationsENABLEROWLEVELSECURITY;
CREATEPOLICY"ownobservations"ONpublic.observationsFORALLTOauthenticatedUSING(auth.uid()=user_id)WITHCHECK(auth.uid()=user_id);

CREATEORREPLACEFUNCTIONpublic.handle_new_user()
RETURNStrigger
LANGUAGEplpgsql
SECURITYDEFINER
SETsearch_path=public
AS$$
BEGIN
INSERTINTOpublic.profiles(id,display_name)
VALUES(NEW.id,COALESCE(NEW.raw_user_meta_data->>'display_name',NEW.raw_user_meta_data->>'full_name',split_part(NEW.email,'@',1)))
ONCONFLICT(id)DONOTHING;
RETURNNEW;
END;
$$;

CREATETRIGGERon_auth_user_created
AFTERINSERTONauth.users
FOREACHROWEXECUTEFUNCTIONpublic.handle_new_user();