--============================================================
--COSMOSLIVE—Observatoirecollaboratifentempsréel
--============================================================

--Tabledesobservationsentempsréelsoumisesparlesutilisateurs
CREATETABLEpublic.cosmos_observations(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidREFERENCESauth.usersONDELETESETNULL,
--Géolocalisationdel'observateur
latitudedoubleprecisionNOTNULL,
longitudedoubleprecisionNOTNULL,
altitude_mdoubleprecisionDEFAULT0,
--Directiond'observation(azimut/élévationendegrés)
azimuthdoubleprecision,
elevationdoubleprecision,
--Catégorieduphénomèneobservé
phenomenon_typetextNOTNULLCHECK(phenomenon_typeIN(
'meteor','fireball','comet','supernova','aurora',
'satellite','atmospheric','unknown'
)),
--Descriptionlibre+métadonnéesAI
descriptiontextNOTNULL,
image_urltext,
--Duréeestiméeensecondes
duration_sdoubleprecision,
--Magnitudeestimée
magnitudedoubleprecision,
--Scoredeconfianceattribuéparl'IA(0-1)
ai_confidencedoubleprecisionDEFAULT0,
ai_analysisjsonb,
--Statutdetraitement
statustextDEFAULT'pending'CHECK(statusIN('pending','clustered','triangulated','published','rejected')),
--Référenceàl'événementregroupé(siclustérisé)
event_iduuid,
observed_attimestamptzNOTNULLDEFAULTnow(),
created_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_cosmos_obs_userONpublic.cosmos_observations(user_id);
CREATEINDEXidx_cosmos_obs_typeONpublic.cosmos_observations(phenomenon_type);
CREATEINDEXidx_cosmos_obs_observed_atONpublic.cosmos_observations(observed_atDESC);
CREATEINDEXidx_cosmos_obs_eventONpublic.cosmos_observations(event_id)WHEREevent_idISNOTNULL;
--Indexgéographiqueviacolonneslat/lon
CREATEINDEXidx_cosmos_obs_geoONpublic.cosmos_observations(latitude,longitude);

GRANTSELECTONpublic.cosmos_observationsTOauthenticated,anon;
GRANTINSERT,UPDATEONpublic.cosmos_observationsTOauthenticated;
GRANTALLONpublic.cosmos_observationsTOservice_role;

ALTERTABLEpublic.cosmos_observationsENABLEROWLEVELSECURITY;

CREATEPOLICY"anyone_view_obs"ONpublic.cosmos_observationsFORSELECTUSING(true);
CREATEPOLICY"users_insert_obs"ONpublic.cosmos_observationsFORINSERTTOauthenticatedWITHCHECK(auth.uid()=user_id);
CREATEPOLICY"users_update_own_obs"ONpublic.cosmos_observationsFORUPDATETOauthenticatedUSING(auth.uid()=user_id);

--============================================================
--Tabledesévénementsregroupés(clusterd'observations)
--Unévénement=plusieursobservationsdumêmephénomène
--============================================================
CREATETABLEpublic.cosmos_events(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
phenomenon_typetextNOTNULL,
titletextNOTNULL,
descriptiontext,
--Nombred'observationsconfirmantes
observation_countintegerDEFAULT0,
--Étenduegéographique(boundingboxapproximatif)
min_latitudedoubleprecision,
max_latitudedoubleprecision,
min_longitudedoubleprecision,
max_longitudedoubleprecision,
--Heureestiméeduphénomène
event_attimestamptzNOTNULL,
--Duréeestiméeensecondes
estimated_duration_sdoubleprecision,
--Scoredeconfianceglobal(0-1)
confidence_scoredoubleprecisionDEFAULT0,
--Statutscientifique
statustextDEFAULT'unverified'CHECK(statusIN('unverified','confirmed','transmitted','rejected')),
--AnalyseIAcomplète
ai_analysisjsonb,
--Donnéesdetriangulation(sidisponibles)
triangulationjsonb,
--Transmisàunréseauscientifiquecitoyen
transmitted_totext[],
created_attimestamptzNOTNULLDEFAULTnow(),
updated_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_cosmos_events_typeONpublic.cosmos_events(phenomenon_type);
CREATEINDEXidx_cosmos_events_atONpublic.cosmos_events(event_atDESC);
CREATEINDEXidx_cosmos_events_statusONpublic.cosmos_events(status);

GRANTSELECTONpublic.cosmos_eventsTOauthenticated,anon;
GRANTALLONpublic.cosmos_eventsTOservice_role;

ALTERTABLEpublic.cosmos_eventsENABLEROWLEVELSECURITY;

CREATEPOLICY"anyone_view_events"ONpublic.cosmos_eventsFORSELECTUSING(true);

--============================================================
--Tabledestriangulationscalculées
--============================================================
CREATETABLEpublic.cosmos_triangulations(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
event_iduuidNOTNULLREFERENCESpublic.cosmos_eventsONDELETECASCADE,
--Observationsutiliséespourlatriangulation
observation_idsuuid[]NOTNULL,
--Résultat:positionestiméeduphénomène
estimated_latitudedoubleprecision,
estimated_longitudedoubleprecision,
--Altitudeestiméeenkm
estimated_altitude_kmdoubleprecision,
--Trajectoire(tableaudepointslat/lon/alt)
trajectoryjsonb,
--Vitesseestiméeenkm/s
estimated_speed_km_sdoubleprecision,
--Erreurmarginaleestiméeenkm
error_margin_kmdoubleprecision,
--Méthodedecalcul
methodtextDEFAULT'geometric'CHECK(methodIN('geometric','ai_assisted','hybrid')),
confidencedoubleprecisionDEFAULT0,
computed_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_cosmos_tri_eventONpublic.cosmos_triangulations(event_id);

GRANTSELECTONpublic.cosmos_triangulationsTOauthenticated,anon;
GRANTALLONpublic.cosmos_triangulationsTOservice_role;

ALTERTABLEpublic.cosmos_triangulationsENABLEROWLEVELSECURITY;

CREATEPOLICY"anyone_view_triangulations"ONpublic.cosmos_triangulationsFORSELECTUSING(true);

--============================================================
--FKretardée:observations->events
--============================================================
ALTERTABLEpublic.cosmos_observations
ADDCONSTRAINTfk_obs_event
FOREIGNKEY(event_id)
REFERENCESpublic.cosmos_events(id)
ONDELETESETNULL;

--============================================================
--Trigger:incrémenteobservation_countsurcosmos_events
--============================================================
CREATEORREPLACEFUNCTIONupdate_event_observation_count()
RETURNSTRIGGERAS$$
BEGIN
IFTG_OP='INSERT'ANDNEW.event_idISNOTNULLTHEN
UPDATEpublic.cosmos_events
SETobservation_count=observation_count+1,
updated_at=now()
WHEREid=NEW.event_id;
ELSIFTG_OP='UPDATE'ANDNEW.event_idISDISTINCTFROMOLD.event_idTHEN
IFOLD.event_idISNOTNULLTHEN
UPDATEpublic.cosmos_events
SETobservation_count=GREATEST(0,observation_count-1),
updated_at=now()
WHEREid=OLD.event_id;
ENDIF;
IFNEW.event_idISNOTNULLTHEN
UPDATEpublic.cosmos_events
SETobservation_count=observation_count+1,
updated_at=now()
WHEREid=NEW.event_id;
ENDIF;
ENDIF;
RETURNNULL;
END;
$$LANGUAGEplpgsql;

CREATETRIGGERtrigger_event_obs_count
AFTERINSERTORUPDATEONpublic.cosmos_observations
FOREACHROWEXECUTEFUNCTIONupdate_event_observation_count();

--============================================================
--RPC:observationsrécentesdansunezonegéographique
--============================================================
CREATEORREPLACEFUNCTIONget_recent_observations(
lat_centerdoubleprecision,
lon_centerdoubleprecision,
radius_degdoubleprecisionDEFAULT30,
since_minutesintegerDEFAULT60,
limit_countintegerDEFAULT100
)
RETURNSSETOFpublic.cosmos_observationsAS$$
BEGIN
RETURNQUERY
SELECT*
FROMpublic.cosmos_observations
WHERE
observed_at>=now()-(since_minutes||'minutes')::interval
ANDlatitudeBETWEENlat_center-radius_degANDlat_center+radius_deg
ANDlongitudeBETWEENlon_center-radius_degANDlon_center+radius_deg
ORDERBYobserved_atDESC
LIMITlimit_count;
END;
$$LANGUAGEplpgsqlSECURITYDEFINER;

--============================================================
--RPC:événementsactifsavecstatistiques
--============================================================
CREATEORREPLACEFUNCTIONget_active_events(since_hoursintegerDEFAULT24)
RETURNSTABLE(
iduuid,
phenomenon_typetext,
titletext,
descriptiontext,
observation_countinteger,
confidence_scoredoubleprecision,
statustext,
event_attimestamptz,
triangulationjsonb,
ai_analysisjsonb
)AS$$
BEGIN
RETURNQUERY
SELECT
e.id,e.phenomenon_type,e.title,e.description,
e.observation_count,e.confidence_score,e.status,
e.event_at,e.triangulation,e.ai_analysis
FROMpublic.cosmos_eventse
WHEREe.event_at>=now()-(since_hours||'hours')::interval
ANDe.status!='rejected'
ORDERBYe.observation_countDESC,e.event_atDESC;
END;
$$LANGUAGEplpgsqlSECURITYDEFINER;
