--============================================================
--ASTROSTACKGLOBAL—Moteurdefusionastrophotographiquemondial
--============================================================

--Cataloguedesobjetscélestesconnus(M31,NGC224,etc.)
CREATETABLEpublic.astro_objects(
idtextPRIMARYKEY,--"M31","NGC224","IC1805",etc.
common_nametext,
typetextNOTNULLCHECK(typeIN(
'galaxy','nebula','cluster_open','cluster_globular',
'planetary_nebula','supernova_remnant','double_star',
'asteroid','comet','planet','other'
)),
ra_degdoubleprecisionNOTNULL,--RightAscensionendegrés
dec_degdoubleprecisionNOTNULL,--Declinationendegrés
magnitudedoubleprecision,
size_arcmindoubleprecision,--Tailleapparenteenarcminutes
descriptiontext,
--Statsagrégéesmisesàjourpartriggers
total_lightsbigintDEFAULT0,
total_darksbigintDEFAULT0,
total_flatsbigintDEFAULT0,
total_biasbigintDEFAULT0,
total_contributorsintegerDEFAULT0,
total_exposure_hoursdoubleprecisionDEFAULT0,
master_image_urltext,
master_updated_attimestamptz,
created_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_astro_objects_typeONpublic.astro_objects(type);
CREATEINDEXidx_astro_objects_ra_decONpublic.astro_objects(ra_deg,dec_deg);

GRANTSELECTONpublic.astro_objectsTOauthenticated,anon;
GRANTALLONpublic.astro_objectsTOservice_role;

ALTERTABLEpublic.astro_objectsENABLEROWLEVELSECURITY;
CREATEPOLICY"anyone_view_objects"ONpublic.astro_objectsFORSELECTUSING(true);

--============================================================
--Uploadsdeframesparlescontributeurs
--============================================================
CREATETABLEpublic.astro_uploads(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidNOTNULLREFERENCESauth.usersONDELETECASCADE,
object_idtextREFERENCESpublic.astro_objects(id)ONDELETESETNULL,
--Typedeframe
frame_typetextNOTNULLCHECK(frame_typeIN('light','dark','flat','bias')),
--Stockage
storage_pathtextNOTNULL,
file_urltextNOTNULL,
file_size_bytesbigintNOTNULL,
original_filenametextNOTNULL,
--MétadonnéesFITS/EXIFextraitesousoumises
metadatajsonbDEFAULT'{}',
--Instrument
telescopetext,
cameratext,
focal_length_mmdoubleprecision,
aperture_mmdoubleprecision,
focal_ratiodoubleprecision,
pixel_size_umdoubleprecision,
sensor_width_pxinteger,
sensor_height_pxinteger,
--Acquisition
exposure_sdoubleprecision,
gaininteger,
offset_intinteger,
temperature_cdoubleprecision,
filter_nametext,
binningintegerDEFAULT1,
--Localisationettemps
latitudedoubleprecision,
longitudedoubleprecision,
altitude_mdoubleprecision,
captured_attimestamptz,
--Qualitéautomatique(calculéeparl'IApipeline)
fwhmdoubleprecision,
eccentricitydoubleprecision,
snrdoubleprecision,
background_gradientdoubleprecision,
star_countinteger,
--Platesolving
solvedbooleanDEFAULTfalse,
solved_ra_degdoubleprecision,
solved_dec_degdoubleprecision,
solved_scale_arcsec_pxdoubleprecision,
solved_rotation_degdoubleprecision,
--Rejetautomatique
rejectedbooleanDEFAULTfalse,
rejection_reasontext,
--QualificationIA
quality_scoredoubleprecisionDEFAULT0,--0à1
ai_analysisjsonb,
--Compatibilitépourstacking
instrument_grouptext,--hashdecompatibilitéinstrument
--Statutdanslepipeline
statustextDEFAULT'uploaded'CHECK(statusIN(
'uploaded','extracting','qualifying','qualified',
'stacking','stacked','rejected'
)),
uploaded_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_astro_uploads_userONpublic.astro_uploads(user_id);
CREATEINDEXidx_astro_uploads_objectONpublic.astro_uploads(object_id)WHEREobject_idISNOTNULL;
CREATEINDEXidx_astro_uploads_typeONpublic.astro_uploads(frame_type);
CREATEINDEXidx_astro_uploads_statusONpublic.astro_uploads(status);
CREATEINDEXidx_astro_uploads_qualityONpublic.astro_uploads(quality_scoreDESC)WHERErejected=false;
CREATEINDEXidx_astro_uploads_groupONpublic.astro_uploads(instrument_group)WHEREinstrument_groupISNOTNULL;

GRANTSELECTONpublic.astro_uploadsTOauthenticated,anon;
GRANTINSERT,UPDATEONpublic.astro_uploadsTOauthenticated;
GRANTALLONpublic.astro_uploadsTOservice_role;

ALTERTABLEpublic.astro_uploadsENABLEROWLEVELSECURITY;
CREATEPOLICY"anyone_view_uploads"ONpublic.astro_uploadsFORSELECTUSING(true);
CREATEPOLICY"users_insert_uploads"ONpublic.astro_uploadsFORINSERTTOauthenticatedWITHCHECK(auth.uid()=user_id);
CREATEPOLICY"users_update_own_uploads"ONpublic.astro_uploadsFORUPDATETOauthenticatedUSING(auth.uid()=user_id);

--============================================================
--Jobsdestacking(unetentativedefusionpourunobjet)
--============================================================
CREATETABLEpublic.astro_stacking_jobs(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
object_idtextNOTNULLREFERENCESpublic.astro_objects(id)ONDELETECASCADE,
--Uploadsinclusdanscejob
light_idsuuid[]NOTNULLDEFAULT'{}',
dark_idsuuid[]DEFAULT'{}',
flat_idsuuid[]DEFAULT'{}',
bias_idsuuid[]DEFAULT'{}',
--Statistiquesdujob
lights_countintegerDEFAULT0,
total_exposure_hoursdoubleprecisionDEFAULT0,
contributors_countintegerDEFAULT0,
configurations_countintegerDEFAULT0,
--Paramètresdestacking
stacking_methodtextDEFAULT'kappa_sigma'CHECK(stacking_methodIN(
'mean','median','kappa_sigma','winsorized','linear_fit'
)),
weighting_modetextDEFAULT'quality_score'CHECK(weighting_modeIN(
'equal','snr','fwhm','quality_score','exposure'
)),
--Résultats
statustextDEFAULT'pending'CHECK(statusIN(
'pending','running','completed','failed'
)),
result_image_urltext,
result_thumbnail_urltext,
result_metadatajsonb,
ai_pipeline_logjsonb,
error_messagetext,
started_attimestamptz,
completed_attimestamptz,
created_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_stacking_jobs_objectONpublic.astro_stacking_jobs(object_id);
CREATEINDEXidx_stacking_jobs_statusONpublic.astro_stacking_jobs(status);

GRANTSELECTONpublic.astro_stacking_jobsTOauthenticated,anon;
GRANTALLONpublic.astro_stacking_jobsTOservice_role;

ALTERTABLEpublic.astro_stacking_jobsENABLEROWLEVELSECURITY;
CREATEPOLICY"anyone_view_jobs"ONpublic.astro_stacking_jobsFORSELECTUSING(true);

--============================================================
--Masters:imagesrésultantesconsolidéesparobjet
--============================================================
CREATETABLEpublic.astro_masters(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
object_idtextNOTNULLREFERENCESpublic.astro_objects(id)ONDELETECASCADE,
stacking_job_iduuidREFERENCESpublic.astro_stacking_jobs(id)ONDELETESETNULL,
--Imagefinale
image_urltextNOTNULL,
thumbnail_urltext,
--Statistiquesdelafusion
lights_stackedintegerNOTNULLDEFAULT0,
total_exposure_hoursdoubleprecisionNOTNULLDEFAULT0,
contributors_countintegerNOTNULLDEFAULT0,
configurations_countintegerNOTNULLDEFAULT0,
countries_countintegerNOTNULLDEFAULT0,
--Qualitédelafusion
final_snrdoubleprecision,
final_fwhmdoubleprecision,
dynamic_range_stopsdoubleprecision,
--Métadonnées
generationintegerNOTNULLDEFAULT1,--numérodeversiondumaster
notestext,
is_currentbooleanNOTNULLDEFAULTtrue,
created_attimestamptzNOTNULLDEFAULTnow()
);

CREATEINDEXidx_astro_masters_objectONpublic.astro_masters(object_id);
CREATEINDEXidx_astro_masters_currentONpublic.astro_masters(object_id,is_current)WHEREis_current=true;

GRANTSELECTONpublic.astro_mastersTOauthenticated,anon;
GRANTALLONpublic.astro_mastersTOservice_role;

ALTERTABLEpublic.astro_mastersENABLEROWLEVELSECURITY;
CREATEPOLICY"anyone_view_masters"ONpublic.astro_mastersFORSELECTUSING(true);

--============================================================
--Contributions:lienuser?objet(statsparcontributeur)
--============================================================
CREATETABLEpublic.astro_contributions(
iduuidPRIMARYKEYDEFAULTgen_random_uuid(),
user_iduuidNOTNULLREFERENCESauth.usersONDELETECASCADE,
object_idtextNOTNULLREFERENCESpublic.astro_objects(id)ONDELETECASCADE,
lights_countintegerDEFAULT0,
darks_countintegerDEFAULT0,
flats_countintegerDEFAULT0,
bias_countintegerDEFAULT0,
total_exposure_hoursdoubleprecisionDEFAULT0,
quality_avgdoubleprecisionDEFAULT0,
first_contribution_attimestamptzDEFAULTnow(),
last_contribution_attimestamptzDEFAULTnow(),
UNIQUE(user_id,object_id)
);

CREATEINDEXidx_contributions_userONpublic.astro_contributions(user_id);
CREATEINDEXidx_contributions_objectONpublic.astro_contributions(object_id);

GRANTSELECTONpublic.astro_contributionsTOauthenticated,anon;
GRANTINSERT,UPDATEONpublic.astro_contributionsTOauthenticated;
GRANTALLONpublic.astro_contributionsTOservice_role;

ALTERTABLEpublic.astro_contributionsENABLEROWLEVELSECURITY;
CREATEPOLICY"anyone_view_contributions"ONpublic.astro_contributionsFORSELECTUSING(true);
CREATEPOLICY"users_manage_own_contributions"ONpublic.astro_contributions
FORALLTOauthenticatedUSING(auth.uid()=user_id)WITHCHECK(auth.uid()=user_id);

--============================================================
--Triggers:miseàjourdesstatistiquesagrégées
--============================================================

--Metàjourastro_objects+astro_contributionsaprèsunuploadqualifié
CREATEORREPLACEFUNCTIONupdate_object_stats_on_upload()
RETURNSTRIGGERAS$$
BEGIN
--Miseàjourdescompteurssurl'objet
IFNEW.object_idISNOTNULLANDNEW.rejected=falseTHEN
IFNEW.frame_type='light'THEN
UPDATEpublic.astro_objects
SETtotal_lights=total_lights+1,
total_exposure_hours=total_exposure_hours+COALESCE(NEW.exposure_s,0)/3600.0
WHEREid=NEW.object_id;
ELSIFNEW.frame_type='dark'THEN
UPDATEpublic.astro_objectsSETtotal_darks=total_darks+1WHEREid=NEW.object_id;
ELSIFNEW.frame_type='flat'THEN
UPDATEpublic.astro_objectsSETtotal_flats=total_flats+1WHEREid=NEW.object_id;
ELSIFNEW.frame_type='bias'THEN
UPDATEpublic.astro_objectsSETtotal_bias=total_bias+1WHEREid=NEW.object_id;
ENDIF;

--Upsertcontributions
INSERTINTOpublic.astro_contributions(user_id,object_id,
lights_count,darks_count,flats_count,bias_count,
total_exposure_hours,last_contribution_at)
VALUES(
NEW.user_id,NEW.object_id,
CASEWHENNEW.frame_type='light'THEN1ELSE0END,
CASEWHENNEW.frame_type='dark'THEN1ELSE0END,
CASEWHENNEW.frame_type='flat'THEN1ELSE0END,
CASEWHENNEW.frame_type='bias'THEN1ELSE0END,
CASEWHENNEW.frame_type='light'THENCOALESCE(NEW.exposure_s,0)/3600.0ELSE0END,
now()
)
ONCONFLICT(user_id,object_id)DOUPDATESET
lights_count=astro_contributions.lights_count+EXCLUDED.lights_count,
darks_count=astro_contributions.darks_count+EXCLUDED.darks_count,
flats_count=astro_contributions.flats_count+EXCLUDED.flats_count,
bias_count=astro_contributions.bias_count+EXCLUDED.bias_count,
total_exposure_hours=astro_contributions.total_exposure_hours+EXCLUDED.total_exposure_hours,
last_contribution_at=now();

--Metàjourlecompteurdecontributeursuniques
UPDATEpublic.astro_objects
SETtotal_contributors=(
SELECTCOUNT(DISTINCTuser_id)
FROMpublic.astro_uploads
WHEREobject_id=NEW.object_idANDrejected=false
)
WHEREid=NEW.object_id;
ENDIF;
RETURNNULL;
END;
$$LANGUAGEplpgsql;

CREATETRIGGERtrigger_update_object_stats
AFTERINSERTONpublic.astro_uploads
FOREACHROWEXECUTEFUNCTIONupdate_object_stats_on_upload();

--Metàjourmaster_image_urlsurastro_objectsquandunmasterestcréé
CREATEORREPLACEFUNCTIONupdate_object_master()
RETURNSTRIGGERAS$$
BEGIN
IFNEW.is_currentTHEN
--Marquelesanciensmasterscommenoncourants
UPDATEpublic.astro_masters
SETis_current=false
WHEREobject_id=NEW.object_idANDid!=NEW.id;
--Metàjourl'objet
UPDATEpublic.astro_objects
SETmaster_image_url=NEW.image_url,
master_updated_at=NEW.created_at
WHEREid=NEW.object_id;
ENDIF;
RETURNNULL;
END;
$$LANGUAGEplpgsql;

CREATETRIGGERtrigger_update_object_master
AFTERINSERTORUPDATEONpublic.astro_masters
FOREACHROWEXECUTEFUNCTIONupdate_object_master();

--============================================================
--Seed:objetsMessier/NGCpopulaires
--============================================================
INSERTINTOpublic.astro_objects(id,common_name,type,ra_deg,dec_deg,magnitude,size_arcmin,description)VALUES
('M31','Andromède','galaxy',10.6847,41.2692,3.4,189.0,'Grandegalaxiespiraledelaconstellationd''Andromède'),
('M42','Nébuleused''Orion','nebula',83.8221,-5.3911,4.0,85.0,'Nébuleusediffusegéantedanslaconstellationd''Orion'),
('M45','Pléiades','cluster_open',56.8750,24.1167,1.6,110.0,'AmasouvertbrillantdansleTaureau'),
('M51','GalaxieduTourbillon','galaxy',202.4696,47.1952,8.4,11.2,'GalaxiespiraleaveccompagnonNGC5195'),
('M57','Nébuleusedel''Anneau','planetary_nebula',283.3963,33.0289,8.8,1.4,'NébuleuseplanétairedanslaLyre'),
('M101','GalaxieduMoulinet','galaxy',210.8024,54.3489,7.9,28.8,'Grandegalaxiespiraleenface'),
('M13','Amasd''Hercule','cluster_globular',250.4234,36.4613,5.8,20.0,'Plusgrandamasglobulairedel''hémisphèrenord'),
('M27','NébuleuseHaltère','planetary_nebula',299.9013,22.7214,7.5,8.0,'NébuleuseplanétairedanslePetitRenard'),
('NGC7000','NébuleuseAmériqueduNord','nebula',314.7500,44.3333,4.0,120.0,'Grandenébuleuseenémissionenformedecontinent'),
('IC1805','NébuleuseduCoeur','nebula',38.1750,61.4500,6.5,60.0,'NébuleuseenémissiondansCassiopée'),
('M33','GalaxieduTriangle','galaxy',23.4620,30.6603,5.7,70.0,'GalaxiespiraleduGroupeLocal'),
('M81','GalaxiedeBode','galaxy',148.8882,69.0653,6.9,26.9,'GrandegalaxiespiraledanslaGrandeOurse'),
('M82','GalaxieCigare','galaxy',148.9695,69.6797,8.4,11.2,'GalaxiestarburstcompagnondeM81'),
('M104','GalaxieSombrero','galaxy',189.9976,-11.6231,8.0,8.7,'Galaxiespiraleavecanneaudepoussièreproéminent'),
('NGC4889','','galaxy',195.0338,27.9769,11.5,2.8,'GalaxieelliptiquegéantedanslaCheveluredeBérénice')
ONCONFLICT(id)DONOTHING;

--============================================================
--RPC:recherched'objets+statspourcontribution
--============================================================
CREATEORREPLACEFUNCTIONsearch_astro_objects(
querytextDEFAULT'',
object_typetextDEFAULTNULL,
min_contributorsintegerDEFAULT0,
limit_countintegerDEFAULT20
)
RETURNSSETOFpublic.astro_objectsAS$$
BEGIN
RETURNQUERY
SELECT*FROMpublic.astro_objects
WHERE
(query=''OR
idILIKE'%'||query||'%'OR
common_nameILIKE'%'||query||'%'
)
AND(object_typeISNULLORtype=object_type)
ANDtotal_contributors>=min_contributors
ORDERBYtotal_lightsDESC,idASC
LIMITlimit_count;
END;
$$LANGUAGEplpgsqlSECURITYDEFINER;

--RPC:topcontributeurspourunobjet
CREATEORREPLACEFUNCTIONget_top_contributors(
p_object_idtext,
limit_countintegerDEFAULT10
)
RETURNSTABLE(
user_iduuid,
lights_countinteger,
total_exposure_hoursdoubleprecision,
quality_avgdoubleprecision,
last_contribution_attimestamptz
)AS$$
BEGIN
RETURNQUERY
SELECTc.user_id,c.lights_count,c.total_exposure_hours,
c.quality_avg,c.last_contribution_at
FROMpublic.astro_contributionsc
WHEREc.object_id=p_object_id
ORDERBYc.total_exposure_hoursDESC
LIMITlimit_count;
END;
$$LANGUAGEplpgsqlSECURITYDEFINER;

--RPC:recommandationspourunutilisateur(objetsaveclacunesdedata)
CREATEORREPLACEFUNCTIONget_contribution_recommendations(
p_user_iduuid,
limit_countintegerDEFAULT10
)
RETURNSTABLE(
object_idtext,
common_nametext,
typetext,
total_lightsbigint,
total_contributorsinteger,
missing_darksboolean,
missing_flatsboolean,
scoredoubleprecision
)AS$$
BEGIN
RETURNQUERY
SELECT
o.id,
o.common_name,
o.type,
o.total_lights,
o.total_contributors,
o.total_darks<50asmissing_darks,
o.total_flats<50asmissing_flats,
--Scoredebesoin:objetspopulairesavecdonnéesmanquantes
(o.total_lights::doubleprecision/GREATEST(1,o.total_contributors)+
CASEWHENo.total_darks<50THEN50ELSE0END+
CASEWHENo.total_flats<50THEN30ELSE0END)asscore
FROMpublic.astro_objectso
WHERENOTEXISTS(
SELECT1FROMpublic.astro_contributionsc
WHEREc.user_id=p_user_idANDc.object_id=o.id
)
ORDERBYscoreDESC
LIMITlimit_count;
END;
$$LANGUAGEplpgsqlSECURITYDEFINER;
