import { createFileRoute } from "@tanstack/react-router";
import { createAdminClient } from "@/lib/api-auth.server";
import {
  buildGlobalMosaicProperties,
  GLOBAL_MOSAIC_MIN_PHOTO_ORDER,
  parseGlobalMosaicTilePath,
} from "@/features/mosaic/domain/global-hips";

const RED_TILE_BASE64 =
  "UklGRhgCAABXRUJQVlA4IAwCAABQOgCdASoAAgACPp1OpE4lpCOiIAgAsBOJaW7hd2EbQAnsA99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych6wAAP7/wsv/QfFy//8kvk787RRu6wz3AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

const RED_TILE_BYTES = Uint8Array.from(atob(RED_TILE_BASE64), (character) =>
  character.charCodeAt(0),
);
const TILE_CACHE_CONTROL = "public, max-age=60, s-maxage=300, stale-while-revalidate=900";
const PROPERTIES_CACHE_CONTROL = "public, max-age=3600, s-maxage=3600";

function redTileResponse(): Response {
  return new Response(RED_TILE_BYTES, {
    headers: {
      "Content-Type": "image/webp",
      "Cache-Control": TILE_CACHE_CONTROL,
      "X-Sky-Map-Coverage": "uncovered",
    },
  });
}

function isPublishedTilePath(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.startsWith("hips/") &&
    value.endsWith(".webp") &&
    !value.includes("..")
  );
}

export const Route = createFileRoute("/api/mosaic/hips/$")({
  server: {
    handlers: {
      GET: async ({ params }) => {
        const path = params._splat?.replace(/^\/+|\/+$/g, "") ?? "";
        if (path === "properties") {
          return new Response(buildGlobalMosaicProperties(), {
            headers: {
              "Content-Type": "text/plain; charset=utf-8",
              "Cache-Control": PROPERTIES_CACHE_CONTROL,
            },
          });
        }

        const tile = parseGlobalMosaicTilePath(path);
        if (!tile) return new Response("HiPS resource not found", { status: 404 });

        // The current v9 publisher starts at HEALPix order 6. At wider zoom levels
        // Sky Map deliberately renders the still-uncovered universe in red until
        // parent/Allsky products are generated by a later all-sky publication pass.
        if (tile.order < GLOBAL_MOSAIC_MIN_PHOTO_ORDER) return redTileResponse();

        const admin = createAdminClient();
        const { data, error } = await admin.rpc("resolve_global_mosaic_tile", {
          p_order: tile.order,
          p_index: tile.index,
        });
        if (error) {
          return new Response("Sky Map tile lookup unavailable", {
            status: 503,
            headers: { "Cache-Control": "no-store" },
          });
        }

        const row = data?.[0] as { tile_path?: unknown } | undefined;
        if (!row || !isPublishedTilePath(row.tile_path)) return redTileResponse();

        const supabaseUrl = process.env["SUPABASE_URL"]?.replace(/\/$/, "");
        if (!supabaseUrl) {
          return new Response("Sky Map storage is unavailable", {
            status: 503,
            headers: { "Cache-Control": "no-store" },
          });
        }

        const storageUrl = `${supabaseUrl}/storage/v1/object/public/astro-derived/${row.tile_path}`;
        return new Response(null, {
          status: 307,
          headers: {
            Location: storageUrl,
            "Cache-Control": TILE_CACHE_CONTROL,
            "X-Sky-Map-Coverage": "covered",
          },
        });
      },
    },
  },
});
