import{Slot}from"@radix-ui/react-slot"
import{cva,typeVariantProps}from"class-variance-authority"

import{cn}from"@/lib/utils"
import{Separator}from"@/components/ui/separator"

constbuttonGroupVariants=cva(
"flexw-fititems-stretchhas-[>[data-slot=button-group]]:gap-2[&>*]:focus-visible:relative[&>*]:focus-visible:z-10has-[select[aria-hidden=true]:last-child]:[&>[data-slot=select-trigger]:last-of-type]:rounded-r-md[&>[data-slot=select-trigger]:not([class*='w-'])]:w-fit[&>input]:flex-1",
{
variants:{
orientation:{
horizontal:
"[&>*:not(:first-child)]:rounded-l-none[&>*:not(:first-child)]:border-l-0[&>*:not(:last-child)]:rounded-r-none",
vertical:
"flex-col[&>*:not(:first-child)]:rounded-t-none[&>*:not(:first-child)]:border-t-0[&>*:not(:last-child)]:rounded-b-none",
},
},
defaultVariants:{
orientation:"horizontal",
},
}
)

functionButtonGroup({
className,
orientation,
...props
}:React.ComponentProps<"div">&VariantProps<typeofbuttonGroupVariants>){
return(
<div
role="group"
data-slot="button-group"
data-orientation={orientation}
className={cn(buttonGroupVariants({orientation}),className)}
{...props}
/>
)
}

functionButtonGroupText({
className,
asChild=false,
...props
}:React.ComponentProps<"div">&{
asChild?:boolean
}){
constComp=asChild?Slot:"div"

return(
<Comp
className={cn(
"bg-mutedshadow-xsflexitems-centergap-2rounded-mdborderpx-4text-smfont-medium[&_svg:not([class*='size-'])]:size-4[&_svg]:pointer-events-none",
className
)}
{...props}
/>
)
}

functionButtonGroupSeparator({
className,
orientation="vertical",
...props
}:React.ComponentProps<typeofSeparator>){
return(
<Separator
data-slot="button-group-separator"
orientation={orientation}
className={cn(
"bg-inputrelative!m-0self-stretchdata-[orientation=vertical]:h-auto",
className
)}
{...props}
/>
)
}

export{
ButtonGroup,
ButtonGroupSeparator,
ButtonGroupText,
buttonGroupVariants,
}
