"useclient";

import*asReactfrom"react";
import{ChevronDownIcon,ChevronLeftIcon,ChevronRightIcon}from"lucide-react";
import{DayButton,DayPicker,getDefaultClassNames}from"react-day-picker";

import{cn}from"@/lib/utils";
import{Button,buttonVariants}from"@/components/ui/button";

functionCalendar({
className,
classNames,
showOutsideDays=true,
captionLayout="label",
buttonVariant="ghost",
formatters,
components,
...props
}:React.ComponentProps<typeofDayPicker>&{
buttonVariant?:React.ComponentProps<typeofButton>["variant"];
}){
constdefaultClassNames=getDefaultClassNames();

return(
<DayPicker
showOutsideDays={showOutsideDays}
className={cn(
"bg-backgroundgroup/calendarp-3[--cell-size:2rem][[data-slot=card-content]_&]:bg-transparent[[data-slot=popover-content]_&]:bg-transparent",
String.raw`rtl:**:[.rdp-button\_next>svg]:rotate-180`,
String.raw`rtl:**:[.rdp-button\_previous>svg]:rotate-180`,
className,
)}
captionLayout={captionLayout}
formatters={{
formatMonthDropdown:(date)=>date.toLocaleString("default",{month:"short"}),
...formatters,
}}
classNames={{
root:cn("w-fit",defaultClassNames.root),
months:cn("relativeflexflex-colgap-4md:flex-row",defaultClassNames.months),
month:cn("flexw-fullflex-colgap-4",defaultClassNames.month),
nav:cn(
"absoluteinset-x-0top-0flexw-fullitems-centerjustify-betweengap-1",
defaultClassNames.nav,
),
button_previous:cn(
buttonVariants({variant:buttonVariant}),
"h-(--cell-size)w-(--cell-size)select-nonep-0aria-disabled:opacity-50",
defaultClassNames.button_previous,
),
button_next:cn(
buttonVariants({variant:buttonVariant}),
"h-(--cell-size)w-(--cell-size)select-nonep-0aria-disabled:opacity-50",
defaultClassNames.button_next,
),
month_caption:cn(
"flexh-(--cell-size)w-fullitems-centerjustify-centerpx-(--cell-size)",
defaultClassNames.month_caption,
),
dropdowns:cn(
"flexh-(--cell-size)w-fullitems-centerjustify-centergap-1.5text-smfont-medium",
defaultClassNames.dropdowns,
),
dropdown_root:cn(
"has-focus:border-ringborder-inputshadow-xshas-focus:ring-ring/50has-focus:ring-[3px]relativerounded-mdborder",
defaultClassNames.dropdown_root,
),
dropdown:cn("bg-popoverabsoluteinset-0opacity-0",defaultClassNames.dropdown),
caption_label:cn(
"select-nonefont-medium",
captionLayout==="label"
?"text-sm"
:"[&>svg]:text-muted-foregroundflexh-8items-centergap-1rounded-mdpl-2pr-1text-sm[&>svg]:size-3.5",
defaultClassNames.caption_label,
),
table:"w-fullborder-collapse",
weekdays:cn("flex",defaultClassNames.weekdays),
weekday:cn(
"text-muted-foregroundflex-1select-nonerounded-mdtext-[0.8rem]font-normal",
defaultClassNames.weekday,
),
week:cn("mt-2flexw-full",defaultClassNames.week),
week_number_header:cn("w-(--cell-size)select-none",defaultClassNames.week_number_header),
week_number:cn(
"text-muted-foregroundselect-nonetext-[0.8rem]",
defaultClassNames.week_number,
),
day:cn(
"group/dayrelativeaspect-squareh-fullw-fullselect-nonep-0text-center[&:first-child[data-selected=true]_button]:rounded-l-md[&:last-child[data-selected=true]_button]:rounded-r-md",
defaultClassNames.day,
),
range_start:cn("bg-accentrounded-l-md",defaultClassNames.range_start),
range_middle:cn("rounded-none",defaultClassNames.range_middle),
range_end:cn("bg-accentrounded-r-md",defaultClassNames.range_end),
today:cn(
"bg-accenttext-accent-foregroundrounded-mddata-[selected=true]:rounded-none",
defaultClassNames.today,
),
outside:cn(
"text-muted-foregroundaria-selected:text-muted-foreground",
defaultClassNames.outside,
),
disabled:cn("text-muted-foregroundopacity-50",defaultClassNames.disabled),
hidden:cn("invisible",defaultClassNames.hidden),
...classNames,
}}
components={{
Root:({className,rootRef,...props})=>{
return<divdata-slot="calendar"ref={rootRef}className={cn(className)}{...props}/>;
},
Chevron:({className,orientation,...props})=>{
if(orientation==="left"){
return<ChevronLeftIconclassName={cn("size-4",className)}{...props}/>;
}

if(orientation==="right"){
return<ChevronRightIconclassName={cn("size-4",className)}{...props}/>;
}

return<ChevronDownIconclassName={cn("size-4",className)}{...props}/>;
},
DayButton:CalendarDayButton,
WeekNumber:({children,...props})=>{
return(
<td{...props}>
<divclassName="flexsize-(--cell-size)items-centerjustify-centertext-center">
{children}
</div>
</td>
);
},
...components,
}}
{...props}
/>
);
}

functionCalendarDayButton({
className,
day,
modifiers,
...props
}:React.ComponentProps<typeofDayButton>){
constdefaultClassNames=getDefaultClassNames();

constref=React.useRef<HTMLButtonElement>(null);
React.useEffect(()=>{
if(modifiers["focused"])ref.current?.focus();
},[modifiers]);

return(
<Button
ref={ref}
variant="ghost"
size="icon"
data-day={day.date.toLocaleDateString()}
data-selected-single={
modifiers["selected"]&&
!modifiers["range_start"]&&
!modifiers["range_end"]&&
!modifiers["range_middle"]
}
data-range-start={modifiers["range_start"]}
data-range-end={modifiers["range_end"]}
data-range-middle={modifiers["range_middle"]}
className={cn(
"data-[selected-single=true]:bg-primarydata-[selected-single=true]:text-primary-foregrounddata-[range-middle=true]:bg-accentdata-[range-middle=true]:text-accent-foregrounddata-[range-start=true]:bg-primarydata-[range-start=true]:text-primary-foregrounddata-[range-end=true]:bg-primarydata-[range-end=true]:text-primary-foregroundgroup-data-[focused=true]/day:border-ringgroup-data-[focused=true]/day:ring-ring/50flexaspect-squareh-autow-fullmin-w-(--cell-size)flex-colgap-1font-normalleading-nonedata-[range-end=true]:rounded-mddata-[range-middle=true]:rounded-nonedata-[range-start=true]:rounded-mdgroup-data-[focused=true]/day:relativegroup-data-[focused=true]/day:z-10group-data-[focused=true]/day:ring-[3px][&>span]:text-xs[&>span]:opacity-70",
defaultClassNames.day,
className,
)}
{...props}
/>
);
}

export{Calendar,CalendarDayButton};
