"useclient"

import*asReactfrom"react"
import{cva,typeVariantProps}from"class-variance-authority"

import{cn}from"@/lib/utils"
import{Button}from"@/components/ui/button"
import{Input}from"@/components/ui/input"
import{Textarea}from"@/components/ui/textarea"

functionInputGroup({className,...props}:React.ComponentProps<"div">){
return(
<div
data-slot="input-group"
role="group"
className={cn(
"group/input-groupborder-inputdark:bg-input/30shadow-xsrelativeflexw-fullitems-centerrounded-mdborderoutline-nonetransition-[color,box-shadow]",
"h-9has-[>textarea]:h-auto",

//Variantsbasedonalignment.
"has-[>[data-align=inline-start]]:[&>input]:pl-2",
"has-[>[data-align=inline-end]]:[&>input]:pr-2",
"has-[>[data-align=block-start]]:h-autohas-[>[data-align=block-start]]:flex-colhas-[>[data-align=block-start]]:[&>input]:pb-3",
"has-[>[data-align=block-end]]:h-autohas-[>[data-align=block-end]]:flex-colhas-[>[data-align=block-end]]:[&>input]:pt-3",

//Focusstate.
"has-[[data-slot=input-group-control]:focus-visible]:ring-ringhas-[[data-slot=input-group-control]:focus-visible]:ring-1",

//Errorstate.
"has-[[data-slot][aria-invalid=true]]:ring-destructive/20has-[[data-slot][aria-invalid=true]]:border-destructivedark:has-[[data-slot][aria-invalid=true]]:ring-destructive/40",

className
)}
{...props}
/>
)
}

constinputGroupAddonVariants=cva(
"text-muted-foregroundflexh-autocursor-textselect-noneitems-centerjustify-centergap-2py-1.5text-smfont-mediumgroup-data-[disabled=true]/input-group:opacity-50[&>kbd]:rounded-[calc(var(--radius)-5px)][&>svg:not([class*='size-'])]:size-4",
{
variants:{
align:{
"inline-start":
"order-firstpl-3has-[>button]:ml-[-0.45rem]has-[>kbd]:ml-[-0.35rem]",
"inline-end":
"order-lastpr-3has-[>button]:mr-[-0.4rem]has-[>kbd]:mr-[-0.35rem]",
"block-start":
"[.border-b]:pb-3order-firstw-fulljustify-startpx-3pt-3group-has-[>input]/input-group:pt-2.5",
"block-end":
"[.border-t]:pt-3order-lastw-fulljustify-startpx-3pb-3group-has-[>input]/input-group:pb-2.5",
},
},
defaultVariants:{
align:"inline-start",
},
}
)

functionInputGroupAddon({
className,
align="inline-start",
...props
}:React.ComponentProps<"div">&VariantProps<typeofinputGroupAddonVariants>){
return(
<div
role="group"
data-slot="input-group-addon"
data-align={align}
className={cn(inputGroupAddonVariants({align}),className)}
onClick={(e)=>{
if((e.targetasHTMLElement).closest("button")){
return
}
e.currentTarget.parentElement?.querySelector("input")?.focus()
}}
{...props}
/>
)
}

constinputGroupButtonVariants=cva(
"flexitems-centergap-2text-smshadow-none",
{
variants:{
size:{
xs:"h-6gap-1rounded-[calc(var(--radius)-5px)]px-2has-[>svg]:px-2[&>svg:not([class*='size-'])]:size-3.5",
sm:"h-8gap-1.5rounded-mdpx-2.5has-[>svg]:px-2.5",
"icon-xs":
"size-6rounded-[calc(var(--radius)-5px)]p-0has-[>svg]:p-0",
"icon-sm":"size-8p-0has-[>svg]:p-0",
},
},
defaultVariants:{
size:"xs",
},
}
)

functionInputGroupButton({
className,
type="button",
variant="ghost",
size="xs",
...props
}:Omit<React.ComponentProps<typeofButton>,"size">&
VariantProps<typeofinputGroupButtonVariants>){
return(
<Button
type={type}
data-size={size}
variant={variant}
className={cn(inputGroupButtonVariants({size}),className)}
{...props}
/>
)
}

functionInputGroupText({className,...props}:React.ComponentProps<"span">){
return(
<span
className={cn(
"text-muted-foregroundflexitems-centergap-2text-sm[&_svg:not([class*='size-'])]:size-4[&_svg]:pointer-events-none",
className
)}
{...props}
/>
)
}

functionInputGroupInput({
className,
...props
}:React.ComponentProps<"input">){
return(
<Input
data-slot="input-group-control"
className={cn(
"flex-1rounded-noneborder-0bg-transparentshadow-nonefocus-visible:ring-0dark:bg-transparent",
className
)}
{...props}
/>
)
}

functionInputGroupTextarea({
className,
...props
}:React.ComponentProps<"textarea">){
return(
<Textarea
data-slot="input-group-control"
className={cn(
"flex-1resize-nonerounded-noneborder-0bg-transparentpy-3shadow-nonefocus-visible:ring-0dark:bg-transparent",
className
)}
{...props}
/>
)
}

export{
InputGroup,
InputGroupAddon,
InputGroupButton,
InputGroupText,
InputGroupInput,
InputGroupTextarea,
}
