import*asReactfrom"react";
import*asMenubarPrimitivefrom"@radix-ui/react-menubar";
import{Check,ChevronRight,Circle}from"lucide-react";

import{cn}from"@/lib/utils";

functionMenubarMenu({...props}:React.ComponentProps<typeofMenubarPrimitive.Menu>){
return<MenubarPrimitive.Menu{...props}/>;
}

functionMenubarGroup({...props}:React.ComponentProps<typeofMenubarPrimitive.Group>){
return<MenubarPrimitive.Group{...props}/>;
}

functionMenubarPortal({...props}:React.ComponentProps<typeofMenubarPrimitive.Portal>){
return<MenubarPrimitive.Portal{...props}/>;
}

functionMenubarRadioGroup({...props}:React.ComponentProps<typeofMenubarPrimitive.RadioGroup>){
return<MenubarPrimitive.RadioGroup{...props}/>;
}

functionMenubarSub({...props}:React.ComponentProps<typeofMenubarPrimitive.Sub>){
return<MenubarPrimitive.Subdata-slot="menubar-sub"{...props}/>;
}

constMenubar=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Root>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Root>
>(({className,...props},ref)=>(
<MenubarPrimitive.Root
ref={ref}
className={cn(
"flexh-9items-centerspace-x-1rounded-mdborderbg-backgroundp-1shadow-sm",
className,
)}
{...props}
/>
));
Menubar.displayName=MenubarPrimitive.Root.displayName;

constMenubarTrigger=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Trigger>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Trigger>
>(({className,...props},ref)=>(
<MenubarPrimitive.Trigger
ref={ref}
className={cn(
"flexcursor-defaultselect-noneitems-centerrounded-smpx-3py-1text-smfont-mediumoutline-nonefocus:bg-accentfocus:text-accent-foregrounddata-[state=open]:bg-accentdata-[state=open]:text-accent-foreground",
className,
)}
{...props}
/>
));
MenubarTrigger.displayName=MenubarPrimitive.Trigger.displayName;

constMenubarSubTrigger=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.SubTrigger>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.SubTrigger>&{
inset?:boolean;
}
>(({className,inset,children,...props},ref)=>(
<MenubarPrimitive.SubTrigger
ref={ref}
className={cn(
"flexcursor-defaultselect-noneitems-centerrounded-smpx-2py-1.5text-smoutline-nonefocus:bg-accentfocus:text-accent-foregrounddata-[state=open]:bg-accentdata-[state=open]:text-accent-foreground",
inset&&"pl-8",
className,
)}
{...props}
>
{children}
<ChevronRightclassName="ml-autoh-4w-4"/>
</MenubarPrimitive.SubTrigger>
));
MenubarSubTrigger.displayName=MenubarPrimitive.SubTrigger.displayName;

constMenubarSubContent=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.SubContent>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.SubContent>
>(({className,...props},ref)=>(
<MenubarPrimitive.SubContent
ref={ref}
className={cn(
"z-50min-w-[8rem]overflow-hiddenrounded-mdborderbg-popoverp-1text-popover-foregroundshadow-lgdata-[state=open]:animate-indata-[state=closed]:animate-outdata-[state=closed]:fade-out-0data-[state=open]:fade-in-0data-[state=closed]:zoom-out-95data-[state=open]:zoom-in-95data-[side=bottom]:slide-in-from-top-2data-[side=left]:slide-in-from-right-2data-[side=right]:slide-in-from-left-2data-[side=top]:slide-in-from-bottom-2origin-(--radix-menubar-content-transform-origin)",
className,
)}
{...props}
/>
));
MenubarSubContent.displayName=MenubarPrimitive.SubContent.displayName;

constMenubarContent=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Content>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Content>
>(({className,align="start",alignOffset=-4,sideOffset=8,...props},ref)=>(
<MenubarPrimitive.Portal>
<MenubarPrimitive.Content
ref={ref}
align={align}
alignOffset={alignOffset}
sideOffset={sideOffset}
className={cn(
"z-50min-w-[12rem]overflow-hiddenrounded-mdborderbg-popoverp-1text-popover-foregroundshadow-mddata-[state=open]:animate-indata-[state=closed]:fade-out-0data-[state=open]:fade-in-0data-[state=closed]:zoom-out-95data-[state=open]:zoom-in-95data-[side=bottom]:slide-in-from-top-2data-[side=left]:slide-in-from-right-2data-[side=right]:slide-in-from-left-2data-[side=top]:slide-in-from-bottom-2origin-(--radix-menubar-content-transform-origin)",
className,
)}
{...props}
/>
</MenubarPrimitive.Portal>
));
MenubarContent.displayName=MenubarPrimitive.Content.displayName;

constMenubarItem=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Item>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Item>&{
inset?:boolean;
}
>(({className,inset,...props},ref)=>(
<MenubarPrimitive.Item
ref={ref}
className={cn(
"relativeflexcursor-defaultselect-noneitems-centerrounded-smpx-2py-1.5text-smoutline-nonefocus:bg-accentfocus:text-accent-foregrounddata-[disabled]:pointer-events-nonedata-[disabled]:opacity-50",
inset&&"pl-8",
className,
)}
{...props}
/>
));
MenubarItem.displayName=MenubarPrimitive.Item.displayName;

constMenubarCheckboxItem=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.CheckboxItem>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.CheckboxItem>
>(({className,children,...props},ref)=>(
<MenubarPrimitive.CheckboxItem
ref={ref}
className={cn(
"relativeflexcursor-defaultselect-noneitems-centerrounded-smpy-1.5pl-8pr-2text-smoutline-nonefocus:bg-accentfocus:text-accent-foregrounddata-[disabled]:pointer-events-nonedata-[disabled]:opacity-50",
className,
)}
{...props}
>
<spanclassName="absoluteleft-2flexh-3.5w-3.5items-centerjustify-center">
<MenubarPrimitive.ItemIndicator>
<CheckclassName="h-4w-4"/>
</MenubarPrimitive.ItemIndicator>
</span>
{children}
</MenubarPrimitive.CheckboxItem>
));
MenubarCheckboxItem.displayName=MenubarPrimitive.CheckboxItem.displayName;

constMenubarRadioItem=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.RadioItem>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.RadioItem>
>(({className,children,...props},ref)=>(
<MenubarPrimitive.RadioItem
ref={ref}
className={cn(
"relativeflexcursor-defaultselect-noneitems-centerrounded-smpy-1.5pl-8pr-2text-smoutline-nonefocus:bg-accentfocus:text-accent-foregrounddata-[disabled]:pointer-events-nonedata-[disabled]:opacity-50",
className,
)}
{...props}
>
<spanclassName="absoluteleft-2flexh-3.5w-3.5items-centerjustify-center">
<MenubarPrimitive.ItemIndicator>
<CircleclassName="h-4w-4fill-current"/>
</MenubarPrimitive.ItemIndicator>
</span>
{children}
</MenubarPrimitive.RadioItem>
));
MenubarRadioItem.displayName=MenubarPrimitive.RadioItem.displayName;

constMenubarLabel=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Label>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Label>&{
inset?:boolean;
}
>(({className,inset,...props},ref)=>(
<MenubarPrimitive.Label
ref={ref}
className={cn("px-2py-1.5text-smfont-semibold",inset&&"pl-8",className)}
{...props}
/>
));
MenubarLabel.displayName=MenubarPrimitive.Label.displayName;

constMenubarSeparator=React.forwardRef<
React.ElementRef<typeofMenubarPrimitive.Separator>,
React.ComponentPropsWithoutRef<typeofMenubarPrimitive.Separator>
>(({className,...props},ref)=>(
<MenubarPrimitive.Separator
ref={ref}
className={cn("-mx-1my-1h-pxbg-muted",className)}
{...props}
/>
));
MenubarSeparator.displayName=MenubarPrimitive.Separator.displayName;

constMenubarShortcut=({className,...props}:React.HTMLAttributes<HTMLSpanElement>)=>{
return(
<span
className={cn("ml-autotext-xstracking-widesttext-muted-foreground",className)}
{...props}
/>
);
};
MenubarShortcut.displayname="MenubarShortcut";

export{
Menubar,
MenubarMenu,
MenubarTrigger,
MenubarContent,
MenubarItem,
MenubarSeparator,
MenubarLabel,
MenubarCheckboxItem,
MenubarRadioGroup,
MenubarRadioItem,
MenubarPortal,
MenubarSubContent,
MenubarSubTrigger,
MenubarGroup,
MenubarSub,
MenubarShortcut,
};
